// AI-GENERATED by Claude (Claude Code), 2026-09-22
// Why: Test scaffolding is tedious and teaches no Flutter concept; the code under test is author-written.
import 'dart:convert';

import 'package:flutter/services.dart';

/// An [AssetBundle] that serves the same text for every key and counts loads.
///
/// Extends [AssetBundle] directly, not [CachingAssetBundle], so every
/// `loadString` call reaches [load] and [loads] reflects real reads.
class FakeAssetBundle extends AssetBundle {
  FakeAssetBundle(this._text);

  final String _text;

  /// Number of times [load] was called.
  int loads = 0;

  @override
  Future<ByteData> load(String key) async {
    loads++;
    return ByteData.sublistView(utf8.encode(_text));
  }
}
