// AI-GENERATED by Claude (Claude Code), 2026-09-23
// Why: Test scaffolding is tedious and teaches no Flutter concept; the code under test is author-written.
import 'dart:async';

import 'package:tenpai/auth/auth_failure.dart';
import 'package:tenpai/auth/auth_repository.dart';
import 'package:tenpai/auth/auth_user.dart';

/// An [AuthRepository] whose [authState] is driven by [emit]. Every write
/// method records its arguments; when [failure] is set the next call throws
/// it instead of succeeding. On success, `signIn`/`signUp`/
/// `signInWithGoogle` emit a user and `signOut` emits null, mirroring what
/// [FirebaseAuthRepository] does through Firebase itself.
class FakeAuthRepository implements AuthRepository {
  final _controller = StreamController<AuthUser?>.broadcast();

  /// Set to make the next write call throw this instead of succeeding.
  AuthFailure? failure;

  /// Arguments passed to [signIn], in order.
  final List<({String email, String password})> signInCalls = [];

  /// Arguments passed to [signUp], in order.
  final List<({String email, String password})> signUpCalls = [];

  /// Number of calls made to [signInWithGoogle].
  int signInWithGoogleCalls = 0;

  /// Emails passed to [sendPasswordReset], in order.
  final List<String> sendPasswordResetCalls = [];

  /// Number of calls made to [signOut].
  int signOutCalls = 0;

  /// Pushes [user] onto [authState], as a real sign-in or the router's
  /// redirect would observe it.
  void emit(AuthUser? user) => _controller.add(user);

  @override
  Stream<AuthUser?> authState() => _controller.stream;

  @override
  Future<void> signIn({required String email, required String password}) async {
    signInCalls.add((email: email, password: password));
    _maybeThrow();
    emit(AuthUser(uid: 'uid-$email', email: email, providerId: 'password'));
  }

  @override
  Future<void> signUp({required String email, required String password}) async {
    signUpCalls.add((email: email, password: password));
    _maybeThrow();
    emit(AuthUser(uid: 'uid-$email', email: email, providerId: 'password'));
  }

  @override
  Future<void> signInWithGoogle() async {
    signInWithGoogleCalls++;
    _maybeThrow();
    emit(const AuthUser(uid: 'uid-google', providerId: 'google.com'));
  }

  @override
  Future<void> sendPasswordReset(String email) async {
    sendPasswordResetCalls.add(email);
    _maybeThrow();
  }

  @override
  Future<void> signOut() async {
    signOutCalls++;
    _maybeThrow();
    emit(null);
  }

  void _maybeThrow() {
    final f = failure;
    if (f != null) throw f;
  }
}
