// AI-GENERATED by Claude (Claude Code), 2026-09-23
// Why: Test scaffolding is tedious and teaches no Flutter concept; the code under test is author-written.
import 'dart:collection';
import 'dart:typed_data';

import 'package:dio/dio.dart';

/// One scripted HTTP response: status code and raw response body.
typedef FakeResponse = (int statusCode, String body);

/// A [HttpClientAdapter] that serves a fixed queue of [FakeResponse]s, one
/// per call to [fetch], and records every requested path so a test can
/// assert what the repository actually asked for. The content type is
/// always `application/json` so dio's transformer decodes the body.
class FakeHttpClientAdapter implements HttpClientAdapter {
  FakeHttpClientAdapter(List<FakeResponse> responses)
    : _responses = Queue.of(responses);

  final Queue<FakeResponse> _responses;

  /// The full URI of every request served, in call order.
  final List<String> requestedPaths = [];

  @override
  Future<ResponseBody> fetch(
    RequestOptions options,
    Stream<Uint8List>? requestStream,
    Future<void>? cancelFuture,
  ) async {
    requestedPaths.add(options.uri.toString());
    if (_responses.isEmpty) {
      throw StateError('FakeHttpClientAdapter: no scripted response left');
    }
    final (statusCode, body) = _responses.removeFirst();
    return ResponseBody.fromString(
      body,
      statusCode,
      headers: {
        Headers.contentTypeHeader: [Headers.jsonContentType],
      },
    );
  }

  @override
  void close({bool force = false}) {}
}
