// AI-GENERATED by Claude (Claude Code), 2026-09-25
// Why: Test scaffolding is tedious and teaches no Flutter concept; the code under test is author-written.
import 'package:material_ui/material_ui.dart';
import 'package:tenpai/settings/settings_repository.dart';

/// A [SettingsRepository] holding one in-memory [ThemeMode], starting at
/// [initial] (system by default, matching a fresh install). [setThemeMode]
/// records every call and updates the stored value, or throws [error]
/// instead when set.
class FakeSettingsRepository implements SettingsRepository {
  FakeSettingsRepository({ThemeMode initial = ThemeMode.system, this.error})
    : _mode = initial;

  ThemeMode _mode;

  /// When non-null, [setThemeMode] throws this instead of writing.
  Exception? error;

  /// Modes passed to [setThemeMode], in order.
  final List<ThemeMode> setThemeModeCalls = [];

  @override
  Future<ThemeMode> themeMode() async => _mode;

  @override
  Future<void> setThemeMode(ThemeMode mode) async {
    setThemeModeCalls.add(mode);
    final e = error;
    if (e != null) throw e;
    _mode = mode;
  }
}
