// AI-GENERATED by Claude (Claude Code), 2026-09-23
// Why: Test scaffolding is tedious and teaches no Flutter concept; the code under test is author-written.
import 'package:tenpai/yaku/yaku.dart';
import 'package:tenpai/yaku/yaku_repository.dart';

/// A [YakuRepository] that serves a fixed catalog, or throws [error] when
/// set, and counts how many times [catalog] was called.
class FakeYakuRepository implements YakuRepository {
  FakeYakuRepository(this._yakus, {this.error});

  final List<Yaku> _yakus;

  /// When non-null, [catalog] throws this instead of returning.
  Exception? error;

  /// Number of calls made to [catalog].
  int callCount = 0;

  @override
  Future<List<Yaku>> catalog() async {
    callCount++;
    final err = error;
    if (err != null) throw err;
    return _yakus;
  }
}
