// AI-GENERATED by Claude (Claude Code), 2026-09-23
// Why: Test scaffolding is tedious and teaches no Flutter concept; the code under test is author-written.
import 'dart:typed_data';

import 'package:tenpai/scanner/tile_photo_source.dart';

/// Scripted [TilePhotoSource]: each [capture] call pops the next entry off
/// [_script]. A [Uint8List] is returned as-is, `null` means the user
/// cancelled, and an [Exception] is thrown instead of returned.
class FakeTilePhotoSource implements TilePhotoSource {
  FakeTilePhotoSource(List<Object?> script) : _script = List.of(script);

  /// One capture returning [bytes] every time it is called.
  FakeTilePhotoSource.returning(Uint8List bytes) : _script = [bytes];

  /// One capture that reports the user backed out of the camera.
  FakeTilePhotoSource.cancelled() : _script = [null];

  /// One capture that fails as if the platform camera broke.
  FakeTilePhotoSource.throwing([Object error = const _CaptureFailure()])
    : _script = [error];

  final List<Object?> _script;

  /// Number of times [capture] was called.
  int captures = 0;

  /// `fromGallery` from the most recent [capture] call; null before any call.
  bool? lastFromGallery;

  @override
  Future<Uint8List?> capture({bool fromGallery = false}) async {
    captures++;
    lastFromGallery = fromGallery;
    final entry = _script.removeAt(0);
    if (entry is Exception) throw entry;
    return entry as Uint8List?;
  }
}

class _CaptureFailure implements Exception {
  const _CaptureFailure();

  @override
  String toString() => 'Exception: fake capture failure';
}
