// AI-GENERATED by Claude (Claude Code), 2026-09-23
// Why: Test scaffolding is tedious and teaches no Flutter concept; the code under test is author-written.
import 'dart:typed_data';

import 'package:tenpai/scanner/tile_identifier.dart';
import 'package:tenpai/shared/models/tile.dart';

/// Scripted [TileIdentifier]: always answers [tile] (`null` for "nothing
/// recognised"), or throws [error] instead. Named apart from lib's own
/// `FakeTileIdentifier` (a deterministic stand-in for firebase_ai) to avoid
/// an import clash.
class ScriptedTileIdentifier implements TileIdentifier {
  ScriptedTileIdentifier({this.tile}) : error = null;

  ScriptedTileIdentifier.throwing(this.error) : tile = null;

  final Tile? tile;
  final Exception? error;

  /// The bytes handed to the most recent [identify] call, if any.
  Uint8List? lastPhoto;

  @override
  Future<Tile?> identify(Uint8List photo) async {
    lastPhoto = photo;
    final err = error;
    if (err != null) throw err;
    return tile;
  }
}
