// AI-GENERATED by Claude (Claude Code), 2026-09-23
// Why: Test scaffolding is tedious and teaches no Flutter concept; the code under test is author-written.
import 'package:tenpai/profile/profile_repository.dart';
import 'package:tenpai/profile/user_profile.dart';

/// A [ProfileRepository] seeded with [profile]; [save] records every call and
/// updates the value [load] returns next. When [error] is set, [load] throws
/// it instead.
class FakeProfileRepository implements ProfileRepository {
  FakeProfileRepository({this.profile, this.error});

  /// Served by [load]; overwritten by [save].
  UserProfile? profile;

  /// When non-null, [load] throws this instead of returning [profile].
  Exception? error;

  /// Profiles passed to [save], in order.
  final List<UserProfile> saveCalls = [];

  @override
  Future<UserProfile?> load() async {
    final e = error;
    if (e != null) throw e;
    return profile;
  }

  @override
  Future<void> save(UserProfile profile) async {
    saveCalls.add(profile);
    this.profile = profile;
  }
}
