// AI-GENERATED by Claude (Claude Code), 2026-09-25
// Why: Test scaffolding is tedious and teaches no Flutter concept; the code under test is author-written.
import 'dart:async';

import 'package:tenpai/scanner/scan_history_repository.dart';
import 'package:tenpai/scanner/scan_record.dart';
import 'package:tenpai/shared/models/tile.dart';

/// A [ScanHistoryRepository] backed by an in-memory list, seeded with
/// [seed] (newest first, as [watch] must emit it). [add] appends a record
/// stamped with [now] and re-emits the whole list, mirroring Isar's
/// watch-query behaviour; when [error] is set, [add] throws it instead and
/// nothing is appended.
class FakeScanHistoryRepository implements ScanHistoryRepository {
  FakeScanHistoryRepository({List<ScanRecord>? seed, this.now, this.error})
    : _records = List.of(seed ?? const []);

  final List<ScanRecord> _records;
  final _controller = StreamController<List<ScanRecord>>.broadcast();

  /// Stamped onto every record [add] appends; defaults to [DateTime.now].
  DateTime Function()? now;

  /// When non-null, [add] throws this instead of appending.
  Exception? error;

  /// Tiles passed to [add], in order.
  final List<Tile> addCalls = [];

  @override
  Future<void> add(Tile tile) async {
    addCalls.add(tile);
    final e = error;
    if (e != null) throw e;
    _records.insert(
      0,
      ScanRecord()
        ..code = tile.code
        ..scannedAt = (now ?? DateTime.now)(),
    );
    _controller.add(List.of(_records));
  }

  @override
  Stream<List<ScanRecord>> watch() async* {
    yield List.of(_records);
    yield* _controller.stream;
  }
}
