// AI-GENERATED by Claude (Claude Code), 2026-09-22
// Why: Test scaffolding is tedious and teaches no Flutter concept; the code under test is author-written.
import 'package:tenpai/progress/progress_repository.dart';
import 'package:tenpai/progress/user_progress.dart';
import 'package:tenpai/shared/models/lesson.dart';

/// A [ProgressRepository] that starts from a given progress and records calls.
class FakeProgressRepository implements ProgressRepository {
  FakeProgressRepository([
    this._progress = const UserProgress(completedLessonIds: {}, xp: 0),
  ]);

  UserProgress _progress;

  /// Ids passed to [completeLesson], in order.
  final List<String> completedIds = [];

  @override
  Future<UserProgress> load() async => _progress;

  @override
  Future<UserProgress> completeLesson(Lesson lesson) async {
    completedIds.add(lesson.id);
    return _progress = _progress.copyWith(
      completedLessonIds: {..._progress.completedLessonIds, lesson.id},
      xp: _progress.xp + lesson.xp,
    );
  }
}
