// AI-GENERATED by Claude (Claude Code), 2026-09-23
// Why: Test scaffolding is tedious and teaches no Flutter concept; the code under test is author-written.
import 'dart:async';

import 'package:tenpai/sensei/sensei_repository.dart';
import 'package:tenpai/sensei/sensei_request.dart';

/// A [SenseiRepository] the test drives one call at a time. Each [explain]
/// call opens a fresh [StreamController] and records the [SenseiRequest] it
/// was asked about; the test then scripts that call through [emit], [close]
/// or [fail], addressing it by its call index (0 = first call). [cancelled]
/// tracks whether the notifier's subscription to a given call was cancelled
/// (`onCancel`), which is the only way to observe an auto-disposed provider
/// from here.
class ScriptedSenseiRepository implements SenseiRepository {
  /// Every request passed to [explain], in call order.
  final List<SenseiRequest> requests = [];

  /// `cancelled[i]` becomes true once the subscription from call `i` (the
  /// `i`-th [explain] invocation) is cancelled.
  final List<bool> cancelled = [];

  final List<StreamController<String>> _controllers = [];

  /// Number of [explain] calls so far.
  int get callCount => requests.length;

  @override
  Stream<String> explain(SenseiRequest request) {
    final index = requests.length;
    requests.add(request);
    cancelled.add(false);
    final controller = StreamController<String>(
      onCancel: () => cancelled[index] = true,
    );
    _controllers.add(controller);
    return controller.stream;
  }

  /// Emits [chunk] on the [call]-th [explain] invocation.
  void emit(String chunk, {int call = 0}) => _controllers[call].add(chunk);

  /// Closes the [call]-th stream with nothing more to emit.
  void close({int call = 0}) => _controllers[call].close();

  /// Errors the [call]-th stream with [error]; the stream closes with it.
  void fail(Object error, {int call = 0}) => _controllers[call].addError(error);
}
