// AI-GENERATED by Claude (Claude Code), 2026-09-22
// Why: Test scaffolding is tedious and teaches no Flutter concept; the code under test is author-written.
import 'package:tenpai/learning/lesson_repository.dart';
import 'package:tenpai/shared/models/lesson.dart';
import 'package:tenpai/shared/models/unit.dart';

/// A [LessonRepository] that serves a fixed list of units, no assets involved.
class FakeLessonRepository implements LessonRepository {
  FakeLessonRepository(this._units);

  final List<Unit> _units;

  @override
  Future<List<Unit>> units() async => _units;

  @override
  Future<Lesson> lessonById(String id) async => _units
      .expand((unit) => unit.lessons)
      .firstWhere(
        (lesson) => lesson.id == id,
        orElse: () => throw ArgumentError.value(id, 'id', 'Unknown lesson'),
      );
}
