// AI-GENERATED by Claude (Claude Code), 2026-09-25
// Why: Test scaffolding is tedious and teaches no Flutter concept; the code under test is author-written.
import 'package:tenpai/yaku/yaku.dart';
import 'package:tenpai/yaku/yaku_cache_source.dart';

/// A [YakuCacheSource] backed by an in-memory list, starting at [seed]
/// (empty by default, as a fresh install has nothing cached). [replace]
/// records every call and overwrites the stored list.
class FakeYakuCacheSource implements YakuCacheSource {
  FakeYakuCacheSource({List<Yaku> seed = const []}) : _yakus = List.of(seed);

  List<Yaku> _yakus;

  /// Lists passed to [replace], in order.
  final List<List<Yaku>> replaceCalls = [];

  @override
  Future<List<Yaku>> read() async => _yakus;

  @override
  Future<void> replace(List<Yaku> yakus) async {
    replaceCalls.add(yakus);
    _yakus = yakus;
  }
}
