// AI-GENERATED by Claude (Claude Code), 2026-09-22
// Why: Test scaffolding is tedious and teaches no Flutter concept; the code under test is author-written.
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:tenpai/learning/lesson_providers.dart';
import 'package:tenpai/learning/lesson_session.dart';
import 'package:tenpai/shared/models/lesson.dart';
import 'package:tenpai/shared/models/lesson_block.dart';
import 'package:tenpai/shared/models/unit.dart';

import '../fakes/fake_lesson_repository.dart';

final _lesson1 = Lesson(
  id: 'l1',
  title: 'one',
  xp: 10,
  blocks: const [LessonBlock.explanation(tile: '1m', title: 't', body: 'b')],
);
final _lesson2 = Lesson(
  id: 'l2',
  title: 'two',
  xp: 15,
  blocks: const [LessonBlock.explanation(tile: '1m', title: 't', body: 'b')],
);
final _units = [
  Unit(id: 'u1', title: 'unit one', lessons: [_lesson1, _lesson2]),
  const Unit(id: 'u2', title: 'unit two', lessons: []),
];

void main() {
  late ProviderContainer container;

  setUp(() {
    container = ProviderContainer.test(
      overrides: [
        lessonRepositoryProvider.overrideWithValue(
          FakeLessonRepository(_units),
        ),
      ],
    );
  });

  group('unitsProvider', () {
    test('resolves to the repository units', () async {
      final units = await container.read(unitsProvider.future);

      expect(units.map((unit) => unit.id), ['u1', 'u2']);
    });
  });

  group('lessonProvider', () {
    test('resolves a lesson by id', () async {
      final lesson = await container.read(lessonProvider('l2').future);

      expect(lesson, _lesson2);
    });

    test('fails for an unknown id', () async {
      await expectLater(
        container.read(lessonProvider('nope').future),
        throwsArgumentError,
      );
    });
  });

  group('currentLessonProvider', () {
    LessonSessionNotifier notifier(String id) =>
        container.read(currentLessonProvider(id).notifier);
    LessonSession session(String id) =>
        container.read(currentLessonProvider(id));

    test('starts at block 0, nothing selected, not answered', () {
      expect(
        session('l1'),
        const LessonSession(lessonId: 'l1', blockIndex: 0, isAnswered: false),
      );
    });

    test('select stores the option', () {
      notifier('l1').select(2);

      expect(session('l1').selectedOption, 2);
      expect(session('l1').isAnswered, isFalse);
    });

    test('check without a selection does nothing', () {
      notifier('l1').check();

      expect(session('l1').isAnswered, isFalse);
    });

    test('check after a selection answers, and freezes the selection', () {
      notifier('l1').select(1);
      notifier('l1').check();
      notifier('l1').select(3);

      expect(session('l1').isAnswered, isTrue);
      expect(session('l1').selectedOption, 1);
    });

    test('next advances one block and clears selection and answer', () {
      notifier('l1').select(1);
      notifier('l1').check();
      notifier('l1').next();

      expect(
        session('l1'),
        const LessonSession(lessonId: 'l1', blockIndex: 1, isAnswered: false),
      );
    });

    test('retry keeps the block index and clears the selection and answer', () {
      notifier('l1').select(1);
      notifier('l1').check();
      notifier('l1').retry();

      expect(
        session('l1'),
        const LessonSession(lessonId: 'l1', blockIndex: 0, isAnswered: false),
      );
    });

    test('retry also clears drill picks', () {
      notifier('l1').toggle(0);
      notifier('l1').toggle(2);
      notifier('l1').check();
      notifier('l1').retry();

      expect(session('l1').picked, isEmpty);
      expect(session('l1').blockIndex, 0);
      expect(session('l1').isAnswered, isFalse);
    });

    test('sessions are independent per lesson id', () {
      notifier('l1').select(1);

      expect(session('l2').selectedOption, isNull);
      expect(session('l2').lessonId, 'l2');
    });
  });
}
