// AI-GENERATED by Claude (Claude Code), 2026-09-23
// Why: Test scaffolding is tedious and teaches no Flutter concept; the code under test is author-written.
import 'dart:async';

import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:go_router/go_router.dart';
import 'package:material_ui/material_ui.dart';
import 'package:tenpai/app/router.dart';
import 'package:tenpai/learning/lesson_providers.dart';
import 'package:tenpai/learning/lesson_screen.dart';
import 'package:tenpai/progress/progress_providers.dart';
import 'package:tenpai/sensei/sensei_providers.dart';
import 'package:tenpai/sensei/sensei_request.dart';
import 'package:tenpai/shared/models/lesson.dart';
import 'package:tenpai/shared/models/lesson_block.dart';
import 'package:tenpai/shared/models/tile.dart';
import 'package:tenpai/shared/models/unit.dart';
import 'package:tenpai/shared/theme/app_colors.dart';
import 'package:tenpai/shared/theme/app_theme.dart';
import 'package:tenpai/shared/widgets/tile_size.dart';
import 'package:tenpai/shared/widgets/tile_state.dart';
import 'package:tenpai/shared/widgets/tile_widget.dart';

import '../fakes/fake_lesson_repository.dart';
import '../fakes/fake_progress_repository.dart';
import '../fakes/fake_sensei_repository.dart';

final _lesson = Lesson(
  id: 'l1',
  title: 'Leçon test',
  xp: 10,
  blocks: [
    const LessonBlock.explanation(
      tile: '1m',
      title: 'Titre A',
      body: 'Corps A',
    ),
    LessonBlock.quiz(
      question: 'Quelle tuile ?',
      hand: ['1m', '2m', '3m'],
      options: ['6s', '9p', '5s', '1z'],
      correctIndex: 2,
      feedback: 'FEEDBACK LINE',
    ),
    const LessonBlock.explanation(
      tile: '9p',
      title: 'Titre B',
      body: 'Corps B',
    ),
  ],
);

const _drillPrompt = 'Trouvez la suite 2-3-4 de pinzu.';
const _drillHand = [
  '1m',
  '2m',
  '3m',
  '4m',
  '5m',
  '6m',
  '7m',
  '8m',
  '9m',
  '2p',
  '3p',
  '4p',
  '1p',
];
const _drillAnswers = [9, 10, 11];
const _drillFeedback = 'DRILL FEEDBACK LINE';

final _drillLesson = Lesson(
  id: 'l2',
  title: 'Leçon drill test',
  xp: 10,
  blocks: [
    LessonBlock.drill(
      prompt: _drillPrompt,
      hand: _drillHand,
      answers: _drillAnswers,
      feedback: _drillFeedback,
    ),
  ],
);

const _interactivePrompt = 'Complétez la suite en sozu.';
const _interactiveGroup = ['1s', '2s'];
const _interactiveSlot = 2;
const _interactiveRack = ['3s', '4z', '5z', '6z'];
const _interactiveCorrectIndex = 0;
const _interactiveFeedback = 'INTERACTIVE FEEDBACK LINE';

final _interactiveLesson = Lesson(
  id: 'l3',
  title: 'Leçon interactive test',
  xp: 10,
  blocks: [
    LessonBlock.interactive(
      prompt: _interactivePrompt,
      group: _interactiveGroup,
      slot: _interactiveSlot,
      rack: _interactiveRack,
      correctIndex: _interactiveCorrectIndex,
      feedback: _interactiveFeedback,
    ),
  ],
);

/// Bundles the router and the progress fake so a test can both drive
/// navigation and inspect what got recorded.
class _Harness {
  _Harness(this.router, this.progressRepository, this.senseiRepository);
  final GoRouter router;
  final FakeProgressRepository progressRepository;
  final ScriptedSenseiRepository senseiRepository;
}

Future<_Harness> _pumpLessonScreen(
  WidgetTester tester, {
  String id = 'l1',
  ThemeData? theme,
}) async {
  final progressRepository = FakeProgressRepository();
  final senseiRepository = ScriptedSenseiRepository();
  final router = GoRouter(
    initialLocation: '/',
    routes: [
      GoRoute(path: '/', builder: (context, state) => const Text('path')),
      GoRoute(
        path: AppRoutes.lesson(':id'),
        builder: (context, state) =>
            LessonScreen(lessonId: state.pathParameters['id']!),
      ),
    ],
  );

  await tester.pumpWidget(
    ProviderScope(
      overrides: [
        lessonRepositoryProvider.overrideWithValue(
          FakeLessonRepository([
            Unit(
              id: 'u1',
              title: 'Unité',
              lessons: [_lesson, _drillLesson, _interactiveLesson],
            ),
          ]),
        ),
        progressRepositoryProvider.overrideWithValue(progressRepository),
        senseiRepositoryProvider.overrideWithValue(senseiRepository),
      ],
      retry: (_, _) => null,
      child: MaterialApp.router(
        theme: theme ?? lightTheme(),
        routerConfig: router,
      ),
    ),
  );
  await tester.pumpAndSettle();

  // `push` returns a Future that only resolves once the pushed route pops,
  // so it must not be awaited here or the pump would hang forever.
  unawaited(router.push(AppRoutes.lesson(id)));
  await tester.pumpAndSettle();

  return _Harness(router, progressRepository, senseiRepository);
}

Finder _optionTile(String code) => find.byWidgetPredicate(
  (widget) =>
      widget is TileWidget &&
      widget.tile == Tile.parse(code) &&
      widget.size == TileSize.option,
);

Finder _handTile(String code) => find.byWidgetPredicate(
  (widget) =>
      widget is TileWidget &&
      widget.tile == Tile.parse(code) &&
      widget.size == TileSize.hand,
);

Future<void> _tapContinue(WidgetTester tester) async {
  await tester.tap(find.widgetWithText(FilledButton, 'Continuer').last);
  await tester.pumpAndSettle();
}

Future<void> _tapVerifier(WidgetTester tester) async {
  await tester.tap(find.widgetWithText(FilledButton, 'Vérifier'));
  await tester.pumpAndSettle();
}

Future<void> _tapReessayer(WidgetTester tester) async {
  await tester.tap(find.widgetWithText(FilledButton, 'Réessayer'));
  await tester.pumpAndSettle();
}

void main() {
  group('LessonScreen', () {
    testWidgets(
      'the first block shows the explanation title and a Continuer button, no Verifier',
      (tester) async {
        await _pumpLessonScreen(tester);

        expect(find.text('Titre A'), findsOneWidget);
        expect(find.text('Corps A'), findsOneWidget);
        expect(find.widgetWithText(FilledButton, 'Continuer'), findsOneWidget);
        expect(find.text('Vérifier'), findsNothing);
      },
    );

    testWidgets(
      'the quiz shows its question and disables Verifier until an option is picked',
      (tester) async {
        await _pumpLessonScreen(tester);
        await _tapContinue(tester);

        expect(find.text('Quelle tuile ?'), findsOneWidget);
        var verifier = tester.widget<FilledButton>(
          find.widgetWithText(FilledButton, 'Vérifier'),
        );
        expect(verifier.onPressed, isNull);
        final slide = tester.widget<AnimatedSlide>(find.byType(AnimatedSlide));
        expect(slide.offset, const Offset(0, 1));

        await tester.tap(_optionTile('6s'));
        await tester.pumpAndSettle();

        verifier = tester.widget<FilledButton>(
          find.widgetWithText(FilledButton, 'Vérifier'),
        );
        expect(verifier.onPressed, isNotNull);
      },
    );

    testWidgets(
      'a wrong answer shows the miss feedback, no highlight and offers Réessayer',
      (tester) async {
        await _pumpLessonScreen(tester);
        await _tapContinue(tester);

        await tester.tap(_optionTile('6s'));
        await tester.pumpAndSettle();
        await _tapVerifier(tester);

        expect(find.text('Pas tout à fait'), findsOneWidget);
        expect(
          find.text("Ce n'est pas la bonne tuile. Regardez encore la main."),
          findsOneWidget,
        );
        expect(
          tester.widget<TileWidget>(_optionTile('6s')).state,
          TileState.incorrect,
        );
        expect(
          tester.widget<TileWidget>(_optionTile('5s')).state,
          isNot(TileState.highlighted),
        );
        expect(find.widgetWithText(FilledButton, 'Réessayer'), findsOneWidget);
      },
    );

    testWidgets(
      'a wrong answer shows a Pourquoi link that asks the Sensei once and '
      'keeps Réessayer enabled while it loads',
      (tester) async {
        final harness = await _pumpLessonScreen(tester);
        await _tapContinue(tester);

        await tester.tap(_optionTile('6s'));
        await tester.pumpAndSettle();
        await _tapVerifier(tester);

        expect(find.text('Pourquoi ?'), findsOneWidget);
        expect(harness.senseiRepository.callCount, 0);

        // Not `pumpAndSettle`: the panel's pulsing-tiles animation repeats
        // forever once the Sensei state leaves idle.
        await tester.tap(find.text('Pourquoi ?'));
        await tester.pump();

        expect(harness.senseiRepository.callCount, 1);
        expect(find.text('Le sensei regarde votre main'), findsOneWidget);
        final retry = tester.widget<FilledButton>(
          find.widgetWithText(FilledButton, 'Réessayer'),
        );
        expect(retry.onPressed, isNotNull);
      },
    );

    testWidgets('a right answer shows the authored feedback line', (
      tester,
    ) async {
      await _pumpLessonScreen(tester);
      await _tapContinue(tester);

      await tester.tap(_optionTile('5s'));
      await tester.pumpAndSettle();
      await _tapVerifier(tester);

      expect(find.text('Bien joué !'), findsOneWidget);
      expect(find.text('FEEDBACK LINE'), findsOneWidget);
      expect(
        tester.widget<TileWidget>(_optionTile('5s')).state,
        TileState.correct,
      );
    });

    testWidgets('completing every block records the lesson as done and pops', (
      tester,
    ) async {
      final harness = await _pumpLessonScreen(tester);

      await _tapContinue(tester);
      await tester.tap(_optionTile('5s'));
      await tester.pumpAndSettle();
      await _tapVerifier(tester);
      await _tapContinue(tester);
      await _tapContinue(tester);

      expect(harness.progressRepository.completedIds, ['l1']);
      expect(find.text('path'), findsOneWidget);
    });

    testWidgets('the close button pops without completing the lesson', (
      tester,
    ) async {
      final harness = await _pumpLessonScreen(tester);

      await tester.tap(find.byIcon(Icons.close));
      await tester.pumpAndSettle();

      expect(find.text('path'), findsOneWidget);
      expect(harness.progressRepository.completedIds, isEmpty);
    });

    testWidgets('retrying after a wrong answer returns to the same block, cleared, before '
        'completion can be recorded', (tester) async {
      final harness = await _pumpLessonScreen(tester);

      await _tapContinue(tester);
      await tester.tap(_optionTile('6s'));
      await tester.pumpAndSettle();
      await _tapVerifier(tester);

      expect(harness.progressRepository.completedIds, isEmpty);

      await _tapReessayer(tester);

      expect(find.text('Quelle tuile ?'), findsOneWidget);
      final slide = tester.widget<AnimatedSlide>(find.byType(AnimatedSlide));
      expect(slide.offset, const Offset(0, 1));
      expect(
        tester.widget<TileWidget>(_optionTile('6s')).state,
        TileState.normal,
      );
      final verifier = tester.widget<FilledButton>(
        find.widgetWithText(FilledButton, 'Vérifier'),
      );
      expect(verifier.onPressed, isNull);
      expect(harness.progressRepository.completedIds, isEmpty);

      await tester.tap(_optionTile('5s'));
      await tester.pumpAndSettle();
      await _tapVerifier(tester);

      expect(find.widgetWithText(FilledButton, 'Continuer'), findsOneWidget);

      await _tapContinue(tester);
      await _tapContinue(tester);

      expect(harness.progressRepository.completedIds, ['l1']);
      expect(find.text('path'), findsOneWidget);
    });

    testWidgets('an unknown lesson id shows the retry view', (tester) async {
      await _pumpLessonScreen(tester, id: 'nope');

      expect(find.text('Impossible de charger la leçon'), findsOneWidget);
      expect(find.widgetWithText(TextButton, 'Réessayer'), findsOneWidget);
    });

    testWidgets(
      'reopening a completed lesson restarts at block 0 and records it again',
      (tester) async {
        final harness = await _pumpLessonScreen(tester);

        await _tapContinue(tester);
        await tester.tap(_optionTile('5s'));
        await tester.pumpAndSettle();
        await _tapVerifier(tester);
        await _tapContinue(tester);
        await _tapContinue(tester);

        expect(harness.progressRepository.completedIds, ['l1']);
        expect(find.text('path'), findsOneWidget);

        unawaited(harness.router.push(AppRoutes.lesson('l1')));
        await tester.pumpAndSettle();

        expect(find.text('Titre A'), findsOneWidget);

        await _tapContinue(tester);
        await tester.tap(_optionTile('5s'));
        await tester.pumpAndSettle();
        await _tapVerifier(tester);
        await _tapContinue(tester);
        await _tapContinue(tester);

        expect(harness.progressRepository.completedIds, ['l1', 'l1']);
      },
    );

    testWidgets(
      'a right answer feedback sheet uses the dark success panel colour',
      (tester) async {
        await _pumpLessonScreen(tester, theme: darkTheme());
        await _tapContinue(tester);

        await tester.tap(_optionTile('5s'));
        await tester.pumpAndSettle();
        await _tapVerifier(tester);

        final decoratedBox = tester.widget<DecoratedBox>(
          find.descendant(
            of: find.byType(AnimatedSlide),
            matching: find.byType(DecoratedBox),
          ),
        );
        final decoration = decoratedBox.decoration as BoxDecoration;
        expect(decoration.color, darkColors.successPanel);
      },
    );
  });

  group('LessonScreen drill', () {
    testWidgets(
      'a wrong drill pick shows Pourquoi, asks the Sensei once with a '
      'sorted picked list and keeps Réessayer enabled while it loads',
      (tester) async {
        final harness = await _pumpLessonScreen(tester, id: 'l2');

        expect(find.text(_drillPrompt), findsOneWidget);

        // Tapped in descending index order (12 then 0) to prove the widget
        // sorts `picked` before building the request, not the tap order.
        await tester.tap(_handTile('1p'));
        await tester.pumpAndSettle();
        await tester.tap(_handTile('1m'));
        await tester.pumpAndSettle();
        await _tapVerifier(tester);

        expect(find.text('Pas tout à fait'), findsOneWidget);
        expect(find.text('Pourquoi ?'), findsOneWidget);
        expect(harness.senseiRepository.callCount, 0);
        expect(
          find.text('Il manque des tuiles, ou certaines sont en trop.'),
          findsOneWidget,
        );
        expect(
          tester.widget<TileWidget>(_handTile(_drillHand[0])).state,
          TileState.incorrect,
        );
        expect(
          tester.widget<TileWidget>(_handTile(_drillHand[12])).state,
          TileState.incorrect,
        );
        for (final index in _drillAnswers) {
          expect(
            tester.widget<TileWidget>(_handTile(_drillHand[index])).state,
            TileState.normal,
          );
        }

        // Not `pumpAndSettle`: the panel's pulsing-tiles animation repeats
        // forever once the Sensei state leaves idle.
        await tester.tap(find.text('Pourquoi ?'));
        await tester.pump();

        expect(harness.senseiRepository.callCount, 1);
        final request =
            harness.senseiRepository.requests.single as DrillMissRequest;
        expect(request.prompt, _drillPrompt);
        expect(request.hand, _drillHand);
        expect(request.picked, [0, 12]);
        expect(request.answers, _drillAnswers);

        final retry = tester.widget<FilledButton>(
          find.widgetWithText(FilledButton, 'Réessayer'),
        );
        expect(retry.onPressed, isNotNull);
      },
    );

    testWidgets(
      'Verifier is disabled with no drill picks and enables after one tap',
      (tester) async {
        await _pumpLessonScreen(tester, id: 'l2');

        var verifier = tester.widget<FilledButton>(
          find.widgetWithText(FilledButton, 'Vérifier'),
        );
        expect(verifier.onPressed, isNull);

        await tester.tap(_handTile(_drillHand[_drillAnswers.first]));
        await tester.pumpAndSettle();

        verifier = tester.widget<FilledButton>(
          find.widgetWithText(FilledButton, 'Vérifier'),
        );
        expect(verifier.onPressed, isNotNull);
      },
    );

    testWidgets('a correct drill pick shows no Pourquoi link', (tester) async {
      await _pumpLessonScreen(tester, id: 'l2');

      for (final index in _drillAnswers) {
        await tester.tap(_handTile(_drillHand[index]));
        await tester.pumpAndSettle();
      }
      await _tapVerifier(tester);

      expect(find.text('Bien joué !'), findsOneWidget);
      expect(find.text('Pourquoi ?'), findsNothing);
      expect(find.text(_drillFeedback), findsOneWidget);
      expect(find.widgetWithText(FilledButton, 'Continuer'), findsOneWidget);
      for (final index in _drillAnswers) {
        expect(
          tester.widget<TileWidget>(_handTile(_drillHand[index])).state,
          TileState.correct,
        );
      }
    });
  });

  group('LessonScreen interactive', () {
    Finder optionTiles() => find.byWidgetPredicate(
      (widget) => widget is TileWidget && widget.size == TileSize.option,
    );

    testWidgets('the empty slot shows no tile before answering', (
      tester,
    ) async {
      await _pumpLessonScreen(tester, id: 'l3');

      expect(find.text(_interactivePrompt), findsOneWidget);
      // Only the group (2) and rack (4) tiles render; the slot itself is a
      // plain outline, not a TileWidget, until the block is answered.
      expect(
        optionTiles(),
        findsNWidgets(_interactiveGroup.length + _interactiveRack.length),
      );
    });

    testWidgets(
      'Verifier is disabled with no rack pick and enables after one tap',
      (tester) async {
        await _pumpLessonScreen(tester, id: 'l3');

        var verifier = tester.widget<FilledButton>(
          find.widgetWithText(FilledButton, 'Vérifier'),
        );
        expect(verifier.onPressed, isNull);

        await tester.tap(
          _optionTile(_interactiveRack[_interactiveCorrectIndex]),
        );
        await tester.pumpAndSettle();

        verifier = tester.widget<FilledButton>(
          find.widgetWithText(FilledButton, 'Vérifier'),
        );
        expect(verifier.onPressed, isNotNull);
      },
    );

    testWidgets('a correct rack pick fills the slot and shows Continuer', (
      tester,
    ) async {
      await _pumpLessonScreen(tester, id: 'l3');

      await tester.tap(_optionTile(_interactiveRack[_interactiveCorrectIndex]));
      await tester.pumpAndSettle();
      await _tapVerifier(tester);

      expect(find.text('Bien joué !'), findsOneWidget);
      expect(find.text(_interactiveFeedback), findsOneWidget);
      expect(find.widgetWithText(FilledButton, 'Continuer'), findsOneWidget);
      expect(
        optionTiles(),
        findsNWidgets(_interactiveGroup.length + _interactiveRack.length + 1),
      );
      final filled = tester
          .widgetList<TileWidget>(optionTiles())
          .where(
            (w) =>
                w.tile ==
                    Tile.parse(_interactiveRack[_interactiveCorrectIndex]) &&
                w.state == TileState.correct,
          );
      expect(filled, isNotEmpty);
    });

    testWidgets(
      'a wrong rack pick shows the miss line, the picked tile incorrect and '
      'the right rack tile not highlighted',
      (tester) async {
        const wrongIndex = 1;
        await _pumpLessonScreen(tester, id: 'l3');

        await tester.tap(_optionTile(_interactiveRack[wrongIndex]));
        await tester.pumpAndSettle();
        await _tapVerifier(tester);

        expect(find.text('Pas tout à fait'), findsOneWidget);
        expect(
          find.text('Cette tuile ne complète pas le groupe.'),
          findsOneWidget,
        );
        expect(find.widgetWithText(FilledButton, 'Réessayer'), findsOneWidget);
        expect(find.text('Pourquoi ?'), findsNothing);
        expect(
          optionTiles(),
          findsNWidgets(_interactiveGroup.length + _interactiveRack.length + 1),
        );
        final filled = tester
            .widgetList<TileWidget>(optionTiles())
            .where(
              (w) =>
                  w.tile == Tile.parse(_interactiveRack[wrongIndex]) &&
                  w.state == TileState.incorrect,
            );
        expect(filled, isNotEmpty);
        expect(
          tester
              .widget<TileWidget>(
                _optionTile(_interactiveRack[_interactiveCorrectIndex]),
              )
              .state,
          isNot(TileState.highlighted),
        );
      },
    );

    testWidgets(
      'retrying after a wrong rack pick empties the slot and clears the '
      'selection',
      (tester) async {
        const wrongIndex = 1;
        await _pumpLessonScreen(tester, id: 'l3');

        await tester.tap(_optionTile(_interactiveRack[wrongIndex]));
        await tester.pumpAndSettle();
        await _tapVerifier(tester);
        await _tapReessayer(tester);

        expect(
          optionTiles(),
          findsNWidgets(_interactiveGroup.length + _interactiveRack.length),
        );
        final verifier = tester.widget<FilledButton>(
          find.widgetWithText(FilledButton, 'Vérifier'),
        );
        expect(verifier.onPressed, isNull);
      },
    );
  });
}
