// AI-GENERATED by Claude (Claude Code), 2026-09-23
// Why: Test scaffolding is tedious and teaches no Flutter concept; the code under test is author-written.
import 'dart:async';

import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:go_router/go_router.dart';
import 'package:material_ui/material_ui.dart';
import 'package:tenpai/app/router.dart';
import 'package:tenpai/learning/lesson_providers.dart';
import 'package:tenpai/learning/lesson_screen.dart';
import 'package:tenpai/progress/progress_providers.dart';
import 'package:tenpai/shared/models/lesson.dart';
import 'package:tenpai/shared/models/lesson_block.dart';
import 'package:tenpai/shared/models/tile.dart';
import 'package:tenpai/shared/models/unit.dart';
import 'package:tenpai/shared/theme/app_colors.dart';
import 'package:tenpai/shared/theme/app_theme.dart';
import 'package:tenpai/shared/widgets/tile_size.dart';
import 'package:tenpai/shared/widgets/tile_state.dart';
import 'package:tenpai/shared/widgets/tile_widget.dart';

import '../fakes/fake_lesson_repository.dart';
import '../fakes/fake_progress_repository.dart';

final _lesson = Lesson(
  id: 'l1',
  title: 'Leçon test',
  xp: 10,
  blocks: [
    const LessonBlock.explanation(
      tile: '1m',
      title: 'Titre A',
      body: 'Corps A',
    ),
    LessonBlock.quiz(
      question: 'Quelle tuile ?',
      hand: ['1m', '2m', '3m'],
      options: ['6s', '9p', '5s', '1z'],
      correctIndex: 2,
      feedback: 'FEEDBACK LINE',
    ),
    const LessonBlock.explanation(
      tile: '9p',
      title: 'Titre B',
      body: 'Corps B',
    ),
  ],
);

/// Bundles the router and the progress fake so a test can both drive
/// navigation and inspect what got recorded.
class _Harness {
  _Harness(this.router, this.progressRepository);
  final GoRouter router;
  final FakeProgressRepository progressRepository;
}

Future<_Harness> _pumpLessonScreen(
  WidgetTester tester, {
  String id = 'l1',
  ThemeData? theme,
}) async {
  final progressRepository = FakeProgressRepository();
  final router = GoRouter(
    initialLocation: '/',
    routes: [
      GoRoute(path: '/', builder: (context, state) => const Text('path')),
      GoRoute(
        path: AppRoutes.lesson(':id'),
        builder: (context, state) =>
            LessonScreen(lessonId: state.pathParameters['id']!),
      ),
    ],
  );

  await tester.pumpWidget(
    ProviderScope(
      overrides: [
        lessonRepositoryProvider.overrideWithValue(
          FakeLessonRepository([
            Unit(id: 'u1', title: 'Unité', lessons: [_lesson]),
          ]),
        ),
        progressRepositoryProvider.overrideWithValue(progressRepository),
      ],
      retry: (_, _) => null,
      child: MaterialApp.router(
        theme: theme ?? lightTheme(),
        routerConfig: router,
      ),
    ),
  );
  await tester.pumpAndSettle();

  // `push` returns a Future that only resolves once the pushed route pops,
  // so it must not be awaited here or the pump would hang forever.
  unawaited(router.push(AppRoutes.lesson(id)));
  await tester.pumpAndSettle();

  return _Harness(router, progressRepository);
}

Finder _optionTile(String code) => find.byWidgetPredicate(
  (widget) =>
      widget is TileWidget &&
      widget.tile == Tile.parse(code) &&
      widget.size == TileSize.option,
);

Future<void> _tapContinue(WidgetTester tester) async {
  await tester.tap(find.widgetWithText(FilledButton, 'Continuer').last);
  await tester.pumpAndSettle();
}

Future<void> _tapVerifier(WidgetTester tester) async {
  await tester.tap(find.widgetWithText(FilledButton, 'Vérifier'));
  await tester.pumpAndSettle();
}

void main() {
  group('LessonScreen', () {
    testWidgets(
      'the first block shows the explanation title and a Continuer button, no Verifier',
      (tester) async {
        await _pumpLessonScreen(tester);

        expect(find.text('Titre A'), findsOneWidget);
        expect(find.text('Corps A'), findsOneWidget);
        expect(find.widgetWithText(FilledButton, 'Continuer'), findsOneWidget);
        expect(find.text('Vérifier'), findsNothing);
      },
    );

    testWidgets(
      'the quiz shows its question and disables Verifier until an option is picked',
      (tester) async {
        await _pumpLessonScreen(tester);
        await _tapContinue(tester);

        expect(find.text('Quelle tuile ?'), findsOneWidget);
        var verifier = tester.widget<FilledButton>(
          find.widgetWithText(FilledButton, 'Vérifier'),
        );
        expect(verifier.onPressed, isNull);
        final slide = tester.widget<AnimatedSlide>(find.byType(AnimatedSlide));
        expect(slide.offset, const Offset(0, 1));

        await tester.tap(_optionTile('6s'));
        await tester.pumpAndSettle();

        verifier = tester.widget<FilledButton>(
          find.widgetWithText(FilledButton, 'Vérifier'),
        );
        expect(verifier.onPressed, isNotNull);
      },
    );

    testWidgets(
      'a wrong answer shows the miss feedback and highlights the correct tile',
      (tester) async {
        await _pumpLessonScreen(tester);
        await _tapContinue(tester);

        await tester.tap(_optionTile('6s'));
        await tester.pumpAndSettle();
        await _tapVerifier(tester);

        expect(find.text('Pas tout à fait'), findsOneWidget);
        expect(
          find.text('La bonne réponse était la tuile entourée de vert.'),
          findsOneWidget,
        );
        expect(
          tester.widget<TileWidget>(_optionTile('6s')).state,
          TileState.incorrect,
        );
        expect(
          tester.widget<TileWidget>(_optionTile('5s')).state,
          TileState.highlighted,
        );
      },
    );

    testWidgets('a right answer shows the authored feedback line', (
      tester,
    ) async {
      await _pumpLessonScreen(tester);
      await _tapContinue(tester);

      await tester.tap(_optionTile('5s'));
      await tester.pumpAndSettle();
      await _tapVerifier(tester);

      expect(find.text('Bien joué !'), findsOneWidget);
      expect(find.text('FEEDBACK LINE'), findsOneWidget);
      expect(
        tester.widget<TileWidget>(_optionTile('5s')).state,
        TileState.correct,
      );
    });

    testWidgets('completing every block records the lesson as done and pops', (
      tester,
    ) async {
      final harness = await _pumpLessonScreen(tester);

      await _tapContinue(tester);
      await tester.tap(_optionTile('5s'));
      await tester.pumpAndSettle();
      await _tapVerifier(tester);
      await _tapContinue(tester);
      await _tapContinue(tester);

      expect(harness.progressRepository.completedIds, ['l1']);
      expect(find.text('path'), findsOneWidget);
    });

    testWidgets('the close button pops without completing the lesson', (
      tester,
    ) async {
      final harness = await _pumpLessonScreen(tester);

      await tester.tap(find.byIcon(Icons.close));
      await tester.pumpAndSettle();

      expect(find.text('path'), findsOneWidget);
      expect(harness.progressRepository.completedIds, isEmpty);
    });

    testWidgets(
      'completing the lesson after a wrong answer still records it and pops',
      (tester) async {
        final harness = await _pumpLessonScreen(tester);

        await _tapContinue(tester);
        await tester.tap(_optionTile('6s'));
        await tester.pumpAndSettle();
        await _tapVerifier(tester);
        await _tapContinue(tester);
        await _tapContinue(tester);

        expect(harness.progressRepository.completedIds, ['l1']);
        expect(find.text('path'), findsOneWidget);
      },
    );

    testWidgets('an unknown lesson id shows the retry view', (tester) async {
      await _pumpLessonScreen(tester, id: 'nope');

      expect(find.text('Impossible de charger la leçon'), findsOneWidget);
      expect(find.widgetWithText(TextButton, 'Réessayer'), findsOneWidget);
    });

    testWidgets(
      'reopening a completed lesson restarts at block 0 and records it again',
      (tester) async {
        final harness = await _pumpLessonScreen(tester);

        await _tapContinue(tester);
        await tester.tap(_optionTile('5s'));
        await tester.pumpAndSettle();
        await _tapVerifier(tester);
        await _tapContinue(tester);
        await _tapContinue(tester);

        expect(harness.progressRepository.completedIds, ['l1']);
        expect(find.text('path'), findsOneWidget);

        unawaited(harness.router.push(AppRoutes.lesson('l1')));
        await tester.pumpAndSettle();

        expect(find.text('Titre A'), findsOneWidget);

        await _tapContinue(tester);
        await tester.tap(_optionTile('5s'));
        await tester.pumpAndSettle();
        await _tapVerifier(tester);
        await _tapContinue(tester);
        await _tapContinue(tester);

        expect(harness.progressRepository.completedIds, ['l1', 'l1']);
      },
    );

    testWidgets(
      'a right answer feedback sheet uses the dark success panel colour',
      (tester) async {
        await _pumpLessonScreen(tester, theme: darkTheme());
        await _tapContinue(tester);

        await tester.tap(_optionTile('5s'));
        await tester.pumpAndSettle();
        await _tapVerifier(tester);

        final decoratedBox = tester.widget<DecoratedBox>(
          find.descendant(
            of: find.byType(AnimatedSlide),
            matching: find.byType(DecoratedBox),
          ),
        );
        final decoration = decoratedBox.decoration as BoxDecoration;
        expect(decoration.color, darkColors.successPanel);
      },
    );
  });
}
