// AI-GENERATED by Claude (Claude Code), 2026-09-23
// Why: Test scaffolding is tedious and teaches no Flutter concept; the code under test is author-written.
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:go_router/go_router.dart';
import 'package:material_ui/material_ui.dart';
import 'package:tenpai/app/router.dart';
import 'package:tenpai/learning/lesson_path_screen.dart';
import 'package:tenpai/learning/lesson_providers.dart';
import 'package:tenpai/progress/progress_providers.dart';
import 'package:tenpai/progress/user_progress.dart';
import 'package:tenpai/shared/models/lesson.dart';
import 'package:tenpai/shared/models/unit.dart';
import 'package:tenpai/shared/theme/app_theme.dart';

import '../fakes/fake_lesson_repository.dart';
import '../fakes/fake_progress_repository.dart';

const _unitA = Unit(
  id: 'u1',
  title: 'Unité A',
  lessons: [
    Lesson(id: 'u1-l1', title: 'Leçon 1', xp: 10, blocks: []),
    Lesson(id: 'u1-l2', title: 'Leçon 2', xp: 10, blocks: []),
  ],
);

const _unitB = Unit(
  id: 'u2',
  title: 'Unité B',
  lessons: [Lesson(id: 'u2-l1', title: 'Leçon 1', xp: 10, blocks: [])],
);

GoRouter _buildRouter() => GoRouter(
  initialLocation: '/',
  routes: [
    GoRoute(path: '/', builder: (context, state) => const LessonPathScreen()),
    GoRoute(
      path: AppRoutes.lesson(':id'),
      builder: (context, state) =>
          Text('lesson ${state.pathParameters['id']}'),
    ),
  ],
);

Future<void> _pumpPathScreen(
  WidgetTester tester, {
  required UserProgress progress,
  required GoRouter router,
}) async {
  await tester.pumpWidget(
    ProviderScope(
      overrides: [
        lessonRepositoryProvider.overrideWithValue(
          FakeLessonRepository([_unitA, _unitB]),
        ),
        progressRepositoryProvider.overrideWithValue(
          FakeProgressRepository(progress),
        ),
      ],
      retry: (_, _) => null,
      child: MaterialApp.router(theme: lightTheme(), routerConfig: router),
    ),
  );
  await tester.pumpAndSettle();
}

void main() {
  group('LessonPathScreen', () {
    testWidgets('fresh progress shows the counter on unit A and a lock on unit B', (
      tester,
    ) async {
      await _pumpPathScreen(
        tester,
        progress: const UserProgress(completedLessonIds: {}, xp: 0),
        router: _buildRouter(),
      );

      expect(find.text('0 / 2'), findsOneWidget);
      expect(find.byIcon(Icons.lock), findsOneWidget);
    });

    testWidgets('unit A completed shows a check and unlocks the counter on unit B', (
      tester,
    ) async {
      await _pumpPathScreen(
        tester,
        progress: const UserProgress(
          completedLessonIds: {'u1-l1', 'u1-l2'},
          xp: 20,
        ),
        router: _buildRouter(),
      );

      expect(find.byIcon(Icons.check), findsOneWidget);
      expect(find.text('0 / 1'), findsOneWidget);
    });

    testWidgets('tapping the locked unit B does not navigate', (tester) async {
      await _pumpPathScreen(
        tester,
        progress: const UserProgress(completedLessonIds: {}, xp: 0),
        router: _buildRouter(),
      );

      await tester.tap(find.text('Unité B'));
      await tester.pumpAndSettle();

      expect(find.byType(LessonPathScreen), findsOneWidget);
    });

    testWidgets('tapping unit A navigates to its first lesson', (tester) async {
      await _pumpPathScreen(
        tester,
        progress: const UserProgress(completedLessonIds: {}, xp: 0),
        router: _buildRouter(),
      );

      await tester.tap(find.text('Unité A'));
      await tester.pumpAndSettle();

      expect(find.text('lesson u1-l1'), findsOneWidget);
    });
  });
}
