// AI-GENERATED by Claude (Claude Code), 2026-09-22
// Why: Test scaffolding is tedious and teaches no Flutter concept; the code under test is author-written.
import 'package:flutter_test/flutter_test.dart';
import 'package:tenpai/learning/lesson_asset_source.dart';
import 'package:tenpai/learning/lesson_repository_impl.dart';

import '../fakes/fake_asset_bundle.dart';

void main() {
  // Wires rootBundle to the pubspec assets under `flutter test`.
  TestWidgetsFlutterBinding.ensureInitialized();

  group('LessonRepositoryImpl over the bundled assets', () {
    late LessonRepositoryImpl repository;

    setUp(() {
      repository = LessonRepositoryImpl(LessonAssetSource());
    });

    test('loads the six units in path order', () async {
      final units = await repository.units();

      expect(units.map((unit) => unit.id), [
        'unit_01',
        'unit_02',
        'unit_03',
        'unit_04',
        'unit_05',
        'unit_06',
      ]);
    });

    test('finds unit 1 lesson 1 with its four blocks', () async {
      final lesson = await repository.lessonById('unit_01_lesson_01');

      expect(lesson.title, 'Trois familles, un même alphabet');
      expect(lesson.xp, 10);
      expect(lesson.blocks, hasLength(4));
    });

    test('throws ArgumentError for an unknown lesson id', () {
      expect(repository.lessonById('nope'), throwsArgumentError);
    });
  });

  group('LessonRepositoryImpl caching', () {
    const unitJson = '{"id": "u", "title": "t", "lessons": []}';

    test('reads each asset once across repeated units() calls', () async {
      final bundle = FakeAssetBundle(unitJson);
      final repository = LessonRepositoryImpl(
        LessonAssetSource(bundle: bundle),
      );

      // Concurrent first calls share one load; a later call hits the cache.
      await Future.wait([repository.units(), repository.units()]);
      await repository.units();

      expect(bundle.loads, 6);
    });

    test('a failed units() does not cache the failure', () async {
      final bundle = FakeAssetBundle(unitJson, failFirst: true);
      final repository = LessonRepositoryImpl(
        LessonAssetSource(bundle: bundle),
      );

      await expectLater(repository.units(), throwsException);

      final units = await repository.units();

      expect(units, hasLength(6));
    });
  });
}
