// AI-GENERATED by Claude (Claude Code), 2026-09-23
// Why: Test scaffolding is tedious and teaches no Flutter concept; the code under test is author-written.
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:tenpai/auth/auth_providers.dart';
import 'package:tenpai/auth/auth_user.dart';

import '../fakes/fake_auth_repository.dart';

const _user = AuthUser(uid: 'u1', email: 'a@b.com', providerId: 'password');

void main() {
  test('authStateProvider emits what the repository emits', () async {
    final repository = FakeAuthRepository();
    final container = ProviderContainer.test(
      overrides: [authRepositoryProvider.overrideWithValue(repository)],
      retry: (_, _) => null,
    );

    final events = <AsyncValue<AuthUser?>>[];
    final subscription = container.listen(
      authStateProvider,
      (_, next) => events.add(next),
    );
    addTearDown(subscription.close);

    repository.emit(null);
    await Future<void>.delayed(Duration.zero);
    repository.emit(_user);
    await Future<void>.delayed(Duration.zero);

    expect(events, [
      const AsyncData<AuthUser?>(null),
      const AsyncData<AuthUser?>(_user),
    ]);
  });
}
