// AI-GENERATED by Claude (Claude Code), 2026-09-23
// Why: Test scaffolding is tedious and teaches no Flutter concept; the code under test is author-written.
import 'package:flutter_test/flutter_test.dart';
import 'package:tenpai/auth/auth_failure.dart';

void main() {
  group('AuthFailure.fromCode', () {
    for (final code in ['invalid-credential', 'wrong-password', 'user-not-found']) {
      test('maps "$code" to invalidCredentials', () {
        expect(AuthFailure.fromCode(code), AuthFailure.invalidCredentials);
      });
    }

    test('maps "email-already-in-use" to emailInUse', () {
      expect(
        AuthFailure.fromCode('email-already-in-use'),
        AuthFailure.emailInUse,
      );
    });

    test('maps "weak-password" to weakPassword', () {
      expect(AuthFailure.fromCode('weak-password'), AuthFailure.weakPassword);
    });

    test('maps "invalid-email" to invalidEmail', () {
      expect(AuthFailure.fromCode('invalid-email'), AuthFailure.invalidEmail);
    });

    test('maps "network-request-failed" to network', () {
      expect(
        AuthFailure.fromCode('network-request-failed'),
        AuthFailure.network,
      );
    });

    for (final code in ['web-context-canceled', 'canceled']) {
      test('maps "$code" to cancelled', () {
        expect(AuthFailure.fromCode(code), AuthFailure.cancelled);
      });
    }

    test('maps an unmapped code to unknown', () {
      expect(AuthFailure.fromCode('something-else'), AuthFailure.unknown);
    });
  });

  test('every value has a non-empty French message', () {
    for (final failure in AuthFailure.values) {
      expect(failure.message, isNotEmpty);
    }
  });
}
