// AI-GENERATED by Claude (Claude Code), 2026-09-23
// Why: Test scaffolding is tedious and teaches no Flutter concept; the code under test is author-written.
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:material_ui/material_ui.dart';
import 'package:tenpai/auth/auth_failure.dart';
import 'package:tenpai/auth/auth_providers.dart';
import 'package:tenpai/auth/login_screen.dart';
import 'package:tenpai/shared/theme/app_theme.dart';

import '../fakes/fake_auth_repository.dart';

Future<FakeAuthRepository> _pumpLogin(
  WidgetTester tester, {
  required bool signUp,
}) async {
  final repository = FakeAuthRepository();
  // The default test surface is too short for the whole form: the ListView
  // is lazy, so the Google/Apple buttons below the fold never enter the tree.
  await tester.binding.setSurfaceSize(const Size(800, 1200));
  addTearDown(() => tester.binding.setSurfaceSize(null));
  await tester.pumpWidget(
    ProviderScope(
      overrides: [authRepositoryProvider.overrideWithValue(repository)],
      retry: (_, _) => null,
      child: MaterialApp(
        theme: lightTheme(),
        home: LoginScreen(signUp: signUp),
      ),
    ),
  );
  await tester.pumpAndSettle();
  return repository;
}

void main() {
  group('LoginScreen', () {
    testWidgets(
      '« Se connecter » calls signIn with the typed, trimmed email and password',
      (tester) async {
        final repository = await _pumpLogin(tester, signUp: false);

        await tester.enterText(find.byType(TextField).at(0), '  a@b.com  ');
        await tester.enterText(find.byType(TextField).at(1), 'secret');
        await tester.tap(find.widgetWithText(FilledButton, 'Se connecter'));
        await tester.pumpAndSettle();

        expect(repository.signInCalls, [
          (email: 'a@b.com', password: 'secret'),
        ]);
      },
    );

    testWidgets(
      'an invalidCredentials failure shows Email ou mot de passe incorrect.',
      (tester) async {
        final repository = await _pumpLogin(tester, signUp: false);
        repository.failure = AuthFailure.invalidCredentials;

        await tester.enterText(find.byType(TextField).at(0), 'a@b.com');
        await tester.enterText(find.byType(TextField).at(1), 'wrong');
        await tester.tap(find.widgetWithText(FilledButton, 'Se connecter'));
        await tester.pumpAndSettle();

        expect(
          find.text(AuthFailure.invalidCredentials.message),
          findsOneWidget,
        );
      },
    );

    testWidgets('switching to Inscription changes the CTA and submits signUp', (
      tester,
    ) async {
      final repository = await _pumpLogin(tester, signUp: false);

      await tester.tap(find.text('Inscription'));
      await tester.pumpAndSettle();

      expect(
        find.widgetWithText(FilledButton, 'Créer un compte'),
        findsOneWidget,
      );

      await tester.enterText(find.byType(TextField).at(0), 'new@b.com');
      await tester.enterText(find.byType(TextField).at(1), 'secret1');
      await tester.tap(find.widgetWithText(FilledButton, 'Créer un compte'));
      await tester.pumpAndSettle();

      expect(repository.signUpCalls, [
        (email: 'new@b.com', password: 'secret1'),
      ]);
    });

    testWidgets(
      '« Mot de passe oublié ? » with an empty email shows invalidEmail '
      'without calling the repository',
      (tester) async {
        final repository = await _pumpLogin(tester, signUp: false);

        await tester.tap(find.text('Mot de passe oublié ?'));
        await tester.pumpAndSettle();

        expect(find.text(AuthFailure.invalidEmail.message), findsOneWidget);
        expect(repository.sendPasswordResetCalls, isEmpty);
      },
    );

    testWidgets(
      '« Mot de passe oublié ? » with an email sends the reset and shows '
      'Email envoyé.',
      (tester) async {
        final repository = await _pumpLogin(tester, signUp: false);

        await tester.enterText(find.byType(TextField).at(0), 'a@b.com');
        await tester.tap(find.text('Mot de passe oublié ?'));
        await tester.pump();
        await tester.pump();

        expect(repository.sendPasswordResetCalls, ['a@b.com']);
        expect(find.text('Email envoyé.'), findsOneWidget);
      },
    );

    testWidgets('« Continuer avec Google » calls signInWithGoogle', (
      tester,
    ) async {
      final repository = await _pumpLogin(tester, signUp: false);

      await tester.tap(find.text('Continuer avec Google'));
      await tester.pumpAndSettle();

      expect(repository.signInWithGoogleCalls, 1);
    });

    testWidgets('a cancelled failure shows no error line', (tester) async {
      final repository = await _pumpLogin(tester, signUp: false);
      repository.failure = AuthFailure.cancelled;

      await tester.tap(find.text('Continuer avec Google'));
      await tester.pumpAndSettle();

      for (final failure in AuthFailure.values) {
        expect(find.text(failure.message), findsNothing);
      }
    });

    testWidgets('the Apple button is disabled', (tester) async {
      await _pumpLogin(tester, signUp: false);

      final apple = tester.widget<FilledButton>(
        find.widgetWithText(FilledButton, 'Continuer avec Apple'),
      );
      expect(apple.onPressed, isNull);
    });
  });
}
