// AI-GENERATED by Claude (Claude Code), 2026-09-23
// Why: Test scaffolding is tedious and teaches no Flutter concept; the code under test is author-written.
import 'package:flutter_test/flutter_test.dart';
import 'package:go_router/go_router.dart';
import 'package:material_ui/material_ui.dart';
import 'package:tenpai/auth/welcome_screen.dart';
import 'package:tenpai/shared/theme/app_theme.dart';

GoRouter _buildRouter() => GoRouter(
  initialLocation: '/welcome',
  routes: [
    GoRoute(path: '/welcome', builder: (_, _) => const WelcomeScreen()),
    GoRoute(
      path: '/login',
      builder: (_, state) =>
          Text('login mode=${state.uri.queryParameters['mode']}'),
    ),
  ],
);

Future<void> _pumpWelcome(WidgetTester tester) async {
  await tester.pumpWidget(
    MaterialApp.router(theme: lightTheme(), routerConfig: _buildRouter()),
  );
  await tester.pumpAndSettle();
}

void main() {
  group('WelcomeScreen', () {
    testWidgets('« Commencer » navigates to login with mode=signup', (
      tester,
    ) async {
      await _pumpWelcome(tester);

      await tester.tap(find.text('Commencer'));
      await tester.pumpAndSettle();

      expect(find.text('login mode=signup'), findsOneWidget);
    });

    testWidgets(
      '« J\'ai déjà un compte » navigates to login without a mode',
      (tester) async {
        await _pumpWelcome(tester);

        await tester.tap(find.text("J'ai déjà un compte"));
        await tester.pumpAndSettle();

        expect(find.text('login mode=null'), findsOneWidget);
      },
    );
  });
}
