// AI-GENERATED by Claude (Claude Code), 2026-09-22
// Why: Test scaffolding is tedious and teaches no Flutter concept; the code under test is author-written.
import 'package:flutter_test/flutter_test.dart';
import 'package:tenpai/progress/in_memory_progress_repository.dart';
import 'package:tenpai/shared/models/lesson.dart';
import 'package:tenpai/shared/models/lesson_block.dart';

final _lesson1 = Lesson(
  id: 'l1',
  title: 'one',
  xp: 10,
  blocks: const [LessonBlock.drill()],
);
final _lesson2 = Lesson(
  id: 'l2',
  title: 'two',
  xp: 15,
  blocks: const [LessonBlock.drill()],
);

void main() {
  late InMemoryProgressRepository repository;

  setUp(() {
    repository = InMemoryProgressRepository();
  });

  test('starts empty with zero xp', () async {
    final progress = await repository.load();

    expect(progress.completedLessonIds, isEmpty);
    expect(progress.xp, 0);
  });

  test('completing a lesson records its id and its xp', () async {
    final progress = await repository.completeLesson(_lesson1);

    expect(progress.isCompleted('l1'), isTrue);
    expect(progress.xp, _lesson1.xp);
  });

  test('completing the same lesson twice adds xp once', () async {
    await repository.completeLesson(_lesson1);
    final progress = await repository.completeLesson(_lesson1);

    expect(progress.completedLessonIds, {'l1'});
    expect(progress.xp, _lesson1.xp);
  });

  test('completing two lessons sums their xp', () async {
    await repository.completeLesson(_lesson1);
    final progress = await repository.completeLesson(_lesson2);

    expect(progress.completedLessonIds, {'l1', 'l2'});
    expect(progress.xp, _lesson1.xp + _lesson2.xp);
  });

  test('load returns the latest progress', () async {
    await repository.completeLesson(_lesson1);

    expect(await repository.load(), await repository.load());
    expect((await repository.load()).xp, _lesson1.xp);
  });
}
