// AI-GENERATED by Claude (Claude Code), 2026-09-22
// Why: Test scaffolding is tedious and teaches no Flutter concept; the code under test is author-written.
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:tenpai/progress/in_memory_progress_repository.dart';
import 'package:tenpai/progress/progress_providers.dart';
import 'package:tenpai/progress/user_progress.dart';
import 'package:tenpai/shared/models/lesson.dart';

import '../fakes/fake_progress_repository.dart';

const _lesson = Lesson(id: 'l1', title: 'one', xp: 10, blocks: []);

void main() {
  test('progressRepositoryProvider defaults to the in-memory repository', () {
    final container = ProviderContainer.test();

    expect(
      container.read(progressRepositoryProvider),
      isA<InMemoryProgressRepository>(),
    );
  });

  group('userProgressProvider', () {
    late FakeProgressRepository repository;
    late ProviderContainer container;

    setUp(() {
      repository = FakeProgressRepository(
        const UserProgress(completedLessonIds: {'l0'}, xp: 5),
      );
      container = ProviderContainer.test(
        overrides: [progressRepositoryProvider.overrideWithValue(repository)],
      );
    });

    test('loads the repository progress', () async {
      final progress = await container.read(userProgressProvider.future);

      expect(progress.completedLessonIds, {'l0'});
      expect(progress.xp, 5);
    });

    test('completeLesson delegates and exposes the new progress', () async {
      await container.read(userProgressProvider.future);

      await container
          .read(userProgressProvider.notifier)
          .completeLesson(_lesson);

      expect(repository.completedIds, ['l1']);
      expect(
        container.read(userProgressProvider),
        const AsyncData(UserProgress(completedLessonIds: {'l0', 'l1'}, xp: 15)),
      );
    });
  });
}
