// AI-GENERATED by Claude (Claude Code), 2026-09-22
// Why: Test scaffolding is tedious and teaches no Flutter concept; the code under test is author-written.
import 'package:flutter_test/flutter_test.dart';
import 'package:tenpai/progress/user_progress.dart';
import 'package:tenpai/shared/models/lesson.dart';
import 'package:tenpai/shared/models/unit.dart';

Lesson _lesson(String id) =>
    Lesson(id: id, title: id, xp: 10, blocks: const []);

Unit _unit(String id, List<String> lessonIds) =>
    Unit(id: id, title: id, lessons: [for (final l in lessonIds) _lesson(l)]);

const _fresh = UserProgress(completedLessonIds: {}, xp: 0);

void main() {
  group('UserProgress.isCompleted', () {
    test('is false on fresh progress', () {
      expect(_fresh.isCompleted('l1'), isFalse);
    });

    test('is true once the id is in the set', () {
      const progress = UserProgress(completedLessonIds: {'l1'}, xp: 10);

      expect(progress.isCompleted('l1'), isTrue);
      expect(progress.isCompleted('l2'), isFalse);
    });
  });

  group('statusOf', () {
    final unit = _unit('u1', ['l1', 'l2', 'l3']);

    test('first lesson is current, the rest locked, on fresh progress', () {
      expect(statusOf(unit, 0, _fresh), LessonStatus.current);
      expect(statusOf(unit, 1, _fresh), LessonStatus.locked);
      expect(statusOf(unit, 2, _fresh), LessonStatus.locked);
    });

    test('completing lesson 1 flips lesson 2 from locked to current', () {
      const progress = UserProgress(completedLessonIds: {'l1'}, xp: 10);

      expect(statusOf(unit, 0, progress), LessonStatus.completed);
      expect(statusOf(unit, 1, progress), LessonStatus.current);
      expect(statusOf(unit, 2, progress), LessonStatus.locked);
    });

    test('a completed lesson stays completed even if the previous is not', () {
      const progress = UserProgress(completedLessonIds: {'l2'}, xp: 10);

      expect(statusOf(unit, 1, progress), LessonStatus.completed);
    });
  });

  group('isUnitPlayable', () {
    final units = [
      _unit('u1', ['l1', 'l2']),
      _unit('u2', ['l3']),
      _unit('u3', const []),
      _unit('u4', ['l4']),
    ];

    test('first unit with lessons is playable on fresh progress', () {
      expect(isUnitPlayable(units, 0, _fresh), isTrue);
    });

    test('second unit is locked until the first unit\'s last lesson', () {
      const partial = UserProgress(completedLessonIds: {'l1'}, xp: 10);
      const done = UserProgress(completedLessonIds: {'l1', 'l2'}, xp: 20);

      expect(isUnitPlayable(units, 1, _fresh), isFalse);
      expect(isUnitPlayable(units, 1, partial), isFalse);
      expect(isUnitPlayable(units, 1, done), isTrue);
    });

    test('a unit with no lessons is never playable', () {
      const all = UserProgress(
        completedLessonIds: {'l1', 'l2', 'l3', 'l4'},
        xp: 40,
      );

      expect(isUnitPlayable(units, 2, all), isFalse);
    });

    test('a unit after an empty unit stays locked', () {
      const all = UserProgress(
        completedLessonIds: {'l1', 'l2', 'l3', 'l4'},
        xp: 40,
      );

      expect(isUnitPlayable(units, 3, all), isFalse);
    });
  });
}
