// AI-GENERATED by Claude (Claude Code), 2026-09-23
// Why: Test scaffolding is tedious and teaches no Flutter concept; the code under test is author-written.
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:tenpai/app/app.dart';
import 'package:tenpai/auth/auth_providers.dart';
import 'package:tenpai/auth/auth_user.dart';
import 'package:tenpai/learning/lesson_providers.dart';
import 'package:tenpai/profile/profile_providers.dart';
import 'package:tenpai/profile/user_profile.dart';
import 'package:tenpai/progress/progress_providers.dart';
import 'package:tenpai/shared/models/lesson.dart';
import 'package:tenpai/shared/models/lesson_block.dart';
import 'package:tenpai/shared/models/unit.dart';

import '../fakes/fake_auth_repository.dart';
import '../fakes/fake_lesson_repository.dart';
import '../fakes/fake_profile_repository.dart';
import '../fakes/fake_progress_repository.dart';

const _signedInUser = AuthUser(
  uid: 'u1',
  email: 'a@b.com',
  providerId: 'password',
);

final _units = [
  Unit(
    id: 'u1',
    title: 'Lire les tuiles',
    lessons: [
      Lesson(
        id: 'u1-l1',
        title: 'Leçon 1',
        xp: 10,
        blocks: const [LessonBlock.drill()],
      ),
    ],
  ),
];

/// Pumps the real [TenpaiApp] so the redirect, the shell and the tab screens
/// all run for real; only the repositories underneath them are faked.
Future<FakeAuthRepository> _pumpApp(
  WidgetTester tester, {
  FakeProfileRepository? profileRepository,
}) async {
  final auth = FakeAuthRepository();
  await tester.pumpWidget(
    ProviderScope(
      overrides: [
        authRepositoryProvider.overrideWithValue(auth),
        profileRepositoryProvider.overrideWithValue(
          profileRepository ?? FakeProfileRepository(),
        ),
        progressRepositoryProvider.overrideWithValue(FakeProgressRepository()),
        lessonRepositoryProvider.overrideWithValue(
          FakeLessonRepository(_units),
        ),
      ],
      retry: (_, _) => null,
      child: const TenpaiApp(),
    ),
  );
  await tester.pumpAndSettle();
  return auth;
}

void main() {
  group('router redirect', () {
    testWidgets('a signed-out user sees the welcome screen', (tester) async {
      final auth = await _pumpApp(tester);

      auth.emit(null);
      await tester.pumpAndSettle();

      expect(find.text('Tenpai'), findsOneWidget);
      expect(find.text('Commencer'), findsOneWidget);
    });

    testWidgets('a signed-in user with no profile is sent to onboarding', (
      tester,
    ) async {
      final auth = await _pumpApp(tester);

      auth.emit(_signedInUser);
      await tester.pumpAndSettle();

      expect(find.text('Vous connaissez déjà le mahjong ?'), findsOneWidget);
    });

    testWidgets('a signed-in user with a profile sees the lesson path', (
      tester,
    ) async {
      final auth = await _pumpApp(
        tester,
        profileRepository: FakeProfileRepository(
          profile: const UserProfile(
            level: MahjongLevel.seen,
            dailyGoalMinutes: 10,
          ),
        ),
      );

      auth.emit(_signedInUser);
      await tester.pumpAndSettle();

      expect(find.text('Lire les tuiles'), findsOneWidget);
    });

    testWidgets('signing out from the tabs returns to welcome', (tester) async {
      final auth = await _pumpApp(
        tester,
        profileRepository: FakeProfileRepository(
          profile: const UserProfile(
            level: MahjongLevel.seen,
            dailyGoalMinutes: 10,
          ),
        ),
      );
      auth.emit(_signedInUser);
      await tester.pumpAndSettle();
      expect(find.text('Lire les tuiles'), findsOneWidget);

      auth.emit(null);
      await tester.pumpAndSettle();

      expect(find.text('Tenpai'), findsOneWidget);
      expect(find.text('Commencer'), findsOneWidget);
    });
  });
}
