#!/usr/bin/env python3
# AI-GENERATED by Claude (Claude Code), 2026-09-17
# Why: Project tooling and setup so study time goes to Flutter code.
"""PreToolUse guard: Claude tutors, the user implements.

Denies any tool call that would write under ``lib/`` unless the user granted
implementation for this turn by starting their prompt with ``/implement``
(see ``implement_grant.py``). A prompt starting with ``review`` grants a
narrower right: ``Edit`` calls under ``lib/`` whose old and new strings differ
only in ``///`` dartdoc lines. Also confines subagents to their write scope:

  test-writer   -> test/**
  doc-reviewer  -> README.md
  flutter-reviewer -> nothing

Reads the hook JSON on stdin. Emits a PreToolUse "deny" decision when a write
is out of bounds; otherwise prints nothing so the normal permission flow runs.
Never raises: any parsing problem falls through to "no decision".
"""

import json
import os
import re
import sys
import time
from pathlib import Path

GRANT_FILE = Path(".claude/.implement-grant")
DARTDOC_GRANT_FILE = Path(".claude/.dartdoc-grant")
GRANT_TTL_SECONDS = 60 * 60
DARTDOC_LINE = re.compile(r"^\s*///")

EDIT_TOOLS = {"Edit", "Write", "MultiEdit", "NotebookEdit"}
TOKENSAVE_EDIT_TOOLS = {
    "mcp__tokensave__tokensave_str_replace",
    "mcp__tokensave__tokensave_multi_str_replace",
    "mcp__tokensave__tokensave_replace_symbol",
    "mcp__tokensave__tokensave_insert_at",
    "mcp__tokensave__tokensave_insert_at_symbol",
    "mcp__tokensave__tokensave_ast_grep_rewrite",
}
PATH_KEY = re.compile(r"(path|file)", re.IGNORECASE)

# Subagent write scopes. A subagent not listed here gets the main-thread rules.
AGENT_SCOPES = {
    "test-writer": ("test/",),
    "doc-reviewer": ("README.md",),
    "flutter-reviewer": (),
}

# Shell commands that write into lib/. Heuristic, not a sandbox: the point is
# to stop the *habit*, and the deny reason tells Claude what to do instead.
SHELL_WRITE_PATTERNS = [
    re.compile(r"(>>?|\btee\b(\s+-a)?)\s*[\"']?\.?/?lib/"),
    re.compile(r"\bsed\b[^|;&]*\s-[a-zA-Z]*i[^|;&]*\blib/"),
    re.compile(r"\bsed\b[^|;&]*--in-place[^|;&]*\blib/"),
    re.compile(r"\bperl\b\s+-[a-zA-Z]*i[^|;&]*\blib/"),
    re.compile(r"\b(cp|mv|rm|touch|mkdir|install|rsync|ln|rmdir)\b[^|;&]*\blib/?\b"),
    re.compile(r"\bfind\b[^|;&]*\blib\b[^|;&]*(-delete|-exec)"),
    re.compile(r"\bflutter\s+create\b"),
    re.compile(r"\b(cat|printf|echo)\b[^|;&]*>\s*[\"']?\.?/?lib/"),
]
SHELL_ALLOWED = [
    re.compile(r"\bdart\s+run\s+build_runner\b"),  # generated files only
    re.compile(r"\bdart\s+fix\b"),
    re.compile(r"\bdart\s+format\b"),
    re.compile(r"\bflutter\s+pub\b"),
]

DENY_LIB = (
    "Tenpai tutor mode: lib/ is written by the user, not by Claude. Explain the "
    "change in chat instead (concept + a snippet of at most 10 lines + the "
    "pub-cache file the API comes from) and let them write it. If the user "
    "really wants Claude to implement this, they start their next message with "
    "`/implement <scope>`."
)
DENY_AGENT = (
    "Tenpai tutor mode: the {agent} agent may only write under {scope}. Report "
    "what should change and where; do not write it."
)
DENY_DARTDOC = (
    "Tenpai review mode: this turn may only add or rewrite `///` dartdoc lines "
    "under lib/ with the Edit tool (old_string and new_string must be identical "
    "once `///` lines are removed). Report any code change as a finding for "
    "the user instead."
)


def _grant_active() -> bool:
    return _fresh(GRANT_FILE)


def _dartdoc_grant_active() -> bool:
    return _fresh(DARTDOC_GRANT_FILE)


def _fresh(grant: Path) -> bool:
    try:
        age = time.time() - grant.stat().st_mtime
    except OSError:
        return False
    return age < GRANT_TTL_SECONDS


def _without_dartdoc(text: str) -> str:
    return "\n".join(l for l in text.splitlines() if not DARTDOC_LINE.match(l))


def _dartdoc_only(tool: str, tool_input) -> bool:
    """True when an Edit changes nothing but `///` lines."""
    if tool != "Edit" or not isinstance(tool_input, dict):
        return False
    old = tool_input.get("old_string")
    new = tool_input.get("new_string")
    if not isinstance(old, str) or not isinstance(new, str):
        return False
    return _without_dartdoc(old) == _without_dartdoc(new)


def _relative(path: str, cwd: str) -> str:
    """Path relative to the project root, POSIX style, or '' if outside it."""
    try:
        resolved = Path(path)
        if not resolved.is_absolute():
            resolved = Path(cwd) / resolved
        return resolved.resolve().relative_to(Path(cwd).resolve()).as_posix()
    except (OSError, ValueError):
        return ""


def _paths_in(value, found=None):
    """Collect every string under a key that looks like a path/file key."""
    if found is None:
        found = []
    if isinstance(value, dict):
        for key, item in value.items():
            if isinstance(item, str) and PATH_KEY.search(key):
                found.append(item)
            else:
                _paths_in(item, found)
    elif isinstance(value, list):
        for item in value:
            _paths_in(item, found)
    return found


def _in_scope(rel: str, scope) -> bool:
    return any(rel == s or rel.startswith(s) for s in scope)


def _deny(reason: str) -> None:
    print(
        json.dumps(
            {
                "hookSpecificOutput": {
                    "hookEventName": "PreToolUse",
                    "permissionDecision": "deny",
                    "permissionDecisionReason": reason,
                }
            }
        )
    )


def _check_file_tool(tool, tool_input, targets, agent, cwd):
    rels = [r for r in (_relative(t, cwd) for t in targets) if r]
    if agent in AGENT_SCOPES:
        scope = AGENT_SCOPES[agent]
        bad = [r for r in rels if not _in_scope(r, scope)]
        if bad:
            shown = ", ".join(scope) or "nothing"
            _deny(DENY_AGENT.format(agent=agent, scope=shown) + f" (target: {bad[0]})")
            return
    if not any(r.startswith("lib/") for r in rels) or _grant_active():
        return
    if _dartdoc_grant_active() and agent is None:
        if not _dartdoc_only(tool, tool_input):
            _deny(DENY_DARTDOC)
        return
    _deny(DENY_LIB)


def _check_bash(command: str, agent):
    if any(p.search(command) for p in SHELL_ALLOWED):
        return
    touches_lib = any(p.search(command) for p in SHELL_WRITE_PATTERNS)
    if not touches_lib:
        return
    if agent in AGENT_SCOPES:
        shown = ", ".join(AGENT_SCOPES[agent]) or "nothing"
        _deny(DENY_AGENT.format(agent=agent, scope=shown))
        return
    if not _grant_active():
        _deny(DENY_LIB)


def main() -> None:
    try:
        data = json.load(sys.stdin)
    except (json.JSONDecodeError, OSError):
        return
    cwd = data.get("cwd") or os.getcwd()
    os.chdir(cwd)
    tool = data.get("tool_name", "")
    tool_input = data.get("tool_input") or {}
    agent = data.get("agent_type")

    if tool in EDIT_TOOLS or tool in TOKENSAVE_EDIT_TOOLS:
        _check_file_tool(tool, tool_input, _paths_in(tool_input), agent, cwd)
    elif tool == "Bash":
        _check_bash(str(tool_input.get("command", "")), agent)


if __name__ == "__main__":
    main()
