#!/usr/bin/env python3
# AI-GENERATED by Claude (Claude Code), 2026-09-17
# Why: Project tooling and setup so study time goes to Flutter code.
"""UserPromptSubmit hook: turn a leading ``/implement`` into a one-turn grant.

Only the user types prompts, so only the user can create the grant file that
``guard_lib_writes.py`` honours. Any prompt that does not start with
``/implement`` removes the grant, which makes it single-turn by construction
(the TTL in the guard is a backstop for crashed sessions).
"""

import json
import re
import sys
import time
from pathlib import Path

GRANT_FILE = Path(".claude/.implement-grant")
IMPLEMENT = re.compile(r"^\s*/implement\b")


def main() -> None:
    try:
        data = json.load(sys.stdin)
    except (json.JSONDecodeError, OSError):
        return
    prompt = data.get("prompt") or ""
    if IMPLEMENT.match(prompt):
        GRANT_FILE.parent.mkdir(parents=True, exist_ok=True)
        GRANT_FILE.write_text(str(time.time()))
        # Plain stdout from UserPromptSubmit is added to Claude's context.
        print(
            "Implement grant active for this turn only: writes under lib/ are "
            "allowed, limited to the scope stated after /implement. Explain "
            "every file written."
        )
    else:
        GRANT_FILE.unlink(missing_ok=True)


if __name__ == "__main__":
    main()
