#!/usr/bin/env python3
# AI-GENERATED by Claude (Claude Code), 2026-09-17
# Why: Project tooling and setup so study time goes to Flutter code.
"""UserPromptSubmit hook: turn a leading ``/implement`` or ``review`` into a
one-turn grant.

Only the user types prompts, so only the user can create the grant files that
``guard_lib_writes.py`` honours. Any prompt that starts with neither removes
both grants, which makes them single-turn by construction (the TTL in the
guard is a backstop for crashed sessions).

  /implement <scope>  -> .claude/.implement-grant  (any write under lib/)
  review ...          -> .claude/.dartdoc-grant    (Edit of ``///`` lines only)
"""

import json
import re
import sys
import time
from pathlib import Path

GRANT_FILE = Path(".claude/.implement-grant")
DARTDOC_GRANT_FILE = Path(".claude/.dartdoc-grant")
IMPLEMENT = re.compile(r"^\s*/implement\b")
REVIEW = re.compile(r"^\s*review\b", re.IGNORECASE)


def main() -> None:
    try:
        data = json.load(sys.stdin)
    except (json.JSONDecodeError, OSError):
        return
    prompt = data.get("prompt") or ""
    if IMPLEMENT.match(prompt):
        DARTDOC_GRANT_FILE.unlink(missing_ok=True)
        GRANT_FILE.parent.mkdir(parents=True, exist_ok=True)
        GRANT_FILE.write_text(str(time.time()))
        # Plain stdout from UserPromptSubmit is added to Claude's context.
        print(
            "Implement grant active for this turn only: writes under lib/ are "
            "allowed, limited to the scope stated after /implement. Explain "
            "every file written."
        )
    elif REVIEW.match(prompt):
        GRANT_FILE.unlink(missing_ok=True)
        DARTDOC_GRANT_FILE.parent.mkdir(parents=True, exist_ok=True)
        DARTDOC_GRANT_FILE.write_text(str(time.time()))
        print(
            "Dartdoc grant active for this turn only: Edit calls under lib/ "
            "pass the guard when the diff touches nothing but `///` lines. "
            "Write the missing or weak dartdoc yourself (short, the why or the "
            "non-obvious behaviour, never a restatement of the signature); "
            "add a `dartdoc` row to docs/AI_CONTRIBUTIONS.md once per file. "
            "Code changes stay findings for the user."
        )
    else:
        GRANT_FILE.unlink(missing_ok=True)
        DARTDOC_GRANT_FILE.unlink(missing_ok=True)


if __name__ == "__main__":
    main()
