// AI-GENERATED by Claude (Claude Code), 2026-09-25
// Why: Test scaffolding is tedious and teaches no Flutter concept; the code under test is author-written.
import 'package:flutter_test/flutter_test.dart';
import 'package:tenpai/yaku/cached_yaku_repository.dart';
import 'package:tenpai/yaku/yaku.dart';

import '../fakes/fake_yaku_cache_source.dart';
import '../fakes/fake_yaku_repository.dart';

const _riichi = Yaku(
  id: 'riichi',
  name: 'Riichi',
  kanji: '立直',
  nickname: 'Prête',
  summary: 'Main fermée prête à gagner.',
  description: 'Déclarée quand la main est tenpai et fermée.',
  han: 1,
  tier: YakuTier.essential,
  tiles: ['1m', '2m', '3m'],
);
const _tanyao = Yaku(
  id: 'tanyao',
  name: 'Tanyao',
  kanji: '断幺九',
  nickname: 'Tout simple',
  summary: 'Que des tuiles simples.',
  description: 'Aucun terminal ni honneur.',
  han: 1,
  tier: YakuTier.essential,
  tiles: ['2m', '3m', '4m'],
);

void main() {
  group('CachedYakuRepository.catalog', () {
    test('a working remote returns the fresh catalog and refreshes the '
        'cache', () async {
      final remote = FakeYakuRepository([_riichi, _tanyao]);
      final cache = FakeYakuCacheSource(seed: [_tanyao]);
      final repository = CachedYakuRepository(remote, cache);

      final result = await repository.catalog();

      expect(result, [_riichi, _tanyao]);
      expect(cache.replaceCalls, [
        [_riichi, _tanyao],
      ]);
    });

    test('a failing remote with a non-empty cache returns the cached '
        'catalog instead of rethrowing', () async {
      final remote = FakeYakuRepository([], error: Exception('offline'));
      final cache = FakeYakuCacheSource(seed: [_riichi]);
      final repository = CachedYakuRepository(remote, cache);

      final result = await repository.catalog();

      expect(result, [_riichi]);
      expect(cache.replaceCalls, isEmpty);
    });

    test('a failing remote with an empty cache rethrows the same '
        'exception', () async {
      final failure = Exception('offline');
      final remote = FakeYakuRepository([], error: failure);
      final cache = FakeYakuCacheSource();
      final repository = CachedYakuRepository(remote, cache);

      await expectLater(repository.catalog(), throwsA(same(failure)));
    });
  });
}
