// AI-GENERATED by Claude (Claude Code), 2026-09-23
// Why: Test scaffolding is tedious and teaches no Flutter concept; the code under test is author-written.
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:material_ui/material_ui.dart';
import 'package:tenpai/learning/lesson_providers.dart';
import 'package:tenpai/progress/progress_providers.dart';
import 'package:tenpai/shared/models/lesson.dart';
import 'package:tenpai/shared/models/lesson_block.dart';
import 'package:tenpai/shared/models/unit.dart';
import 'package:tenpai/shared/theme/app_theme.dart';
import 'package:tenpai/shared/widgets/tile_state.dart';
import 'package:tenpai/shared/widgets/tile_widget.dart';
import 'package:tenpai/yaku/yaku.dart';
import 'package:tenpai/yaku/yaku_providers.dart';
import 'package:tenpai/yaku/yaku_screen.dart';

import '../fakes/fake_lesson_repository.dart';
import '../fakes/fake_progress_repository.dart';
import '../fakes/fake_yaku_repository.dart';

const _riichi = Yaku(
  id: 'riichi',
  name: 'Riichi',
  kanji: '立直',
  nickname: 'Prête',
  summary: 'Main fermée prête à gagner.',
  description: 'Déclarée quand la main est tenpai et fermée.',
  han: 1,
  tier: YakuTier.essential,
  tiles: ['1m', '2m', '3m'],
);
const _tanyao = Yaku(
  id: 'tanyao',
  name: 'Tanyao',
  kanji: '断幺九',
  nickname: 'Tout simple',
  summary: 'Que des tuiles simples.',
  description: 'Aucun terminal ni honneur.',
  han: 1,
  tier: YakuTier.essential,
  tiles: ['2m', '3m', '4m'],
  unlockUnit: 'unit_01',
);
const _pinfu = Yaku(
  id: 'pinfu',
  name: 'Pinfu',
  kanji: '平和',
  nickname: 'Main plate',
  summary: 'Que des séquences.',
  description: 'Une main entièrement en séquences, sans fu.',
  han: 1,
  tier: YakuTier.common,
  tiles: ['2m', '3m', '4m'],
);
const _chinitsu = Yaku(
  id: 'chinitsu',
  name: 'Chinitsu',
  kanji: '清一色',
  nickname: 'Couleur pure',
  summary: 'Une seule couleur.',
  description: 'Toute la main dans une seule des trois couleurs.',
  han: 5,
  tier: YakuTier.rare,
  tiles: ['1m', '2m', '3m'],
);
const _kazoe = Yaku(
  id: 'kazoe',
  name: 'Kazoe yakuman',
  kanji: '数え役満',
  nickname: 'Compté yakuman',
  summary: 'Un total de han hors norme.',
  description: 'Treize han ou plus par cumul.',
  han: 13,
  tier: YakuTier.rare,
  tiles: ['1m', '2m', '3m'],
  unlockUnit: 'unit_01',
);

const _yakus = [_riichi, _tanyao, _pinfu, _chinitsu, _kazoe];

final _units = [
  Unit(
    id: 'unit_01',
    title: 'unit one',
    lessons: [
      Lesson(
        id: 'l1',
        title: 'one',
        xp: 10,
        blocks: const [LessonBlock.drill()],
      ),
      Lesson(
        id: 'l2',
        title: 'two',
        xp: 10,
        blocks: const [LessonBlock.drill()],
      ),
    ],
  ),
];

Future<FakeYakuRepository> _pumpYakuScreen(
  WidgetTester tester, {
  List<Yaku> yakus = _yakus,
  Exception? error,
}) async {
  final repository = FakeYakuRepository(yakus, error: error);
  // The default test surface is too short to build every card: ListView is
  // lazy, so a card outside the viewport never enters the tree.
  await tester.binding.setSurfaceSize(const Size(800, 2000));
  addTearDown(() => tester.binding.setSurfaceSize(null));
  await tester.pumpWidget(
    ProviderScope(
      overrides: [
        yakuRepositoryProvider.overrideWithValue(repository),
        lessonRepositoryProvider.overrideWithValue(
          FakeLessonRepository(_units),
        ),
        progressRepositoryProvider.overrideWithValue(FakeProgressRepository()),
      ],
      retry: (_, _) => null,
      child: MaterialApp(theme: lightTheme(), home: const YakuScreen()),
    ),
  );
  await tester.pumpAndSettle();
  return repository;
}

void main() {
  group('YakuScreen', () {
    testWidgets('renders one card per yaku', (tester) async {
      await _pumpYakuScreen(tester);

      for (final yaku in _yakus) {
        expect(find.text(yaku.name), findsOneWidget);
      }
    });

    testWidgets('typing in the search field filters the list', (tester) async {
      await _pumpYakuScreen(tester);

      await tester.enterText(find.byType(TextField), 'tan');
      await tester.pumpAndSettle();

      expect(find.text('Tanyao'), findsOneWidget);
      expect(find.text('Riichi'), findsNothing);
      expect(find.text('Pinfu'), findsNothing);
      expect(find.text('Chinitsu'), findsNothing);
      expect(find.text('Kazoe yakuman'), findsNothing);
    });

    testWidgets(
      'tapping the Rares chip shows only rare yakus, Tous restores all',
      (tester) async {
        await _pumpYakuScreen(tester);

        await tester.tap(find.widgetWithText(ChoiceChip, 'Rares'));
        await tester.pumpAndSettle();

        expect(find.text('Chinitsu'), findsOneWidget);
        expect(find.text('Kazoe yakuman'), findsOneWidget);
        expect(find.text('Riichi'), findsNothing);
        expect(find.text('Tanyao'), findsNothing);
        expect(find.text('Pinfu'), findsNothing);

        await tester.tap(find.widgetWithText(ChoiceChip, 'Tous'));
        await tester.pumpAndSettle();

        for (final yaku in _yakus) {
          expect(find.text(yaku.name), findsOneWidget);
        }
      },
    );

    testWidgets('a locked yaku shows a lock icon and face-down tiles', (
      tester,
    ) async {
      await _pumpYakuScreen(tester);

      final card = find.ancestor(
        of: find.text('Tanyao'),
        matching: find.byType(Padding),
      );
      expect(
        find.descendant(of: card.first, matching: find.byIcon(Icons.lock)),
        findsOneWidget,
      );
      final tiles = tester.widgetList<TileWidget>(
        find.descendant(of: card.first, matching: find.byType(TileWidget)),
      );
      expect(tiles, isNotEmpty);
      for (final tile in tiles) {
        expect(tile.state, TileState.faceDown);
      }
    });

    testWidgets('an unlocked yaku shows its han count and normal tiles', (
      tester,
    ) async {
      await _pumpYakuScreen(tester);

      final card = find.ancestor(
        of: find.text('Riichi'),
        matching: find.byType(Padding),
      );
      expect(
        find.descendant(of: card.first, matching: find.text('1 han')),
        findsOneWidget,
      );
      final tiles = tester.widgetList<TileWidget>(
        find.descendant(of: card.first, matching: find.byType(TileWidget)),
      );
      expect(tiles, isNotEmpty);
      for (final tile in tiles) {
        expect(tile.state, TileState.normal);
      }
    });

    testWidgets(
      'a repository error shows the retry view and Réessayer refetches',
      (tester) async {
        final repository = await _pumpYakuScreen(
          tester,
          error: Exception('boom'),
        );

        expect(find.text('Impossible de charger les yakus'), findsOneWidget);
        expect(find.widgetWithText(TextButton, 'Réessayer'), findsOneWidget);
        expect(repository.callCount, 1);

        repository.error = null;
        await tester.tap(find.widgetWithText(TextButton, 'Réessayer'));
        await tester.pumpAndSettle();

        expect(repository.callCount, 2);
        expect(find.text('Riichi'), findsOneWidget);
      },
    );

    testWidgets(
      'with the default retry active, the error still shows immediately and '
      'Réessayer cancels the pending retry and refetches',
      (tester) async {
        final repository = FakeYakuRepository(_yakus, error: Exception('boom'));
        await tester.binding.setSurfaceSize(const Size(800, 2000));
        addTearDown(() => tester.binding.setSurfaceSize(null));
        await tester.pumpWidget(
          ProviderScope(
            overrides: [
              yakuRepositoryProvider.overrideWithValue(repository),
              lessonRepositoryProvider.overrideWithValue(
                FakeLessonRepository(_units),
              ),
              progressRepositoryProvider.overrideWithValue(
                FakeProgressRepository(),
              ),
            ],
            // No `retry:` override: this is the point of the test. Do not
            // `pumpAndSettle` before the retry timer is cancelled below, it
            // would wait out the (minutes-long) default retry delay.
            child: MaterialApp(theme: lightTheme(), home: const YakuScreen()),
          ),
        );
        await tester.pump(Duration.zero);

        expect(find.text('Impossible de charger les yakus'), findsOneWidget);
        expect(find.widgetWithText(TextButton, 'Réessayer'), findsOneWidget);

        repository.error = null;
        await tester.tap(find.widgetWithText(TextButton, 'Réessayer'));
        await tester.pumpAndSettle();

        expect(find.text('Riichi'), findsOneWidget);
      },
    );

    testWidgets(
      'unlocking a yaku through progress updates its card without a widget rebuild',
      (tester) async {
        await _pumpYakuScreen(tester);

        final lockedCard = find.ancestor(
          of: find.text('Tanyao'),
          matching: find.byType(Padding),
        );
        expect(
          find.descendant(
            of: lockedCard.first,
            matching: find.byIcon(Icons.lock),
          ),
          findsOneWidget,
        );

        final progress = tester.container().read(userProgressProvider.notifier);
        for (final lesson in _units.first.lessons) {
          await progress.completeLesson(lesson);
        }
        await tester.pumpAndSettle();

        final unlockedCard = find.ancestor(
          of: find.text('Tanyao'),
          matching: find.byType(Padding),
        );
        expect(
          find.descendant(
            of: unlockedCard.first,
            matching: find.byIcon(Icons.lock),
          ),
          findsNothing,
        );
        expect(
          find.descendant(of: unlockedCard.first, matching: find.text('1 han')),
          findsOneWidget,
        );
        final tiles = tester.widgetList<TileWidget>(
          find.descendant(
            of: unlockedCard.first,
            matching: find.byType(TileWidget),
          ),
        );
        expect(tiles, isNotEmpty);
        for (final tile in tiles) {
          expect(tile.state, TileState.normal);
        }
      },
    );
  });
}
