// AI-GENERATED by Claude (Claude Code), 2026-09-23
// Why: Test scaffolding is tedious and teaches no Flutter concept; the code under test is author-written.
import 'package:flutter_test/flutter_test.dart';
import 'package:tenpai/yaku/yaku.dart';

Map<String, Object?> _json({
  int? hanOpen,
  String? unlockUnit,
  String tier = 'common',
}) => {
  'id': 'riichi',
  'name': 'Riichi',
  'kanji': '立直',
  'nickname': 'Prête',
  'summary': 'Main fermée prête à gagner.',
  'description': 'Déclarée quand la main est tenpai et fermée.',
  'han': 1,
  'hanOpen': hanOpen,
  'tier': tier,
  'tiles': ['1m', '2m', '3m'],
  'unlockUnit': unlockUnit,
};

void main() {
  group('Yaku.fromJson', () {
    test('round-trips a full entry with a non-null hanOpen and unlockUnit', () {
      final yaku = Yaku.fromJson(_json(hanOpen: 2, unlockUnit: 'unit_01'));

      expect(yaku.id, 'riichi');
      expect(yaku.name, 'Riichi');
      expect(yaku.kanji, '立直');
      expect(yaku.nickname, 'Prête');
      expect(yaku.summary, 'Main fermée prête à gagner.');
      expect(yaku.description, 'Déclarée quand la main est tenpai et fermée.');
      expect(yaku.han, 1);
      expect(yaku.hanOpen, 2);
      expect(yaku.tier, YakuTier.common);
      expect(yaku.tiles, ['1m', '2m', '3m']);
      expect(yaku.unlockUnit, 'unit_01');
    });

    test(
      'hanOpen and unlockUnit are both null when the JSON has them null',
      () {
        final yaku = Yaku.fromJson(_json());

        expect(yaku.hanOpen, isNull);
        expect(yaku.unlockUnit, isNull);
      },
    );

    test('maps every tier string to its enum value', () {
      expect(Yaku.fromJson(_json(tier: 'essential')).tier, YakuTier.essential);
      expect(Yaku.fromJson(_json()).tier, YakuTier.common);
      expect(Yaku.fromJson(_json(tier: 'rare')).tier, YakuTier.rare);
    });

    test('an unknown tier throws ArgumentError', () {
      expect(
        () => Yaku.fromJson(_json(tier: 'legendary')),
        throwsArgumentError,
      );
    });
  });
}
