// AI-GENERATED by Claude (Claude Code), 2026-09-23
// Why: Test scaffolding is tedious and teaches no Flutter concept; the code under test is author-written.
import 'dart:convert';

import 'package:dio/dio.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:tenpai/yaku/yaku_remote_source.dart';
import 'package:tenpai/yaku/yaku_repository_impl.dart';

import '../fakes/fake_http_client_adapter.dart';

Map<String, Object?> _entry(String id) => {
  'id': id,
  'name': id,
  'kanji': '役',
  'nickname': id,
  'summary': 'résumé',
  'description': 'description',
  'han': 1,
  'hanOpen': null,
  'tier': 'common',
  'tiles': ['1m', '2m', '3m'],
  'unlockUnit': null,
};

String _catalogBody(int count) => jsonEncode({
  'yakus': [for (var i = 0; i < count; i++) _entry('yaku_$i')],
});

Dio _dio(FakeHttpClientAdapter adapter) =>
    Dio(BaseOptions(baseUrl: 'https://example.test/'))
      ..httpClientAdapter = adapter;

void main() {
  group('YakuRepositoryImpl.catalog', () {
    test('returns every yaku from the requested path', () async {
      final adapter = FakeHttpClientAdapter([(200, _catalogBody(3))]);
      final repository = YakuRepositoryImpl(YakuRemoteSource(_dio(adapter)));

      final yakus = await repository.catalog();

      expect(yakus, hasLength(3));
      expect(yakus.map((y) => y.id), ['yaku_0', 'yaku_1', 'yaku_2']);
      expect(adapter.requestedPaths, [
        'https://example.test/yaku/v1/catalog.json',
      ]);
    });

    test(
      'a second call returns the same list without a second request',
      () async {
        final adapter = FakeHttpClientAdapter([(200, _catalogBody(2))]);
        final repository = YakuRepositoryImpl(YakuRemoteSource(_dio(adapter)));

        final first = await repository.catalog();
        final second = await repository.catalog();

        expect(second, same(first));
        expect(adapter.requestedPaths, hasLength(1));
      },
    );

    test('a failure is not cached, so the next call retries', () async {
      final adapter = FakeHttpClientAdapter([
        (500, '{"error": "server error"}'),
        (200, _catalogBody(1)),
      ]);
      final repository = YakuRepositoryImpl(YakuRemoteSource(_dio(adapter)));

      await expectLater(
        repository.catalog(),
        throwsA(
          isA<DioException>().having(
            (e) => e.type,
            'type',
            DioExceptionType.badResponse,
          ),
        ),
      );
      final yakus = await repository.catalog();

      expect(yakus, hasLength(1));
      expect(adapter.requestedPaths, hasLength(2));
    });

    test('a wrong-shape body (missing `yakus`) is not cached, so the next call retries', () async {
      final adapter = FakeHttpClientAdapter([
        (200, jsonEncode(<String, Object?>{})),
        (200, _catalogBody(1)),
      ]);
      final repository = YakuRepositoryImpl(YakuRemoteSource(_dio(adapter)));

      await expectLater(repository.catalog(), throwsA(isA<TypeError>()));
      final yakus = await repository.catalog();

      expect(yakus, hasLength(1));
      expect(adapter.requestedPaths, hasLength(2));
    });
  });
}
