// AI-GENERATED by Claude (Claude Code), 2026-09-23
// Why: Test scaffolding is tedious and teaches no Flutter concept; the code under test is author-written.
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:tenpai/learning/lesson_providers.dart';
import 'package:tenpai/progress/progress_providers.dart';
import 'package:tenpai/progress/user_progress.dart';
import 'package:tenpai/shared/models/lesson.dart';
import 'package:tenpai/shared/models/lesson_block.dart';
import 'package:tenpai/shared/models/unit.dart';
import 'package:tenpai/yaku/yaku.dart';
import 'package:tenpai/yaku/yaku_providers.dart';

import '../fakes/fake_lesson_repository.dart';
import '../fakes/fake_progress_repository.dart';
import '../fakes/fake_yaku_repository.dart';

const _riichi = Yaku(
  id: 'riichi',
  name: 'Riichi',
  kanji: '立直',
  nickname: 'Prête',
  summary: 'Main fermée prête à gagner.',
  description: 'Déclarée quand la main est tenpai et fermée.',
  han: 1,
  tier: YakuTier.essential,
  tiles: ['1m', '2m', '3m'],
);
const _tanyao = Yaku(
  id: 'tanyao',
  name: 'Tanyao',
  kanji: '断幺九',
  nickname: 'Tout simple',
  summary: 'Que des tuiles simples.',
  description: 'Aucun terminal ni honneur.',
  han: 1,
  tier: YakuTier.essential,
  tiles: ['2m', '3m', '4m'],
  unlockUnit: 'unit_01',
);
const _pinfu = Yaku(
  id: 'pinfu',
  name: 'Pinfu',
  kanji: '平和',
  nickname: 'Main plate',
  summary: 'Que des séquences.',
  description: 'Une main entièrement en séquences, sans fu.',
  han: 1,
  tier: YakuTier.common,
  tiles: ['2m', '3m', '4m'],
  unlockUnit: 'unit_01',
);
const _chinitsu = Yaku(
  id: 'chinitsu',
  name: 'Chinitsu',
  kanji: '清一色',
  nickname: 'Couleur pure',
  summary: 'Une seule couleur.',
  description: 'Toute la main dans une seule des trois couleurs.',
  han: 5,
  tier: YakuTier.rare,
  tiles: ['1m', '2m', '3m'],
);
const _kazoe = Yaku(
  id: 'kazoe',
  name: 'Kazoe yakuman',
  kanji: '数え役満',
  nickname: 'Compté yakuman',
  summary: 'Un total de han hors norme.',
  description: 'Treize han ou plus par cumul.',
  han: 13,
  tier: YakuTier.rare,
  tiles: ['1m', '2m', '3m'],
  unlockUnit: 'unit_99',
);

final _yakus = [_riichi, _tanyao, _pinfu, _chinitsu, _kazoe];

final _lesson1 = Lesson(
  id: 'l1',
  title: 'one',
  xp: 10,
  blocks: const [LessonBlock.drill()],
);
final _lesson2 = Lesson(
  id: 'l2',
  title: 'two',
  xp: 10,
  blocks: const [LessonBlock.drill()],
);
final _units = [
  Unit(id: 'unit_01', title: 'unit one', lessons: [_lesson1, _lesson2]),
];

const _freshProgress = UserProgress(completedLessonIds: {}, xp: 0);
const _unit01CompletedProgress = UserProgress(
  completedLessonIds: {'l1', 'l2'},
  xp: 20,
);

void main() {
  ProviderContainer makeContainer({
    required FakeYakuRepository yakuRepository,
    UserProgress progress = _freshProgress,
    bool disableRetry = true,
  }) => ProviderContainer.test(
    overrides: [
      yakuRepositoryProvider.overrideWithValue(yakuRepository),
      lessonRepositoryProvider.overrideWithValue(FakeLessonRepository(_units)),
      progressRepositoryProvider.overrideWithValue(
        FakeProgressRepository(progress),
      ),
    ],
    retry: disableRetry ? (_, _) => null : null,
  );

  Future<List<YakuCard>> cards(ProviderContainer container) async {
    await container.read(yakuCatalogProvider.future);
    await container.read(unitsProvider.future);
    await container.read(userProgressProvider.future);
    return container.read(yakuCardsProvider).value!;
  }

  group('yakuCardsProvider filtering', () {
    late ProviderContainer container;

    setUp(() {
      container = makeContainer(
        yakuRepository: FakeYakuRepository(_yakus),
        progress: _unit01CompletedProgress,
      );
    });

    test('with no filter, every yaku is returned', () async {
      final rows = await cards(container);

      expect(rows.map((r) => r.yaku.id), _yakus.map((y) => y.id));
    });

    test('query matches the name', () async {
      container.read(yakuQueryProvider.notifier).query = 'Riichi';

      final rows = await cards(container);

      expect(rows.map((r) => r.yaku.id), ['riichi']);
    });

    test('query matches the nickname, case- and accent-insensitive', () async {
      container.read(yakuQueryProvider.notifier).query = 'PRETE';

      final rows = await cards(container);

      expect(rows.map((r) => r.yaku.id), ['riichi']);
    });

    test(
      'query matches the nickname with surrounding spaces and its own accent',
      () async {
        container.read(yakuQueryProvider.notifier).query = '  prête ';

        final rows = await cards(container);

        expect(rows.map((r) => r.yaku.id), ['riichi']);
      },
    );

    test('query matches the kanji', () async {
      container.read(yakuQueryProvider.notifier).query = '平和';

      final rows = await cards(container);

      expect(rows.map((r) => r.yaku.id), ['pinfu']);
    });

    test('tier filter keeps only that tier', () async {
      container.read(yakuTierFilterProvider.notifier).tier = YakuTier.rare;

      final rows = await cards(container);

      expect(rows.map((r) => r.yaku.id), ['chinitsu', 'kazoe']);
    });

    test('query and tier filter combine', () async {
      container.read(yakuTierFilterProvider.notifier).tier = YakuTier.rare;
      container.read(yakuQueryProvider.notifier).query = 'kazoe';

      final rows = await cards(container);

      expect(rows.map((r) => r.yaku.id), ['kazoe']);
    });
  });

  group('yakuCardsProvider unlocked flag', () {
    test(
      'a null unlockUnit is always unlocked, even on fresh progress',
      () async {
        final container = makeContainer(
          yakuRepository: FakeYakuRepository(_yakus),
        );

        final rows = await cards(container);

        final riichi = rows.firstWhere((r) => r.yaku.id == 'riichi');
        final chinitsu = rows.firstWhere((r) => r.yaku.id == 'chinitsu');
        expect(riichi.unlocked, isTrue);
        expect(chinitsu.unlocked, isTrue);
      },
    );

    test('an unlockUnit is locked on fresh progress', () async {
      final container = makeContainer(
        yakuRepository: FakeYakuRepository(_yakus),
      );

      final rows = await cards(container);

      final tanyao = rows.firstWhere((r) => r.yaku.id == 'tanyao');
      final pinfu = rows.firstWhere((r) => r.yaku.id == 'pinfu');
      expect(tanyao.unlocked, isFalse);
      expect(pinfu.unlocked, isFalse);
    });

    test(
      'an unlockUnit is unlocked once both its lessons are completed',
      () async {
        final container = makeContainer(
          yakuRepository: FakeYakuRepository(_yakus),
          progress: _unit01CompletedProgress,
        );

        final rows = await cards(container);

        final tanyao = rows.firstWhere((r) => r.yaku.id == 'tanyao');
        final pinfu = rows.firstWhere((r) => r.yaku.id == 'pinfu');
        expect(tanyao.unlocked, isTrue);
        expect(pinfu.unlocked, isTrue);
      },
    );

    test('an unknown unlockUnit stays locked even after progress', () async {
      final container = makeContainer(
        yakuRepository: FakeYakuRepository(_yakus),
        progress: _unit01CompletedProgress,
      );

      final rows = await cards(container);

      final kazoe = rows.firstWhere((r) => r.yaku.id == 'kazoe');
      expect(kazoe.unlocked, isFalse);
    });
  });

  group('yakuCardsProvider on repository error', () {
    test('with retry disabled, it is a plain AsyncError', () async {
      final container = makeContainer(
        yakuRepository: FakeYakuRepository(_yakus, error: Exception('boom')),
      );

      await expectLater(
        container.read(yakuCatalogProvider.future),
        throwsA(isA<Exception>()),
      );

      expect(
        container.read(yakuCardsProvider),
        isA<AsyncError<List<YakuCard>>>(),
      );
    });

    test('with the default retry, it still reads as AsyncError while the '
        'catalog provider is loading-with-error underneath', () async {
      final container = makeContainer(
        yakuRepository: FakeYakuRepository(_yakus, error: Exception('boom')),
        disableRetry: false,
      );

      // Start the build without awaiting `.future`: with a retry pending,
      // `.future` stays deliberately unresolved until retries are
      // exhausted (minutes away), so only a microtask flush is awaited
      // here for the first attempt to fail and set the retrying state.
      container.read(yakuCatalogProvider);
      await Future<void>.delayed(Duration.zero);

      final catalogState = container.read(yakuCatalogProvider);
      expect(catalogState.hasError, isTrue);
      expect(catalogState.isLoading, isTrue);

      expect(
        container.read(yakuCardsProvider),
        isA<AsyncError<List<YakuCard>>>(),
      );

      // No manual dispose: `ProviderContainer.test` already registers
      // `addTearDown(container.dispose)`, which cancels the pending retry
      // timer before the next test runs.
    });
  });
}
