// AI-GENERATED by Claude (Claude Code), 2026-09-25
// Why: Test scaffolding is tedious and teaches no Flutter concept; the code under test is author-written.
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:material_ui/material_ui.dart';
import 'package:tenpai/settings/settings_providers.dart';
import 'package:tenpai/settings/settings_screen.dart';
import 'package:tenpai/shared/theme/app_theme.dart';

import '../fakes/fake_settings_repository.dart';

Future<FakeSettingsRepository> _pumpSettings(
  WidgetTester tester, {
  ThemeMode initial = ThemeMode.system,
}) async {
  final repository = FakeSettingsRepository(initial: initial);
  await tester.pumpWidget(
    ProviderScope(
      overrides: [settingsRepositoryProvider.overrideWithValue(repository)],
      retry: (_, _) => null,
      child: MaterialApp(theme: lightTheme(), home: const SettingsScreen()),
    ),
  );
  await tester.pumpAndSettle();
  return repository;
}

/// The segment whose selected state a test wants to read; `SegmentedButton`
/// draws no distinct selected widget, so the underlying value is the only
/// reliable seam.
bool _isSelected(WidgetTester tester, ThemeMode mode) => tester
    .widget<SegmentedButton<ThemeMode>>(find.byType(SegmentedButton<ThemeMode>))
    .selected
    .contains(mode);

void main() {
  group('SettingsScreen', () {
    testWidgets('Système is selected on a fresh install', (tester) async {
      await _pumpSettings(tester);

      expect(_isSelected(tester, ThemeMode.system), isTrue);
    });

    testWidgets('tapping Sombre records the choice and selects it', (
      tester,
    ) async {
      final repository = await _pumpSettings(tester);

      await tester.tap(find.text('Sombre'));
      await tester.pumpAndSettle();

      expect(repository.setThemeModeCalls, [ThemeMode.dark]);
      expect(_isSelected(tester, ThemeMode.dark), isTrue);
    });
  });
}
