// AI-GENERATED by Claude (Claude Code), 2026-09-25
// Why: Test scaffolding is tedious and teaches no Flutter concept; the code under test is author-written.
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:material_ui/material_ui.dart';
import 'package:tenpai/settings/settings_providers.dart';

import '../fakes/fake_settings_repository.dart';

ProviderContainer _makeContainer(FakeSettingsRepository repository) =>
    ProviderContainer.test(
      overrides: [settingsRepositoryProvider.overrideWithValue(repository)],
      retry: (_, _) => null,
    );

void main() {
  group('themeModeProvider', () {
    test('resolves to system on a fresh install', () async {
      final container = _makeContainer(FakeSettingsRepository());

      final mode = await container.read(themeModeProvider.future);

      expect(mode, ThemeMode.system);
    });

    test('resolves to whatever the repository already holds', () async {
      final container = _makeContainer(
        FakeSettingsRepository(initial: ThemeMode.dark),
      );

      final mode = await container.read(themeModeProvider.future);

      expect(mode, ThemeMode.dark);
    });

    test('set writes to the repository once and updates state', () async {
      final repository = FakeSettingsRepository();
      final container = _makeContainer(repository);
      await container.read(themeModeProvider.future);

      await container.read(themeModeProvider.notifier).set(ThemeMode.dark);

      expect(repository.setThemeModeCalls, [ThemeMode.dark]);
      expect(container.read(themeModeProvider), const AsyncData(ThemeMode.dark));
    });

    test('a failing write does not update state', () async {
      final repository = FakeSettingsRepository()
        ..error = Exception('disk full');
      final container = _makeContainer(repository);
      await container.read(themeModeProvider.future);

      await expectLater(
        container.read(themeModeProvider.notifier).set(ThemeMode.dark),
        throwsA(isA<Exception>()),
      );

      expect(
        container.read(themeModeProvider),
        const AsyncData(ThemeMode.system),
      );
    });
  });
}
