// AI-GENERATED by Claude (Claude Code), 2026-09-23
// Why: Test scaffolding is tedious and teaches no Flutter concept; the code under test is author-written.
import 'package:flutter_test/flutter_test.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:tenpai/shared/models/lesson_block.dart';

void main() {
  group('LessonBlock JSON round-trip', () {
    test('explanation block survives fromJson(toJson())', () {
      const block = LessonBlock.explanation(
        tile: '5p',
        title: 'Les pin',
        body: 'Une famille de tuiles numérotées.',
      );

      final roundTripped = LessonBlock.fromJson(block.toJson());

      expect(roundTripped, block);
    });

    test('quiz block survives fromJson(toJson())', () {
      final block = LessonBlock.quiz(
        question: 'Quelle tuile complète la main ?',
        hand: ['1m', '2m', '3m'],
        options: ['6s', '9p', '5s', '1z'],
        correctIndex: 2,
        feedback: 'Bien vu.',
      );

      final roundTripped = LessonBlock.fromJson(block.toJson());

      expect(roundTripped, block);
    });

    test('drill block survives fromJson(toJson())', () {
      final block = LessonBlock.drill(
        prompt: 'Touchez les cercles',
        hand: const [
          '1m',
          '2m',
          '3m',
          '1p',
          '2p',
          '3p',
          '1s',
          '2s',
          '3s',
          '1z',
          '2z',
          '3z',
          '4z',
        ],
        answers: const [3, 4, 5],
        feedback: 'Les cercles se lisent au nombre de points.',
      );

      final roundTripped = LessonBlock.fromJson(block.toJson());

      expect(roundTripped, block);
    });

    test('interactive block survives fromJson(toJson())', () {
      final block = LessonBlock.interactive(
        prompt: 'Complétez la suite',
        group: const ['4p', '5p'],
        slot: 2,
        rack: const ['3s', '6p', '6m', '5p'],
        correctIndex: 1,
        feedback: '4-5-6 dans la même famille : une suite.',
      );

      final roundTripped = LessonBlock.fromJson(block.toJson());

      expect(roundTripped, block);
    });

    test('toJson uses "type" as the union key', () {
      const block = LessonBlock.explanation(tile: '1m', title: 't', body: 'b');

      final json = block.toJson();

      expect(json['type'], 'explanation');
    });

    test('an unknown type throws CheckedFromJsonException', () {
      final json = {'type': 'unknown', 'tile': '1m'};

      expect(
        () => LessonBlock.fromJson(json),
        throwsA(isA<CheckedFromJsonException>()),
      );
    });
  });
}
