// AI-GENERATED by Claude (Claude Code), 2026-09-23
// Why: Test scaffolding is tedious and teaches no Flutter concept; the code under test is author-written.
import 'package:flutter_test/flutter_test.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:tenpai/shared/models/lesson_block.dart';

void main() {
  group('LessonBlock JSON round-trip', () {
    test('explanation block survives fromJson(toJson())', () {
      const block = LessonBlock.explanation(
        tile: '5p',
        title: 'Les pin',
        body: 'Une famille de tuiles numérotées.',
      );

      final roundTripped = LessonBlock.fromJson(block.toJson());

      expect(roundTripped, block);
    });

    test('quiz block survives fromJson(toJson())', () {
      const block = LessonBlock.quiz(
        question: 'Quelle tuile complète la main ?',
        hand: ['1m', '2m', '3m'],
        options: ['6s', '9p', '5s', '1z'],
        correctIndex: 2,
        feedback: 'Bien vu.',
      );

      final roundTripped = LessonBlock.fromJson(block.toJson());

      expect(roundTripped, block);
    });

    test('drill block survives fromJson(toJson())', () {
      const block = LessonBlock.drill();

      final roundTripped = LessonBlock.fromJson(block.toJson());

      expect(roundTripped, block);
    });

    test('interactive block survives fromJson(toJson())', () {
      const block = LessonBlock.interactive();

      final roundTripped = LessonBlock.fromJson(block.toJson());

      expect(roundTripped, block);
    });

    test('toJson uses "type" as the union key', () {
      const block = LessonBlock.explanation(tile: '1m', title: 't', body: 'b');

      final json = block.toJson();

      expect(json['type'], 'explanation');
    });

    test('an unknown type throws CheckedFromJsonException', () {
      final json = {'type': 'unknown', 'tile': '1m'};

      expect(
        () => LessonBlock.fromJson(json),
        throwsA(isA<CheckedFromJsonException>()),
      );
    });
  });
}
