// AI-GENERATED by Claude (Claude Code), 2026-09-18
// Why: Test scaffolding is tedious and teaches no Flutter concept; the widget under test is author-written.
import 'package:flutter_test/flutter_test.dart';
import 'package:tenpai/shared/models/tile.dart';

void main() {
  group('Tile.parse', () {
    test('round-trips a man tile', () {
      final tile = Tile.parse('1m');

      expect(tile.suit, TileSuit.man);
      expect(tile.number, 1);
      expect(tile.isRed, isFalse);
      expect(tile.code, '1m');
    });

    test('round-trips a pin tile', () {
      final tile = Tile.parse('7p');

      expect(tile.suit, TileSuit.pin);
      expect(tile.number, 7);
      expect(tile.isRed, isFalse);
      expect(tile.code, '7p');
    });

    test('round-trips a sou tile', () {
      final tile = Tile.parse('9s');

      expect(tile.suit, TileSuit.sou);
      expect(tile.number, 9);
      expect(tile.isRed, isFalse);
      expect(tile.code, '9s');
    });

    test('round-trips an honor tile', () {
      final tile = Tile.parse('3z');

      expect(tile.suit, TileSuit.honor);
      expect(tile.number, 3);
      expect(tile.isRed, isFalse);
      expect(tile.code, '3z');
    });

    test('round-trips a red five of pin', () {
      final tile = Tile.parse('5pr');

      expect(tile.suit, TileSuit.pin);
      expect(tile.number, 5);
      expect(tile.isRed, isTrue);
      expect(tile.code, '5pr');
    });
  });

  group('Tile equality', () {
    test(
      'two tiles built from the same fields are equal and hash the same',
      () {
        const a = Tile(suit: TileSuit.man, number: 4, isRed: true);
        const b = Tile(suit: TileSuit.man, number: 4, isRed: true);

        expect(a, b);
        expect(a.hashCode, b.hashCode);
      },
    );

    test('tiles differing only by isRed are not equal', () {
      const a = Tile(suit: TileSuit.pin, number: 5);
      const b = Tile(suit: TileSuit.pin, number: 5, isRed: true);

      expect(a, isNot(b));
    });
  });

  group('Tile.copyWith', () {
    test('replaces only the given field', () {
      const original = Tile(suit: TileSuit.sou, number: 2);

      final copy = original.copyWith(isRed: true);

      expect(copy.suit, TileSuit.sou);
      expect(copy.number, 2);
      expect(copy.isRed, isTrue);
    });
  });

  group('Tile number assertion', () {
    test('throws for number 0', () {
      expect(
        () => Tile(suit: TileSuit.man, number: 0),
        throwsA(isA<AssertionError>()),
      );
    });

    test('throws for number 10', () {
      expect(
        () => Tile(suit: TileSuit.pin, number: 10),
        throwsA(isA<AssertionError>()),
      );
    });

    test('throws for honor number 8', () {
      expect(
        () => Tile(suit: TileSuit.honor, number: 8),
        throwsA(isA<AssertionError>()),
      );
    });
  });
}
