// AI-GENERATED by Claude (Claude Code), 2026-09-23
// Why: Test scaffolding is tedious and teaches no Flutter concept; the code under test is author-written.
import 'package:flutter_test/flutter_test.dart';
import 'package:tenpai/sensei/sensei_request.dart';
import 'package:tenpai/shared/models/tile.dart';

SenseiRequest _quizMiss({int chosenIndex = 0}) => SenseiRequest.quizMiss(
  question: 'Quelle tuile complète la main ?',
  hand: const ['1m', '2m', '3m'],
  options: const ['4m', '5m', '6m', '7m'],
  chosenIndex: chosenIndex,
);

SenseiRequest _drillMiss({List<int> picked = const [0, 12]}) =>
    SenseiRequest.drillMiss(
      prompt: 'Trouvez la suite 2-3-4 de pinzu.',
      hand: const ['1m', '2m', '3m', '4p'],
      picked: picked,
      answers: const [9, 10, 11],
    );

void main() {
  group('SenseiRequest.quizMiss', () {
    test(
      'two requests built from the same fields are equal and share a hashCode',
      () {
        final a = _quizMiss();
        final b = _quizMiss();

        expect(a, b);
        expect(a.hashCode, b.hashCode);
      },
    );

    test('a different chosenIndex makes the requests unequal', () {
      final a = _quizMiss();
      final b = _quizMiss(chosenIndex: 2);

      expect(a, isNot(b));
    });
  });

  group('SenseiRequest.tileContext', () {
    test('two requests for the same tile are equal and share a hashCode', () {
      final a = SenseiRequest.tileContext(Tile.parse('5pr'));
      final b = SenseiRequest.tileContext(Tile.parse('5pr'));

      expect(a, b);
      expect(a.hashCode, b.hashCode);
    });

    test('requests for different tiles are unequal', () {
      final a = SenseiRequest.tileContext(Tile.parse('1m'));
      final b = SenseiRequest.tileContext(Tile.parse('2m'));

      expect(a, isNot(b));
    });
  });

  group('SenseiRequest.drillMiss', () {
    test(
      'two requests built from equal lists are equal and share a hashCode',
      () {
        final a = _drillMiss();
        final b = _drillMiss();

        expect(a, b);
        expect(a.hashCode, b.hashCode);
      },
    );

    test('a different picked list makes the requests unequal', () {
      final a = _drillMiss();
      final b = _drillMiss(picked: [0, 1]);

      expect(a, isNot(b));
    });
  });
}
