// AI-GENERATED by Claude (Claude Code), 2026-09-23
// Why: Test scaffolding is tedious and teaches no Flutter concept; the code under test is author-written.
import 'dart:io';

import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:tenpai/sensei/sensei_providers.dart';
import 'package:tenpai/sensei/sensei_request.dart';
import 'package:tenpai/sensei/sensei_state.dart';
import 'package:tenpai/shared/models/tile.dart';

import '../fakes/fake_sensei_repository.dart';

final _request = SenseiRequest.tileContext(Tile.parse('5z'));

/// Lets a chunk queued on the fake's [StreamController] reach the notifier:
/// the controller notifies its listener on a microtask, this future resolves
/// on the next real event-loop turn, by which point that microtask has run.
Future<void> _flush() => Future<void>.delayed(Duration.zero);

void main() {
  late ScriptedSenseiRepository fake;
  late ProviderContainer container;

  setUp(() {
    fake = ScriptedSenseiRepository();
    container = ProviderContainer.test(
      overrides: [senseiRepositoryProvider.overrideWithValue(fake)],
      retry: (_, _) => null,
    );
  });

  SenseiState state() => container.read(senseiProvider(_request));
  SenseiNotifier notifier() =>
      container.read(senseiProvider(_request).notifier);

  /// Keeps the auto-disposed family member alive for the body of one test;
  /// without a listener the member could be disposed between the `await`s
  /// a scripted stream needs.
  ProviderSubscription<SenseiState> keepAlive() {
    final sub = container.listen(senseiProvider(_request), (_, _) {});
    addTearDown(sub.close);
    return sub;
  }

  group('SenseiNotifier', () {
    test('starts idle', () {
      keepAlive();

      expect(state(), const SenseiState.idle());
    });

    test('ask moves to loading and calls the repository once', () {
      keepAlive();

      notifier().ask();

      expect(state(), const SenseiState.loading());
      expect(fake.callCount, 1);
      expect(fake.requests, [_request]);
    });

    test('a chunk moves to streaming carrying it', () async {
      keepAlive();
      notifier().ask();

      fake.emit('Un');
      await _flush();

      expect(state(), const SenseiState.streaming('Un'));
    });

    test('a second chunk appends to the first', () async {
      keepAlive();
      notifier().ask();
      fake.emit('Un ');
      await _flush();

      fake.emit('dragon.');
      await _flush();

      expect(state(), const SenseiState.streaming('Un dragon.'));
    });

    test(
      'closing the stream moves to done with the accumulated text',
      () async {
        keepAlive();
        notifier().ask();
        fake.emit('Un ');
        await _flush();
        fake.emit('dragon.');
        await _flush();

        fake.close();
        await _flush();

        expect(state(), const SenseiState.done('Un dragon.'));
      },
    );

    test('closing with no chunk at all is a failure', () async {
      keepAlive();
      notifier().ask();

      fake.close();
      await _flush();

      expect(state(), const SenseiState.failed());
    });

    test('a SocketException goes offline', () async {
      keepAlive();
      notifier().ask();

      fake.fail(const SocketException('no network'));
      await _flush();

      expect(state(), const SenseiState.offline());
    });

    test('any other error fails', () async {
      keepAlive();
      notifier().ask();

      fake.fail(StateError('boom'));
      await _flush();

      expect(state(), const SenseiState.failed());
    });

    test('a second ask while loading is ignored', () {
      keepAlive();
      notifier().ask();

      notifier().ask();

      expect(fake.callCount, 1);
    });

    test('a second ask while streaming is ignored', () async {
      keepAlive();
      notifier().ask();
      fake.emit('Un');
      await _flush();

      notifier().ask();

      expect(fake.callCount, 1);
    });

    test('ask after a failure starts a new call', () async {
      keepAlive();
      notifier().ask();
      fake.close();
      await _flush();
      expect(state(), const SenseiState.failed());

      notifier().ask();

      expect(fake.callCount, 2);
      expect(state(), const SenseiState.loading());
    });

    test('leaving the panel cancels the running subscription', () async {
      final sub = keepAlive();
      notifier().ask();
      await _flush();

      sub.close();
      await _flush();

      expect(fake.cancelled, [true]);
    });
  });
}
