// AI-GENERATED by Claude (Claude Code), 2026-09-23
// Why: Test scaffolding is tedious and teaches no Flutter concept; the code under test is author-written.
import 'dart:io';

import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:material_ui/material_ui.dart';
import 'package:tenpai/sensei/sensei_panel_widget.dart';
import 'package:tenpai/sensei/sensei_providers.dart';
import 'package:tenpai/sensei/sensei_request.dart';
import 'package:tenpai/shared/models/tile.dart';
import 'package:tenpai/shared/theme/app_theme.dart';

import '../fakes/fake_sensei_repository.dart';

final _tileRequest = SenseiRequest.tileContext(Tile.parse('5z'));
const _quizRequest = SenseiRequest.quizMiss(
  question: 'Quelle tuile complète la main ?',
  hand: ['1m', '2m', '3m'],
  options: ['4m', '5m', '6m', '7m'],
  chosenIndex: 0,
  correctIndex: 1,
  feedback: 'Regardez la suite logique.',
);

Future<void> _pumpPanel(
  WidgetTester tester, {
  required SenseiRequest request,
  required bool autoStart,
  required ScriptedSenseiRepository fake,
}) async {
  await tester.pumpWidget(
    ProviderScope(
      overrides: [senseiRepositoryProvider.overrideWithValue(fake)],
      retry: (_, _) => null,
      child: MaterialApp(
        theme: lightTheme(),
        home: Scaffold(
          body: SenseiPanelWidget(request: request, autoStart: autoStart),
        ),
      ),
    ),
  );
  // Flushes the `addPostFrameCallback` an `autoStart: true` panel schedules
  // in `initState`, and reflects any resulting state change.
  await tester.pump();
}

void main() {
  group('SenseiPanelWidget', () {
    testWidgets('autoStart asks once and shows the tile-context loading label', (
      tester,
    ) async {
      final fake = ScriptedSenseiRepository();

      await _pumpPanel(
        tester,
        request: _tileRequest,
        autoStart: true,
        fake: fake,
      );

      expect(fake.callCount, 1);
      expect(fake.requests, [_tileRequest]);
      expect(find.text('Le sensei regarde la tuile'), findsOneWidget);
    });

    testWidgets('autoStart shows the quiz-miss loading label', (tester) async {
      final fake = ScriptedSenseiRepository();

      await _pumpPanel(
        tester,
        request: _quizRequest,
        autoStart: true,
        fake: fake,
      );

      expect(find.text('Le sensei regarde votre main'), findsOneWidget);
    });

    testWidgets('a streamed chunk becomes visible', (tester) async {
      final fake = ScriptedSenseiRepository();
      await _pumpPanel(
        tester,
        request: _tileRequest,
        autoStart: true,
        fake: fake,
      );

      fake.emit('Un dragon blanc porte chance.');
      await tester.pump(const Duration(milliseconds: 100));

      expect(find.textContaining('Un dragon blanc porte chance.'), findsOneWidget);
    });

    testWidgets('the closed stream leaves its full text visible', (
      tester,
    ) async {
      final fake = ScriptedSenseiRepository();
      await _pumpPanel(
        tester,
        request: _tileRequest,
        autoStart: true,
        fake: fake,
      );

      fake.emit('Un dragon blanc.');
      await tester.pump(const Duration(milliseconds: 100));
      fake.close();
      await tester.pump(const Duration(milliseconds: 100));

      expect(find.text('Un dragon blanc.'), findsOneWidget);
    });

    testWidgets(
      'an empty stream shows the failure copy, and Réessayer asks again',
      (tester) async {
        final fake = ScriptedSenseiRepository();
        await _pumpPanel(
          tester,
          request: _tileRequest,
          autoStart: true,
          fake: fake,
        );

        fake.close();
        await tester.pump(const Duration(milliseconds: 100));

        expect(
          find.text(
            "L'explication n'est pas arrivée. Vous pouvez continuer sans elle.",
          ),
          findsOneWidget,
        );
        expect(find.text('Réessayer'), findsOneWidget);

        await tester.tap(find.text('Réessayer'));
        await tester.pump(const Duration(milliseconds: 100));

        expect(fake.callCount, 2);
      },
    );

    testWidgets('a SocketException shows the offline copy', (tester) async {
      final fake = ScriptedSenseiRepository();
      await _pumpPanel(
        tester,
        request: _tileRequest,
        autoStart: true,
        fake: fake,
      );

      fake.fail(const SocketException('no network'));
      await tester.pump(const Duration(milliseconds: 100));

      expect(
        find.text(
          'Hors ligne — les explications du sensei reviendront avec la connexion.',
        ),
        findsOneWidget,
      );
    });

    testWidgets('autoStart false asks nothing', (tester) async {
      final fake = ScriptedSenseiRepository();

      await _pumpPanel(
        tester,
        request: _tileRequest,
        autoStart: false,
        fake: fake,
      );

      expect(fake.callCount, 0);
    });
  });
}
