// AI-GENERATED by Claude (Claude Code), 2026-09-23
// Why: Test scaffolding is tedious and teaches no Flutter concept; the code under test is author-written.
import 'package:flutter_test/flutter_test.dart';
import 'package:tenpai/sensei/sensei_request.dart';
import 'package:tenpai/shared/models/tile.dart';

SenseiRequest _quizMiss({int chosenIndex = 0}) => SenseiRequest.quizMiss(
  question: 'Quelle tuile complète la main ?',
  hand: const ['1m', '2m', '3m'],
  options: const ['4m', '5m', '6m', '7m'],
  chosenIndex: chosenIndex,
  correctIndex: 1,
  feedback: 'Regardez la suite logique.',
);

void main() {
  group('SenseiRequest.quizMiss', () {
    test(
      'two requests built from the same fields are equal and share a hashCode',
      () {
        final a = _quizMiss();
        final b = _quizMiss();

        expect(a, b);
        expect(a.hashCode, b.hashCode);
      },
    );

    test('a different chosenIndex makes the requests unequal', () {
      final a = _quizMiss();
      final b = _quizMiss(chosenIndex: 2);

      expect(a, isNot(b));
    });
  });

  group('SenseiRequest.tileContext', () {
    test('two requests for the same tile are equal and share a hashCode', () {
      final a = SenseiRequest.tileContext(Tile.parse('5pr'));
      final b = SenseiRequest.tileContext(Tile.parse('5pr'));

      expect(a, b);
      expect(a.hashCode, b.hashCode);
    });

    test('requests for different tiles are unequal', () {
      final a = SenseiRequest.tileContext(Tile.parse('1m'));
      final b = SenseiRequest.tileContext(Tile.parse('2m'));

      expect(a, isNot(b));
    });
  });
}
