// AI-GENERATED by Claude (Claude Code), 2026-09-23
// Why: Test scaffolding is tedious and teaches no Flutter concept; the code under test is author-written.
import 'package:flutter_test/flutter_test.dart';
import 'package:tenpai/sensei/sensei_state.dart';

/// Exhaustive on purpose: a variant added to [SenseiState] without a matching
/// arm here fails to compile, catching the same gap the panel's own switch
/// would hit.
String _describe(SenseiState state) => switch (state) {
  SenseiIdle() => 'idle',
  SenseiLoading() => 'loading',
  SenseiStreaming(:final text) => 'streaming:$text',
  SenseiDone(:final text) => 'done:$text',
  SenseiFailed() => 'failed',
  SenseiOffline() => 'offline',
};

void main() {
  group('SenseiState', () {
    test('idle switches to its own arm', () {
      expect(_describe(const SenseiState.idle()), 'idle');
    });

    test('loading switches to its own arm', () {
      expect(_describe(const SenseiState.loading()), 'loading');
    });

    test('streaming carries its text', () {
      expect(_describe(const SenseiState.streaming('Un ')), 'streaming:Un ');
    });

    test('done carries its text', () {
      expect(
        _describe(const SenseiState.done('Un dragon blanc.')),
        'done:Un dragon blanc.',
      );
    });

    test('failed switches to its own arm', () {
      expect(_describe(const SenseiState.failed()), 'failed');
    });

    test('offline switches to its own arm', () {
      expect(_describe(const SenseiState.offline()), 'offline');
    });
  });
}
