// AI-GENERATED by Claude (Claude Code), 2026-09-17
// Why: Project tooling and setup so study time goes to Flutter code.
package io.github.codenam.tenpai

import io.flutter.embedding.android.FlutterActivity

class MainActivity : FlutterActivity()
