// AI-GENERATED by Claude (Claude Code), 2026-09-25
import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:tenpai/shared/models/lesson_block.dart';
import 'package:tenpai/shared/models/tile.dart';
import 'package:tenpai/shared/models/unit.dart';

/// Safety net for authored content: no hand-evaluation engine exists, so a
/// bad tile code or an out-of-range answer index would otherwise only be
/// caught by a human playing the lesson.
void main() {
  final files =
      Directory('assets/lessons')
          .listSync()
          .whereType<File>()
          .where((entity) => entity.path.endsWith('.json'))
          .toList()
        ..sort((a, b) => a.path.compareTo(b.path));

  final seenUnitIds = <String>{};
  final seenLessonIds = <String>{};

  for (final file in files) {
    final fileName = file.uri.pathSegments.last;

    group(fileName, () {
      Unit? unit;
      Object? parseError;

      try {
        final json =
            jsonDecode(file.readAsStringSync()) as Map<String, Object?>;
        unit = Unit.fromJson(json);
      } on Object catch (e) {
        parseError = e;
      }

      test('parses into a Unit', () {
        if (parseError != null) {
          fail('$fileName failed to parse: $parseError');
        }
      });

      if (unit == null) {
        return;
      }
      final parsedUnit = unit;

      test('has a non-blank title and a unit id unique across units', () {
        _expectNonBlank(parsedUnit.title, '$fileName: blank unit title');
        expect(
          seenUnitIds.add(parsedUnit.id),
          isTrue,
          reason: '$fileName: duplicate unit id "${parsedUnit.id}"',
        );
      });

      for (final lesson in parsedUnit.lessons) {
        group('lesson ${lesson.id}', () {
          test('has a non-blank title, xp > 0, and a unique id', () {
            _expectNonBlank(
              lesson.title,
              '$fileName lesson ${lesson.id}: blank title',
            );
            expect(
              lesson.xp,
              greaterThan(0),
              reason:
                  '$fileName lesson ${lesson.id}: xp must be > 0, '
                  'got ${lesson.xp}',
            );
            expect(
              seenLessonIds.add(lesson.id),
              isTrue,
              reason:
                  '$fileName lesson ${lesson.id}: duplicate lesson id '
                  'across units',
            );
          });

          test('has at least one block', () {
            expect(
              lesson.blocks,
              isNotEmpty,
              reason: '$fileName lesson ${lesson.id}: no blocks',
            );
          });

          for (var i = 0; i < lesson.blocks.length; i++) {
            final block = lesson.blocks[i];

            test('block $i (${block.runtimeType}) is well formed', () {
              _expectValidBlock(
                block,
                fileName: fileName,
                lessonId: lesson.id,
                blockIndex: i,
              );
            });
          }
        });
      }
    });
  }
}

/// Dispatches on the block's runtime type; the switch is exhaustive so a new
/// block variant fails to compile here until it gets its own checks.
void _expectValidBlock(
  LessonBlock block, {
  required String fileName,
  required String lessonId,
  required int blockIndex,
}) {
  switch (block) {
    case ExplanationBlock(:final tile, :final title, :final body):
      _expectValidTileCode(
        tile,
        fileName: fileName,
        lessonId: lessonId,
        blockIndex: blockIndex,
        field: 'tile',
      );
      _expectNonBlank(
        title,
        '$fileName lesson $lessonId block $blockIndex: blank title',
      );
      _expectNonBlank(
        body,
        '$fileName lesson $lessonId block $blockIndex: blank body',
      );

    case QuizBlock(
      :final question,
      :final hand,
      :final options,
      :final correctIndex,
      :final feedback,
    ):
      expect(
        hand.length,
        13,
        reason:
            '$fileName lesson $lessonId block $blockIndex: quiz hand '
            'must have 13 tiles, got ${hand.length}',
      );
      for (final code in hand) {
        _expectValidTileCode(
          code,
          fileName: fileName,
          lessonId: lessonId,
          blockIndex: blockIndex,
          field: 'hand',
        );
      }
      expect(
        options.length,
        4,
        reason:
            '$fileName lesson $lessonId block $blockIndex: quiz needs '
            'exactly 4 options, got ${options.length}',
      );
      for (final code in options) {
        _expectValidTileCode(
          code,
          fileName: fileName,
          lessonId: lessonId,
          blockIndex: blockIndex,
          field: 'options',
        );
      }
      expect(
        options.toSet().length,
        options.length,
        reason:
            '$fileName lesson $lessonId block $blockIndex: quiz '
            'options must be distinct, got $options',
      );
      expect(
        correctIndex,
        inInclusiveRange(0, options.length - 1),
        reason:
            '$fileName lesson $lessonId block $blockIndex: '
            'correctIndex $correctIndex out of range for ${options.length} '
            'options',
      );
      _expectNonBlank(
        question,
        '$fileName lesson $lessonId block $blockIndex: blank question',
      );
      _expectNonBlank(
        feedback,
        '$fileName lesson $lessonId block $blockIndex: blank feedback',
      );

    case DrillBlock(
      :final prompt,
      :final hand,
      :final answers,
      :final feedback,
    ):
      expect(
        hand.length,
        13,
        reason:
            '$fileName lesson $lessonId block $blockIndex: drill hand '
            'must have 13 tiles, got ${hand.length}',
      );
      for (final code in hand) {
        _expectValidTileCode(
          code,
          fileName: fileName,
          lessonId: lessonId,
          blockIndex: blockIndex,
          field: 'hand',
        );
      }
      expect(
        answers,
        isNotEmpty,
        reason:
            '$fileName lesson $lessonId block $blockIndex: drill needs '
            'at least one answer',
      );
      for (final answer in answers) {
        expect(
          answer,
          inInclusiveRange(0, 12),
          reason:
              '$fileName lesson $lessonId block $blockIndex: answer '
              '$answer out of range for a 13-tile hand',
        );
      }
      expect(
        answers.toSet().length,
        answers.length,
        reason:
            '$fileName lesson $lessonId block $blockIndex: drill '
            'answers must be distinct, got $answers',
      );
      _expectNonBlank(
        prompt,
        '$fileName lesson $lessonId block $blockIndex: blank prompt',
      );
      _expectNonBlank(
        feedback,
        '$fileName lesson $lessonId block $blockIndex: blank feedback',
      );

    case InteractiveBlock(
      :final prompt,
      :final group,
      :final slot,
      :final rack,
      :final correctIndex,
      :final feedback,
    ):
      for (final code in group) {
        _expectValidTileCode(
          code,
          fileName: fileName,
          lessonId: lessonId,
          blockIndex: blockIndex,
          field: 'group',
        );
      }
      for (final code in rack) {
        _expectValidTileCode(
          code,
          fileName: fileName,
          lessonId: lessonId,
          blockIndex: blockIndex,
          field: 'rack',
        );
      }
      expect(
        slot,
        inInclusiveRange(0, group.length),
        reason:
            '$fileName lesson $lessonId block $blockIndex: slot $slot '
            'out of range for a group of ${group.length} tiles',
      );
      expect(
        rack.length,
        inInclusiveRange(4, 6),
        reason:
            '$fileName lesson $lessonId block $blockIndex: rack must '
            'have 4 to 6 tiles, got ${rack.length}',
      );
      expect(
        correctIndex,
        inInclusiveRange(0, rack.length - 1),
        reason:
            '$fileName lesson $lessonId block $blockIndex: '
            'correctIndex $correctIndex out of range for a rack of '
            '${rack.length} tiles',
      );
      expect(
        rack.toSet().length,
        rack.length,
        reason:
            '$fileName lesson $lessonId block $blockIndex: rack '
            'entries must be distinct, got $rack',
      );
      _expectNonBlank(
        prompt,
        '$fileName lesson $lessonId block $blockIndex: blank prompt',
      );
      _expectNonBlank(
        feedback,
        '$fileName lesson $lessonId block $blockIndex: blank feedback',
      );
  }
}

/// Parses [code] and checks that `TileWidget`'s art file exists for it
/// (`assets/tiles/<code>.svg`, `tile.code` round-tripped so a red five's
/// trailing `r` is preserved).
void _expectValidTileCode(
  String code, {
  required String fileName,
  required String lessonId,
  required int blockIndex,
  required String field,
}) {
  Tile tile;
  try {
    tile = Tile.parse(code);
  } on Object catch (e) {
    fail(
      '$fileName lesson $lessonId block $blockIndex ($field): tile code '
      '"$code" does not parse: $e',
    );
  }
  final svg = File('assets/tiles/${tile.code}.svg');
  expect(
    svg.existsSync(),
    isTrue,
    reason:
        '$fileName lesson $lessonId block $blockIndex ($field): '
        'missing assets/tiles/${tile.code}.svg for code "$code"',
  );
}

void _expectNonBlank(String value, String message) {
  expect(value.trim(), isNotEmpty, reason: message);
}
