// AI-GENERATED by Claude (Claude Code), 2026-09-17
// Why: Project tooling and setup so study time goes to Flutter code.
//
// Checks the naming and privacy conventions from CLAUDE.md that lints cannot
// express. Run: `dart run tool/check_conventions.dart [root]`. Exit code 1 on
// findings.
//
// Checks on `root` (default `lib`):
//   1. The primary type of a file is named after the file (snake -> Pascal).
//   2. Files in role folders carry the role suffix, and the class matches.
//   3. Providers are named for what they expose, never `*NotifierProvider`.
//   4. Public top-level symbols referenced from no other file (best-effort).
// Repo-wide:
//   5. AI attribution markers are well-formed, BEGIN/END balanced, and every
//      file with a header is listed in docs/AI_CONTRIBUTIONS.md (and every
//      listed path exists).
//
// Heuristic by design: regex over source, no analyzer. Cheap, fast, good enough
// to catch the habit-level mistakes the reviewer would otherwise repeat.

import 'dart:io';

// --- AI attribution (docs/AI_CONTRIBUTIONS.md) -------------------------------

/// The marker token, split so this file's own regexes do not trip the scan.
const _tag = 'AI-' 'GENERATED';
const _register = 'docs/AI_CONTRIBUTIONS.md';
const _headerWindow = 15;

/// Path prefixes never scanned for markers.
const _attributionSkip = <String>[
  'build/',
  '.dart_tool/',
  '.git/',
  'design/handoff/',
  'assets/',
  'android/.gradle/',
  'android/gradle/',
  _register, // holds the format examples
];
const _attributionExtensions = <String>{
  '.dart', '.kt', '.kts', '.py', '.md', '.yaml', '.yml', '.xml', '.gitignore',
};

/// A marker is the token at the start of a comment. Prose that merely mentions
/// the token (docs, agent instructions) is not a marker.
const _commentStart = r'^\s*(?://|#|<!--)\s*';
final _aiHeader = RegExp(
  '$_commentStart$_tag by Claude \\(Claude Code\\), \\d{4}-\\d{2}-\\d{2}\\b',
);
final _aiBegin = RegExp('$_commentStart$_tag \\(Claude\\) BEGIN — .+');
final _aiEnd = RegExp('$_commentStart$_tag \\(Claude\\) END\\b');
final _aiAny = RegExp('$_commentStart$_tag');

/// Immediate parent folder name -> accepted file suffixes (without `.dart`).
///
/// Keyed on the folder *name* only, so it works with whatever tree the user
/// builds: any `screens/` folder anywhere expects `*_screen.dart`.
const _folderSuffix = <String, List<String>>{
  'screens': ['_screen'],
  'dtos': ['_dto'],
  'repositories': ['_repository', '_repository_impl'],
  'sources': ['_source'],
  'providers': ['_providers'],
};

/// Base names whose primary declaration is legitimately not a type named after
/// them (entry point, route table).
const _exemptBaseNames = <String>{'main', 'router'};

final _typeDecl = RegExp(
  r'^(?:(?:abstract|final|sealed|base|interface|mixin)\s+)*'
  r'(?:class|enum|mixin|extension type|extension)\s+(\w+)',
  multiLine: true,
);

/// Top-level functions/variables at column 0: `final GoRouter appRouter =`,
/// `void main() {`, `Future<int> load(`.
final _topLevelValue = RegExp(
  r'^(?:(?:final|const|late|var)\s+)?(?:[A-Za-z_][\w<>,?\s]*?\s+)?'
  r'([a-zA-Z]\w*)\s*(?:=|\()',
  multiLine: true,
);

final _providerDecl = RegExp(r'^final\s+(\w*Provider)\b', multiLine: true);

/// Optional first argument: the source root to scan (defaults to `lib`).
/// Used to run the checker against fixtures outside the project.
void main(List<String> args) {
  final root = args.isEmpty ? 'lib' : args.first;
  final files = Directory(root)
      .listSync(recursive: true)
      .whereType<File>()
      .where((f) => f.path.endsWith('.dart'))
      .where((f) => !f.path.endsWith('.g.dart'))
      .where((f) => !f.path.endsWith('.freezed.dart'))
      .toList()
    ..sort((a, b) => a.path.compareTo(b.path));
  final sources = {for (final f in files) f.path: f.readAsStringSync()};
  final testSources = _readTests();

  final findings = <String>[];
  for (final entry in sources.entries) {
    findings
      ..addAll(_checkFileClassMatch(entry.key, entry.value))
      ..addAll(_checkFolderSuffix(entry.key))
      ..addAll(_checkProviderNames(entry.key, entry.value))
      ..addAll(_checkPublicUnused(entry.key, entry.value, sources, testSources));
  }
  if (root == 'lib') {
    findings.addAll(_checkAttribution());
  }

  if (findings.isEmpty) {
    stdout.writeln('check_conventions: ${files.length} files, no findings.');
    return;
  }
  findings.forEach(stderr.writeln);
  stderr.writeln('check_conventions: ${findings.length} finding(s).');
  exitCode = 1;
}

/// Repo-wide scan of `AI-GENERATED` markers against the rules in
/// docs/AI_CONTRIBUTIONS.md.
Iterable<String> _checkAttribution() sync* {
  final headerFiles = <String>{};
  final entities = Directory('.').listSync(recursive: true, followLinks: false);
  for (final entity in entities) {
    if (entity is! File) {
      continue;
    }
    final path = entity.path.startsWith('./')
        ? entity.path.substring(2)
        : entity.path;
    if (_attributionSkip.any(path.startsWith)) {
      continue;
    }
    final name = path.split('/').last;
    final ext = name.contains('.') ? name.substring(name.lastIndexOf('.')) : '';
    if (!_attributionExtensions.contains(ext) && name != '.gitignore') {
      continue;
    }
    final lines = entity.readAsLinesSync();
    var depth = 0;
    for (var i = 0; i < lines.length; i++) {
      final line = lines[i];
      if (!_aiAny.hasMatch(line)) {
        continue;
      }
      final at = '$path:${i + 1}';
      if (_aiHeader.hasMatch(line)) {
        headerFiles.add(path);
        if (i >= _headerWindow) {
          yield '$at: attribution header must sit within the first '
              '$_headerWindow lines.';
        }
      } else if (_aiBegin.hasMatch(line)) {
        depth++;
        if (depth > 1) {
          yield '$at: nested attribution BEGIN; close the previous block first.';
        }
      } else if (_aiEnd.hasMatch(line)) {
        depth--;
        if (depth < 0) {
          yield '$at: attribution END without a BEGIN.';
          depth = 0;
        }
      } else {
        yield '$at: malformed attribution marker; see $_register.';
      }
    }
    if (depth != 0) {
      yield '$path: attribution BEGIN without END.';
    }
  }

  final register = File(_register);
  if (!register.existsSync()) {
    yield '$_register: missing; every AI-written file must be listed there.';
    return;
  }
  final listed = <String>{};
  for (final line in register.readAsLinesSync()) {
    final m = RegExp(r'^\|\s*`([^`]+)`').firstMatch(line);
    if (m != null) {
      listed.add(m.group(1)!);
    }
  }
  for (final path in headerFiles.difference(listed).toList()..sort()) {
    yield '$path: has an attribution header but is not listed in $_register.';
  }
  for (final path in listed.toList()..sort()) {
    if (!File(path).existsSync()) {
      yield '$_register: lists `$path`, which does not exist.';
    }
  }
}

Map<String, String> _readTests() {
  final dir = Directory('test');
  if (!dir.existsSync()) {
    return const {};
  }
  return {
    for (final f in dir.listSync(recursive: true).whereType<File>())
      if (f.path.endsWith('.dart')) f.path: f.readAsStringSync(),
  };
}

String _baseName(String path) =>
    path.split('/').last.replaceFirst(RegExp(r'\.dart$'), '');

String _pascal(String snake) => snake
    .split('_')
    .where((p) => p.isNotEmpty)
    .map((p) => p[0].toUpperCase() + p.substring(1))
    .join();

int _lineOf(String source, int offset) =>
    '\n'.allMatches(source.substring(0, offset)).length + 1;

Iterable<String> _checkFileClassMatch(String path, String source) sync* {
  if (_exemptBaseNames.contains(_baseName(path)) ||
      path.endsWith('_providers.dart')) {
    return;
  }
  final expected = _pascal(_baseName(path));
  final declared = _typeDecl.allMatches(source).map((m) => m.group(1)!).toSet();
  if (declared.isEmpty) {
    return; // a file of top-level functions; nothing to match
  }
  if (!declared.contains(expected)) {
    yield '$path:1: primary type should be `$expected` (found: '
        '${declared.join(', ')}). Rename the file or the class.';
  }
}

Iterable<String> _checkFolderSuffix(String path) sync* {
  final segments = path.split('/');
  if (segments.length < 2) {
    return;
  }
  final suffixes = _folderSuffix[segments[segments.length - 2]];
  if (suffixes == null) {
    return;
  }
  final base = _baseName(path);
  if (!suffixes.any(base.endsWith)) {
    final expected = suffixes.map((s) => '`$s.dart`').join(' or ');
    yield '$path:1: files in a ${segments[segments.length - 2]}/ folder end '
        'with $expected.';
  }
}

Iterable<String> _checkProviderNames(String path, String source) sync* {
  for (final m in _providerDecl.allMatches(source)) {
    final name = m.group(1)!;
    if (name.endsWith('NotifierProvider') || name.contains('Notifier')) {
      yield '$path:${_lineOf(source, m.start)}: `$name` is named for its '
          'mechanism. Name it for what it exposes (e.g. `currentLessonProvider`).';
    }
    if (!path.endsWith('_providers.dart')) {
      yield '$path:${_lineOf(source, m.start)}: provider `$name` belongs in a '
          '`*_providers.dart` file.';
    }
  }
}

Iterable<String> _checkPublicUnused(
  String path,
  String source,
  Map<String, String> sources,
  Map<String, String> tests,
) sync* {
  final names = <String, int>{};
  for (final m in _typeDecl.allMatches(source)) {
    names[m.group(1)!] = m.start;
  }
  for (final m in _topLevelValue.allMatches(source)) {
    names.putIfAbsent(m.group(1)!, () => m.start);
  }
  for (final entry in names.entries) {
    final name = entry.key;
    if (name.startsWith('_') || name == 'main') {
      continue;
    }
    final word = RegExp('\\b$name\\b');
    final usedElsewhere = sources.entries.any(
          (e) => e.key != path && word.hasMatch(e.value),
        ) ||
        tests.values.any(word.hasMatch);
    if (!usedElsewhere) {
      yield '$path:${_lineOf(source, entry.value)}: `$name` is public but used '
          'only in this file. Prefix with `_` unless another file needs it.';
    }
  }
}
