// AI-GENERATED by Claude (Claude Code), 2026-09-23
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:material_ui/material_ui.dart';
import 'package:tenpai/scanner/scan_state.dart';
import 'package:tenpai/scanner/scanner_providers.dart';
import 'package:tenpai/sensei/sensei_panel_widget.dart';
import 'package:tenpai/sensei/sensei_request.dart';
import 'package:tenpai/shared/models/tile.dart';
import 'package:tenpai/shared/models/tile_labels.dart';
import 'package:tenpai/shared/theme/app_colors.dart';
import 'package:tenpai/shared/theme/app_tokens.dart';
import 'package:tenpai/shared/widgets/primary_button_widget.dart';
import 'package:tenpai/shared/widgets/tile_size.dart';
import 'package:tenpai/shared/widgets/tile_widget.dart';

/// Scanner tab, handoff screens 14, 16 and 17. One `Stack`: the viewfinder
/// underneath, a sheet slid in from the bottom on a result or a failure
/// (same pattern as the lesson feedback sheet). The sheet *is* the tile's
/// card; the Sensei panel joins it at M5 as new [ScanState] variants.
class ScannerScreen extends ConsumerWidget {
  /// Everything comes from [scanProvider]; no parameters.
  const ScannerScreen({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final state = ref.watch(scanProvider);
    final colors = Theme.of(context).extension<AppColors>()!;
    void scan() => ref.read(scanProvider.notifier).scan();

    return Scaffold(
      backgroundColor: colors.viewfinderBg,
      body: Stack(
        children: [
          _Viewfinder(onShutter: state is ScanAnalysing ? null : scan),
          Positioned(
            left: 0,
            right: 0,
            bottom: 0,
            child: AnimatedSlide(
              offset: switch (state) {
                ScanFound() || ScanNotFound() => Offset.zero,
                ScanIdle() || ScanAnalysing() => const Offset(0, 1),
              },
              duration: AppTokens.duration,
              curve: AppTokens.curve,
              // Idle and analysing render nothing: the sheet snaps away when
              // « Réessayer » reopens the camera, which covers it anyway.
              child: switch (state) {
                ScanFound(:final tile) => _ResultSheet(
                  tile: tile,
                  onAgain: scan,
                ),
                ScanNotFound() => _FailureSheet(onRetry: scan),
                ScanIdle() || ScanAnalysing() => const SizedBox.shrink(),
              },
            ),
          ),
        ],
      ),
    );
  }
}

/// Handoff 14. Static: no live preview, the system camera opens on the
/// shutter (the requirement is a single-shot photo, not a feed).
class _Viewfinder extends StatelessWidget {
  const _Viewfinder({required this.onShutter});

  /// Null while a scan runs: the shutter dims and ignores taps.
  final VoidCallback? onShutter;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final colors = theme.extension<AppColors>()!;
    // The viewfinder is dark in both modes, so onSurface (ink in light mode)
    // would vanish; onPrimary is white in both schemes.
    final ink = theme.colorScheme.onPrimary;

    return SafeArea(
      child: Padding(
        padding: const EdgeInsets.all(AppTokens.sideMargin),
        child: Column(
          children: [
            Text(
              '[ flux caméra ]'.toUpperCase(),
              style: theme.textTheme.labelMedium?.copyWith(
                color: colors.mutedStrong,
              ),
            ),
            Expanded(
              child: Center(
                child: FractionallySizedBox(
                  widthFactor: AppTokens.viewfinderWidthFactor,
                  child: AspectRatio(
                    aspectRatio:
                        TileSize.regular.width / TileSize.regular.height,
                    child: CustomPaint(
                      painter: _BracketPainter(colors.viewfinderBracket),
                    ),
                  ),
                ),
              ),
            ),
            Text(
              'Cadrez une tuile',
              style: theme.textTheme.bodyMedium?.copyWith(color: ink),
            ),
            const SizedBox(height: AppTokens.space4),
            _Shutter(onPressed: onShutter),
          ],
        ),
      ),
    );
  }
}

/// Four L-shaped corner marks, no full border (handoff: « équerres vertes
/// aux coins »). Inset by half the stroke so nothing bleeds past the box.
class _BracketPainter extends CustomPainter {
  const _BracketPainter(this.color);

  final Color color;

  @override
  void paint(Canvas canvas, Size size) {
    final paint = Paint()
      ..color = color
      ..style = .stroke
      ..strokeWidth = AppTokens.bracketStroke
      ..strokeCap = .round
      ..strokeJoin = .round;
    const arm = AppTokens.bracketArm;
    final rect = Rect.fromLTWH(
      AppTokens.bracketStroke / 2,
      AppTokens.bracketStroke / 2,
      size.width - AppTokens.bracketStroke,
      size.height - AppTokens.bracketStroke,
    );
    final path = Path()
      ..moveTo(rect.left, rect.top + arm)
      ..lineTo(rect.left, rect.top)
      ..lineTo(rect.left + arm, rect.top)
      ..moveTo(rect.right - arm, rect.top)
      ..lineTo(rect.right, rect.top)
      ..lineTo(rect.right, rect.top + arm)
      ..moveTo(rect.right, rect.bottom - arm)
      ..lineTo(rect.right, rect.bottom)
      ..lineTo(rect.right - arm, rect.bottom)
      ..moveTo(rect.left + arm, rect.bottom)
      ..lineTo(rect.left, rect.bottom)
      ..lineTo(rect.left, rect.bottom - arm);
    canvas.drawPath(path, paint);
  }

  @override
  bool shouldRepaint(_BracketPainter oldDelegate) => oldDelegate.color != color;
}

/// White disc with a green ring (handoff 14). Disabled = dimmed with the same
/// opacity as a locked yaku card, so the two « pas maintenant » cues match.
class _Shutter extends StatelessWidget {
  const _Shutter({required this.onPressed});

  /// Null disables: the viewfinder passes null while a scan runs.
  final VoidCallback? onPressed;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final colors = theme.extension<AppColors>()!;
    final enabled = onPressed != null;

    return Semantics(
      button: true,
      enabled: enabled,
      label: 'Prendre la photo',
      child: Opacity(
        opacity: enabled ? 1 : AppTokens.lockedOpacity,
        child: Material(
          color: theme.colorScheme.onPrimary,
          shape: CircleBorder(
            side: BorderSide(
              color: colors.viewfinderBracket,
              width: AppTokens.shutterRing,
            ),
          ),
          child: InkWell(
            customBorder: const CircleBorder(),
            onTap: onPressed,
            child: const SizedBox.square(dimension: AppTokens.shutterSize),
          ),
        ),
      ),
    );
  }
}

/// Handoff 16 minus « Voir la fiche » (no tile catalogue to open yet). Big
/// tile, name, family line, the Sensei context streamed (`autoStart`, since
/// the sheet only exists once a tile is found), one CTA. Leaving the sheet
/// disposes the panel's provider member, which cancels the stream.
class _ResultSheet extends StatelessWidget {
  const _ResultSheet({required this.tile, required this.onAgain});

  final Tile tile;

  /// Starts a new scan; the sheet leaves as the camera opens.
  final VoidCallback onAgain;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final colors = theme.extension<AppColors>()!;
    // Mono caps are applied here, not in the theme (see app_theme.dart).
    final family = '${tile.isRed ? 'aka dora · ' : ''}${tileFamily(tile)}'
        .toUpperCase();

    return _Sheet(
      children: [
        Center(
          child: TileWidget(tile: tile, size: .demo),
        ),
        const SizedBox(height: AppTokens.space2),
        Text(
          tileName(tile),
          style: theme.textTheme.headlineSmall,
          textAlign: .center,
        ),
        const SizedBox(height: AppTokens.space1),
        Text(
          family,
          style: theme.textTheme.labelMedium?.copyWith(
            color: colors.mutedStrong,
          ),
          textAlign: .center,
        ),
        const SizedBox(height: AppTokens.space3),
        SenseiPanelWidget(
          request: SenseiRequest.tileContext(tile),
          autoStart: true,
        ),
        const SizedBox(height: AppTokens.space3),
        PrimaryButtonWidget(
          label: 'Scanner une autre tuile',
          onPressed: onAgain,
        ),
      ],
    );
  }
}

/// Handoff 17 minus « Parcourir le catalogue des tuiles » (no catalogue
/// yet). Honest copy, one primary action: the failure is never a dead end.
class _FailureSheet extends StatelessWidget {
  const _FailureSheet({required this.onRetry});

  /// Same as a shutter press: the camera opens again.
  final VoidCallback onRetry;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final colors = theme.extension<AppColors>()!;

    return _Sheet(
      children: [
        const Center(child: _UnknownTile()),
        const SizedBox(height: AppTokens.space2),
        Text(
          'Tuile non reconnue',
          style: theme.textTheme.headlineSmall,
          textAlign: .center,
        ),
        const SizedBox(height: AppTokens.space1),
        Text(
          "rien d'identifié".toUpperCase(),
          style: theme.textTheme.labelMedium?.copyWith(
            color: colors.mutedStrong,
          ),
          textAlign: .center,
        ),
        const SizedBox(height: AppTokens.space2),
        Text(
          'Ça arrive. Essayez avec plus de lumière, la tuile bien à plat et '
          'seule dans le cadre.',
          style: theme.textTheme.bodyMedium,
          textAlign: .center,
        ),
        const SizedBox(height: AppTokens.space3),
        PrimaryButtonWidget(label: 'Réessayer', onPressed: onRetry),
      ],
    );
  }
}

/// Grey « ? » in the demo tile's footprint. [TileWidget] has no unknown
/// state and one screen does not justify adding one.
class _UnknownTile extends StatelessWidget {
  const _UnknownTile();

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final colors = theme.extension<AppColors>()!;

    return SizedBox(
      width: TileSize.demo.width,
      height: TileSize.demo.height,
      child: DecoratedBox(
        decoration: BoxDecoration(
          color: colors.track,
          borderRadius: BorderRadius.circular(TileSize.demo.radius),
        ),
        child: Center(
          child: Text(
            '?',
            style: theme.textTheme.headlineLarge?.copyWith(
              color: colors.mutedStrong,
            ),
          ),
        ),
      ),
    );
  }
}

/// Shell shared by both sheets: surface, top radius, handle, safe area.
/// Stretched column so the CTA fills the width; children centre themselves.
class _Sheet extends StatelessWidget {
  const _Sheet({required this.children});

  final List<Widget> children;

  @override
  Widget build(BuildContext context) {
    final scheme = Theme.of(context).colorScheme;

    return DecoratedBox(
      decoration: BoxDecoration(
        color: scheme.surface,
        borderRadius: AppTokens.radiusSheet,
      ),
      child: Padding(
        padding: const EdgeInsets.all(AppTokens.sideMargin),
        child: SafeArea(
          top: false,
          child: Column(
            mainAxisSize: .min,
            crossAxisAlignment: .stretch,
            children: [
              const Center(child: _Handle()),
              const SizedBox(height: AppTokens.space3),
              ...children,
            ],
          ),
        ),
      ),
    );
  }
}

/// Decorative drag handle: the sheet closes through its CTA, not by
/// dragging, because a dismissed sheet would need a state the notifier
/// does not have.
class _Handle extends StatelessWidget {
  const _Handle();

  @override
  Widget build(BuildContext context) {
    final colors = Theme.of(context).extension<AppColors>()!;

    return SizedBox(
      width: AppTokens.sheetHandleWidth,
      height: AppTokens.sheetHandleHeight,
      child: DecoratedBox(
        decoration: BoxDecoration(
          color: colors.track,
          borderRadius: AppTokens.radiusProgress,
        ),
      ),
    );
  }
}
