// AI-GENERATED by Claude (Claude Code), 2026-09-23
// Why: Test scaffolding is tedious and teaches no Flutter concept; the code under test is author-written.
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:material_ui/material_ui.dart';
import 'package:tenpai/onboarding/goal_screen.dart';
import 'package:tenpai/profile/profile_providers.dart';
import 'package:tenpai/profile/user_profile.dart';
import 'package:tenpai/shared/theme/app_theme.dart';

import '../fakes/fake_profile_repository.dart';

Future<FakeProfileRepository> _pumpGoal(WidgetTester tester) async {
  final repository = FakeProfileRepository();
  // OnboardingScaffoldWidget lays its four option cards in a plain Column,
  // not a scroll view: the default test surface is too short for them.
  await tester.binding.setSurfaceSize(const Size(800, 1000));
  addTearDown(() => tester.binding.setSurfaceSize(null));
  await tester.pumpWidget(
    ProviderScope(
      overrides: [profileRepositoryProvider.overrideWithValue(repository)],
      retry: (_, _) => null,
      child: MaterialApp(
        theme: lightTheme(),
        home: const GoalScreen(level: MahjongLevel.seen),
      ),
    ),
  );
  await tester.pumpAndSettle();
  return repository;
}

void main() {
  group('GoalScreen', () {
    testWidgets('the CTA is disabled until a card is tapped', (tester) async {
      await _pumpGoal(tester);

      final cta = tester.widget<FilledButton>(
        find.widgetWithText(FilledButton, "C'est parti"),
      );

      expect(cta.onPressed, isNull);
    });

    testWidgets(
      "tapping 10 min / jour then C'est parti saves the profile",
      (tester) async {
        final repository = await _pumpGoal(tester);

        await tester.tap(find.text('10 min / jour'));
        await tester.pumpAndSettle();
        await tester.tap(find.widgetWithText(FilledButton, "C'est parti"));
        await tester.pumpAndSettle();

        expect(repository.saveCalls, [
          const UserProfile(level: MahjongLevel.seen, dailyGoalMinutes: 10),
        ]);
      },
    );
  });
}
