// AI-GENERATED by Claude (Claude Code), 2026-09-23
// Why: Test scaffolding is tedious and teaches no Flutter concept; the code under test is author-written.
import 'package:flutter_test/flutter_test.dart';
import 'package:go_router/go_router.dart';
import 'package:material_ui/material_ui.dart';
import 'package:tenpai/onboarding/level_screen.dart';
import 'package:tenpai/shared/theme/app_theme.dart';

GoRouter _buildRouter() => GoRouter(
  initialLocation: '/onboarding/level',
  routes: [
    GoRoute(path: '/onboarding/level', builder: (_, _) => const LevelScreen()),
    GoRoute(
      path: '/onboarding/goal',
      builder: (_, state) =>
          Text('goal level=${state.uri.queryParameters['level']}'),
    ),
  ],
);

Future<void> _pumpLevel(WidgetTester tester) async {
  await tester.pumpWidget(
    MaterialApp.router(theme: lightTheme(), routerConfig: _buildRouter()),
  );
  await tester.pumpAndSettle();
}

void main() {
  group('LevelScreen', () {
    testWidgets('the CTA is disabled until a card is tapped', (tester) async {
      await _pumpLevel(tester);

      final cta = tester.widget<FilledButton>(
        find.widgetWithText(FilledButton, 'Continuer'),
      );

      expect(cta.onPressed, isNull);
    });

    testWidgets(
      'tapping Jamais joué then Continuer navigates with level=never',
      (tester) async {
        await _pumpLevel(tester);

        await tester.tap(find.text('Jamais joué'));
        await tester.pumpAndSettle();
        await tester.tap(find.widgetWithText(FilledButton, 'Continuer'));
        await tester.pumpAndSettle();

        expect(find.text('goal level=never'), findsOneWidget);
      },
    );
  });
}
