// AI-GENERATED by Claude (Claude Code), 2026-09-25
import 'package:material_ui/material_ui.dart';
import 'package:tenpai/shared/theme/app_tokens.dart';
import 'package:tenpai/shared/widgets/primary_button_widget.dart';

/// Shared frame of every block the learner checks (quiz, drill,
/// interactive): prompt, block-specific [body], « Vérifier » pinned to the
/// bottom, and [sheet] sliding up over it once answered. Knows nothing about
/// sessions; each view decides when checking is allowed.
class CheckableBlockWidget extends StatelessWidget {
  /// The views pass their own [onCheck] rule: a quiz needs an option, a
  /// drill at least one pick.
  const CheckableBlockWidget({
    super.key,
    required this.prompt,
    required this.body,
    required this.onCheck,
    required this.isAnswered,
    required this.sheet,
  });

  /// Headline above the body (the question or the instruction).
  final String prompt;

  /// Laid out in the column between the prompt and the spacer, so each
  /// entry keeps its intrinsic height.
  final List<Widget> body;

  /// Null disables « Vérifier »: nothing picked yet, or already answered.
  final VoidCallback? onCheck;

  /// Slides [sheet] in; before that it waits one sheet-height below the
  /// screen, still in the tree, so it animates rather than pops.
  final bool isAnswered;

  /// Usually a `FeedbackSheetWidget`.
  final Widget sheet;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return Stack(
      children: [
        Padding(
          padding: const EdgeInsets.symmetric(horizontal: AppTokens.sideMargin),
          child: Column(
            crossAxisAlignment: .start,
            children: [
              Text(prompt, style: theme.textTheme.headlineSmall),
              const SizedBox(height: AppTokens.space3),
              ...body,
              const Spacer(),
              SafeArea(
                top: false,
                child: PrimaryButtonWidget(
                  label: 'Vérifier',
                  onPressed: onCheck,
                ),
              ),
            ],
          ),
        ),
        Positioned(
          left: 0,
          right: 0,
          bottom: 0,
          child: AnimatedSlide(
            offset: isAnswered ? Offset.zero : const Offset(0, 1),
            duration: AppTokens.duration,
            curve: AppTokens.curve,
            child: sheet,
          ),
        ),
      ],
    );
  }
}
