// AI-GENERATED by Claude (Claude Code), 2026-09-25
import 'package:flutter/foundation.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:material_ui/material_ui.dart';
import 'package:tenpai/learning/lesson_providers.dart';
import 'package:tenpai/learning/lesson_session.dart';
import 'package:tenpai/learning/widgets/checkable_block_widget.dart';
import 'package:tenpai/learning/widgets/feedback_sheet_widget.dart';
import 'package:tenpai/sensei/sensei_request.dart';
import 'package:tenpai/shared/models/lesson_block.dart';
import 'package:tenpai/shared/models/tile.dart';
import 'package:tenpai/shared/theme/app_tokens.dart';
import 'package:tenpai/shared/widgets/tile_state.dart';
import 'package:tenpai/shared/widgets/tile_widget.dart';

/// « Find in the hand »: same layout and sheet as the quiz, but the pick is
/// a set of hand indices, right only when it equals the authored answers
/// exactly (order-free, `setEquals`). A miss offers « Pourquoi ? » through
/// a `drillMiss` request whose picks are sorted, so one miss is one key.
class DrillBlockWidget extends ConsumerWidget {
  /// [session] is passed down rather than watched here: the lesson body
  /// already watches it, so the block rebuilds with it.
  const DrillBlockWidget({
    super.key,
    required this.block,
    required this.session,
    required this.onContinue,
  });

  /// The prompt, 13-tile hand and authored answer indices.
  final DrillBlock block;

  /// Current picks and answered flag for this lesson.
  final LessonSession session;

  /// Advances to the next block or completes the lesson.
  final VoidCallback onContinue;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final notifier = ref.read(currentLessonProvider(session.lessonId).notifier);
    final missed =
        session.isAnswered && !setEquals(session.picked, block.answers.toSet());
    final whyRequest = missed
        ? SenseiRequest.drillMiss(
            prompt: block.prompt,
            hand: block.hand,
            picked: session.picked.toList()..sort(),
            answers: block.answers,
            feedback: block.feedback,
          )
        : null;
    return CheckableBlockWidget(
      prompt: block.prompt,
      body: [
        _DrillHand(
          hand: block.hand,
          answers: block.answers,
          isAnswered: session.isAnswered,
          onToggle: session.isAnswered ? null : notifier.toggle,
          picked: session.picked,
        ),
      ],
      onCheck: session.picked.isEmpty || session.isAnswered
          ? null
          : notifier.check,
      isAnswered: session.isAnswered,
      sheet: FeedbackSheetWidget(
        isCorrect: setEquals(session.picked, block.answers.toSet()),
        feedback: block.feedback,
        missLine: 'Il manque des tuiles, ou certaines sont en trop.',
        whyRequest: whyRequest,
        onContinue: onContinue,
        onRetry: notifier.retry,
      ),
    );
  }
}

/// The 13 tiles at option size (48×66, tappable, unlike the 24 px quiz
/// hand) wrapped 7 + 6: 7 × 48 + 6 × 2 = 348 fits the 350 dp column. Row
/// spacing exceeds the selected lift so a raised tile clears the row above.
class _DrillHand extends StatelessWidget {
  const _DrillHand({
    required this.hand,
    required this.answers,
    required this.picked,
    required this.isAnswered,
    this.onToggle,
  });
  final List<String> hand;
  final List<int> answers;
  final Set<int> picked;
  final bool isAnswered;
  final ValueChanged<int>? onToggle;

  @override
  Widget build(BuildContext context) => Wrap(
    alignment: .center,
    spacing: AppTokens.drillGap,
    runSpacing: AppTokens.space2,
    children: [
      for (var i = 0; i < hand.length; i++)
        GestureDetector(
          onTap: onToggle == null ? null : () => onToggle!(i),
          child: TileWidget(
            tile: Tile.parse(hand[i]),
            size: .hand,
            state: _stateOf(i),
          ),
        ),
    ],
  );

  /// Before checking only the picks show; after, a right pick is correct,
  /// a wrong pick incorrect, and a missed answer stays plain so the retry
  /// is not copying.
  TileState _stateOf(int i) =>
      switch ((isAnswered, picked.contains(i), answers.contains(i))) {
        (false, true, _) => .selected,
        (false, false, _) => .normal,
        (true, true, true) => .correct,
        (true, true, false) => .incorrect,
        (true, false, _) => .normal,
      };
}
