// AI-GENERATED by Claude (Claude Code), 2026-09-25
import 'package:material_ui/material_ui.dart';
import 'package:tenpai/shared/models/lesson_block.dart';
import 'package:tenpai/shared/models/tile.dart';
import 'package:tenpai/shared/theme/app_tokens.dart';
import 'package:tenpai/shared/widgets/primary_button_widget.dart';
import 'package:tenpai/shared/widgets/tile_widget.dart';

/// Handoff screen 6: two [Spacer]s centre the tile group in the free height
/// and pin the CTA to the bottom without measuring anything.
class ExplanationBlockWidget extends StatelessWidget {
  /// Nothing to check, so no session: « Continuer » advances directly.
  const ExplanationBlockWidget({
    super.key,
    required this.block,
    required this.onContinue,
  });

  /// The demo tile, title and body to show.
  final ExplanationBlock block;

  /// Advances to the next block or completes the lesson.
  final VoidCallback onContinue;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final scheme = theme.colorScheme;
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: AppTokens.sideMargin),
      child: Column(
        children: [
          const Spacer(),
          TileWidget(tile: Tile.parse(block.tile), size: .demo),
          const SizedBox(height: AppTokens.space4),
          Text(
            block.title,
            style: theme.textTheme.headlineSmall,
            textAlign: .center,
          ),
          const SizedBox(height: AppTokens.space2),
          Text(
            block.body,
            style: theme.textTheme.bodyLarge?.copyWith(
              color: scheme.onSurfaceVariant,
            ),
            textAlign: .center,
          ),
          const Spacer(),
          SafeArea(
            top: false,
            child: PrimaryButtonWidget(
              label: 'Continuer',
              onPressed: onContinue,
            ),
          ),
        ],
      ),
    );
  }
}
