// AI-GENERATED by Claude (Claude Code), 2026-09-25
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:material_ui/material_ui.dart';
import 'package:tenpai/sensei/sensei_panel_widget.dart';
import 'package:tenpai/sensei/sensei_providers.dart';
import 'package:tenpai/sensei/sensei_request.dart';
import 'package:tenpai/sensei/sensei_state.dart';
import 'package:tenpai/shared/theme/app_colors.dart';
import 'package:tenpai/shared/theme/app_tokens.dart';
import 'package:tenpai/shared/widgets/primary_button_widget.dart';

/// Bottom sheet of handoff screens 7–8; the « Continuer » CTA lives in it.
/// Always in the tree, slid off-screen by the parent until the block is
/// answered, so opening animates instead of popping in. Sized to content
/// (`mainAxisSize: .min`), never to the screen.
class FeedbackSheetWidget extends ConsumerWidget {
  /// [missLine] defaults to the quiz sentence; other blocks pass their own.
  const FeedbackSheetWidget({
    super.key,
    required this.isCorrect,
    required this.feedback,
    required this.onContinue,
    required this.onRetry,
    this.whyRequest,
    this.missLine = "Ce n'est pas la bonne tuile. Regardez encore la main.",
  });

  /// Picks tint, title and CTA colour; the parent derives it from the session
  /// so the sheet never re-checks the answer itself.
  final bool isCorrect;

  /// The authored line, shown only on a hit; a miss shows [missLine]
  /// instead, then « Pourquoi ? » (see [whyRequest]).
  final String feedback;

  /// The hit CTA « Continuer », the same callback as the block's own:
  /// advances or, on the last block, completes the lesson.
  final VoidCallback onContinue;

  /// The miss CTA « Réessayer »: resets the same block. A miss never
  /// reaches [onContinue], so a lesson cannot end on a wrong answer.
  final VoidCallback onRetry;

  /// Non-null only on a checked miss: keys the Sensei provider the sheet
  /// watches, so « Pourquoi ? » shows while idle and the panel afterwards.
  /// Null before checking and on a hit, hence no request exists off-screen.
  final SenseiRequest? whyRequest;

  /// Second line on a miss; the quiz keeps the default, the drill passes its own.
  final String missLine;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final theme = Theme.of(context);
    final scheme = theme.colorScheme;
    final colors = theme.extension<AppColors>()!;
    final (bg, fg, title, line, cta, onCta) = isCorrect
        ? (
            colors.successPanel,
            colors.bambooText,
            'Bien joué !',
            feedback,
            'Continuer',
            onContinue,
          )
        : (
            colors.errorPanel,
            colors.vermillionText,
            'Pas tout à fait',
            missLine,
            'Réessayer',
            onRetry,
          );
    return DecoratedBox(
      decoration: BoxDecoration(color: bg, borderRadius: AppTokens.radiusSheet),
      child: Padding(
        padding: const EdgeInsets.all(AppTokens.sideMargin),
        child: SafeArea(
          top: false,
          child: Column(
            mainAxisSize: .min,
            crossAxisAlignment: .start,
            children: [
              Text(
                title,
                style: theme.textTheme.titleLarge?.copyWith(color: fg),
              ),
              const SizedBox(height: AppTokens.space1),
              Text(line, style: theme.textTheme.bodyMedium),
              if (whyRequest case final request?) ...[
                const SizedBox(height: AppTokens.space1),
                switch (ref.watch(senseiProvider(request))) {
                  SenseiIdle() => _WhyLink(
                    onTap: ref.read(senseiProvider(request).notifier).ask,
                  ),
                  _ => SenseiPanelWidget(request: request, autoStart: false),
                },
              ],
              const SizedBox(height: AppTokens.space2),
              PrimaryButtonWidget(
                label: cta,
                onPressed: onCta,
                color: isCorrect ? null : scheme.error,
              ),
            ],
          ),
        ),
      ),
    );
  }
}

/// Handoff 08: discreet underlined link under the miss line. Tapping asks the
/// Sensei once; the sheet swaps it for the panel as soon as the state leaves
/// idle.
class _WhyLink extends StatelessWidget {
  const _WhyLink({required this.onTap});
  final VoidCallback onTap;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final colors = theme.extension<AppColors>()!;
    return TextButton(
      onPressed: onTap,
      style: TextButton.styleFrom(padding: EdgeInsets.zero),
      child: Text(
        'Pourquoi ?',
        style: theme.textTheme.bodyMedium?.copyWith(
          color: colors.mutedStrong,
          decoration: .underline,
        ),
      ),
    );
  }
}
