// AI-GENERATED by Claude (Claude Code), 2026-09-25
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:material_ui/material_ui.dart';
import 'package:tenpai/learning/lesson_providers.dart';
import 'package:tenpai/learning/lesson_session.dart';
import 'package:tenpai/learning/widgets/checkable_block_widget.dart';
import 'package:tenpai/learning/widgets/feedback_sheet_widget.dart';
import 'package:tenpai/shared/models/lesson_block.dart';
import 'package:tenpai/shared/models/tile.dart';
import 'package:tenpai/shared/theme/app_colors.dart';
import 'package:tenpai/shared/theme/app_tokens.dart';
import 'package:tenpai/shared/widgets/tile_size.dart';
import 'package:tenpai/shared/widgets/tile_state.dart';
import 'package:tenpai/shared/widgets/tile_widget.dart';

/// « Complete the group »: one pick from the rack, checked like a quiz
/// (`selectedOption` against `correctIndex`); once answered the pick fills
/// the empty slot. Same sheet, no « Pourquoi ? ».
class InteractiveBlockWidget extends ConsumerWidget {
  /// [session] is passed down rather than watched here: the lesson body
  /// already watches it, so the block rebuilds with it.
  const InteractiveBlockWidget({
    super.key,
    required this.block,
    required this.session,
    required this.onContinue,
  });

  /// The partial group, slot position, rack and authored answer.
  final InteractiveBlock block;

  /// Current rack pick and answered flag for this lesson.
  final LessonSession session;

  /// Advances to the next block or completes the lesson.
  final VoidCallback onContinue;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final notifier = ref.read(currentLessonProvider(session.lessonId).notifier);
    return CheckableBlockWidget(
      prompt: block.prompt,
      body: [
        _GroupRow(
          group: block.group,
          slot: block.slot,
          filled: session.isAnswered
              ? Tile.parse(block.rack[session.selectedOption!])
              : null,
          filledState: session.selectedOption == block.correctIndex
              ? .correct
              : .incorrect,
        ),
        const SizedBox(height: AppTokens.space4),
        _Rack(
          rack: block.rack,
          correctIndex: block.correctIndex,
          selected: session.selectedOption,
          isAnswered: session.isAnswered,
          onSelect: session.isAnswered ? null : notifier.select,
        ),
      ],
      onCheck: session.selectedOption == null || session.isAnswered
          ? null
          : notifier.check,
      isAnswered: session.isAnswered,
      sheet: FeedbackSheetWidget(
        isCorrect: session.selectedOption == block.correctIndex,
        feedback: block.feedback,
        missLine: 'La bonne tuile est entourée de vert.',
        onContinue: onContinue,
      ),
    );
  }
}

/// The partial group with the slot inserted at its position; [filled] is
/// null until the block is answered, then shows the pick in [filledState].
class _GroupRow extends StatelessWidget {
  const _GroupRow({
    required this.group,
    required this.slot,
    required this.filled,
    required this.filledState,
  });
  final List<String> group;
  final int slot;
  final Tile? filled;
  final TileState filledState;
  @override
  Widget build(BuildContext context) {
    final tiles = <Widget>[
      for (final code in group)
        TileWidget(tile: Tile.parse(code), size: .option),
    ];
    tiles.insert(slot, switch (filled) {
      final tile? => TileWidget(tile: tile, size: .option, state: filledState),
      null => const _EmptySlot(),
    });
    return Row(
      mainAxisAlignment: .center,
      spacing: AppTokens.space1,
      children: tiles,
    );
  }
}

/// Tile-sized outline marking the missing tile. Solid, not dashed as in the
/// handoff: Flutter has no dashed border built in.
class _EmptySlot extends StatelessWidget {
  const _EmptySlot();

  @override
  Widget build(BuildContext context) {
    final colors = Theme.of(context).extension<AppColors>()!;
    return SizedBox(
      width: TileSize.option.width,
      height: TileSize.option.height,
      child: DecoratedBox(
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(TileSize.option.radius),
          border: Border.all(
            color: colors.track,
            width: AppTokens.backFrameWidth,
          ),
        ),
      ),
    );
  }
}

/// Up to six option-size tiles on one line (6 × 48 + 5 × 8 = 328 dp); after
/// checking, the right one is highlighted when the pick was wrong.
class _Rack extends StatelessWidget {
  const _Rack({
    required this.rack,
    required this.correctIndex,
    required this.selected,
    required this.isAnswered,
    this.onSelect,
  });
  final List<String> rack;
  final int correctIndex;
  final int? selected;
  final bool isAnswered;
  final ValueChanged<int>? onSelect;
  @override
  Widget build(BuildContext context) => Wrap(
    alignment: .center,
    spacing: AppTokens.space1,
    runSpacing: AppTokens.space2,
    children: [
      for (var i = 0; i < rack.length; i++)
        GestureDetector(
          onTap: onSelect == null ? null : () => onSelect!(i),
          child: TileWidget(
            tile: Tile.parse(rack[i]),
            size: .option,
            state: _stateOf(i),
          ),
        ),
    ],
  );
  TileState _stateOf(int i) =>
      switch ((isAnswered, selected == i, i == correctIndex)) {
        (false, true, _) => .selected,
        (false, false, _) => .normal,
        (true, true, true) => .correct,
        (true, true, false) => .incorrect,
        (true, false, true) => .highlighted,
        (true, false, false) => .normal,
      };
}
