// AI-GENERATED by Claude (Claude Code), 2026-09-25
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:material_ui/material_ui.dart';
import 'package:tenpai/learning/lesson_providers.dart';
import 'package:tenpai/learning/lesson_session.dart';
import 'package:tenpai/learning/widgets/checkable_block_widget.dart';
import 'package:tenpai/learning/widgets/feedback_sheet_widget.dart';
import 'package:tenpai/sensei/sensei_request.dart';
import 'package:tenpai/shared/models/lesson_block.dart';
import 'package:tenpai/shared/models/tile.dart';
import 'package:tenpai/shared/theme/app_colors.dart';
import 'package:tenpai/shared/theme/app_tokens.dart';
import 'package:tenpai/shared/widgets/tile_state.dart';
import 'package:tenpai/shared/widgets/tile_widget.dart';

/// Handoff screens 7–8. Reads [session] only; every change goes through the
/// notifier so the option state and the feedback sheet cannot disagree.
class QuizBlockWidget extends ConsumerWidget {
  /// [session] is passed down rather than watched here: the lesson body
  /// already watches it, so the block rebuilds with it.
  const QuizBlockWidget({
    super.key,
    required this.block,
    required this.session,
    required this.onContinue,
  });

  /// The question, hand, four options and authored answer.
  final QuizBlock block;

  /// Current selection and answered flag for this lesson.
  final LessonSession session;

  /// Advances to the next block or completes the lesson.
  final VoidCallback onContinue;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final notifier = ref.read(currentLessonProvider(session.lessonId).notifier);
    final chosen = session.selectedOption;
    final whyRequest =
        session.isAnswered && chosen != null && chosen != block.correctIndex
        ? SenseiRequest.quizMiss(
            question: block.question,
            hand: block.hand,
            options: block.options,
            chosenIndex: chosen,
          )
        : null;

    return CheckableBlockWidget(
      prompt: block.question,
      body: [
        _HandRow(hand: block.hand),
        const SizedBox(height: AppTokens.space3),
        _OptionGrid(
          block: block,
          session: session,
          onSelect: session.isAnswered ? null : notifier.select,
        ),
      ],
      onCheck: session.selectedOption == null || session.isAnswered
          ? null
          : notifier.check,
      isAnswered: session.isAnswered,
      sheet: FeedbackSheetWidget(
        isCorrect: session.selectedOption == block.correctIndex,
        feedback: block.feedback,
        onContinue: onContinue,
        onRetry: notifier.retry,
        whyRequest: whyRequest,
      ),
    );
  }
}

/// The 13-tile hand of a quiz in one line. Sized to fit 350 dp (390 minus
/// margins): 13 × 24 plus the gaps, so the gap cannot grow past 2.
class _HandRow extends StatelessWidget {
  const _HandRow({required this.hand});
  final List<String> hand;

  @override
  Widget build(BuildContext context) => Row(
    mainAxisAlignment: .center,
    spacing: AppTokens.handGap,
    children: [
      for (final code in hand) TileWidget(tile: Tile.parse(code), size: .small),
    ],
  );
}

/// The 2×2 option cards. Riverpod-free: selection goes out through
/// [onSelect], so this widget can be tested with a plain [LessonSession].
class _OptionGrid extends StatelessWidget {
  const _OptionGrid({
    required this.block,
    required this.session,
    this.onSelect,
  });
  final QuizBlock block;
  final LessonSession session;

  /// Null once answered: cards stop reacting to taps.
  final ValueChanged<int>? onSelect;

  @override
  Widget build(BuildContext context) => Column(
    spacing: AppTokens.space2,
    children: [
      for (final row in [(0, 1), (2, 3)])
        Row(
          spacing: AppTokens.space2,
          children: [
            for (final i in [row.$1, row.$2])
              Expanded(
                child: _OptionCard(
                  tile: Tile.parse(block.options[i]),
                  state: _stateOf(i),
                  onTap: onSelect == null ? null : () => onSelect!(i),
                ),
              ),
          ],
        ),
    ],
  );

  /// Before checking only the pick shows; after, the pick turns correct or
  /// incorrect. The right answer is never revealed: the learner retries.
  TileState _stateOf(int i) => switch ((
    session.isAnswered,
    session.selectedOption == i,
    i == block.correctIndex,
  )) {
    (false, true, _) => .selected,
    (true, true, true) => .correct,
    (true, true, false) => .incorrect,
    (false, false, _) => .normal,
    (true, false, _) => .normal,
  };
}

/// One option card (handoff screens 7–8). The ring is always drawn,
/// transparent when idle, so a card never shifts by its width on select.
class _OptionCard extends StatelessWidget {
  const _OptionCard({
    required this.tile,
    required this.state,
    required this.onTap,
  });

  /// The option itself; options are tile codes, never text.
  final Tile tile;

  /// Shared with the inner [TileWidget]: the card picks tint and ring from
  /// it, the tile draws its own ring and badge, so both always agree.
  final TileState state;

  /// Null once the block is answered, so the card stops reacting.
  final VoidCallback? onTap;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final scheme = theme.colorScheme;
    final colors = theme.extension<AppColors>()!;
    final (bg, ring) = switch (state) {
      .correct => (colors.successPanel, scheme.primary),
      .incorrect => (colors.errorCard, scheme.error),
      .selected || .highlighted => (scheme.surfaceContainer, scheme.primary),
      .normal || .faceDown => (scheme.surfaceContainer, Colors.transparent),
    };
    return GestureDetector(
      onTap: onTap,
      child: DecoratedBox(
        decoration: BoxDecoration(
          color: bg,
          boxShadow: AppTokens.shadowSurface,
          borderRadius: AppTokens.radiusCard,
          border: Border.all(color: ring, width: AppTokens.ringWidth),
        ),
        child: Padding(
          padding: const EdgeInsets.all(AppTokens.space2),
          child: Center(
            child: TileWidget(tile: tile, state: state, size: .option),
          ),
        ),
      ),
    );
  }
}
