// AI-GENERATED by Claude (Claude Code), 2026-09-23
// Firestore Security Rules tests. Run from the repository root:
//   firebase emulators:exec --only firestore "npm --prefix firebase/rules-test test"
// The emulator host comes from FIRESTORE_EMULATOR_HOST, set by emulators:exec.
import { readFileSync } from 'node:fs';
import { after, before, beforeEach, describe, it } from 'node:test';
import {
  assertFails,
  assertSucceeds,
  initializeTestEnvironment,
} from '@firebase/rules-unit-testing';
import {
  Timestamp,
  arrayUnion,
  deleteDoc,
  doc,
  getDoc,
  increment,
  serverTimestamp,
  setDoc,
  updateDoc,
} from 'firebase/firestore';

const rulesPath = new URL('../../firestore.rules', import.meta.url);

/** @type {import('@firebase/rules-unit-testing').RulesTestEnvironment} */
let env;

const alice = 'alice';
const bob = 'bob';

const profile = () => ({
  level: 'seen',
  dailyGoalMinutes: 10,
  createdAt: serverTimestamp(),
});

/** What the app writes on a lesson completion (FirestoreProgressRepository). */
const completion = (lessonId, xp) => ({
  completedLessonIds: arrayUnion(lessonId),
  xp: increment(xp),
  updatedAt: serverTimestamp(),
});

const db = (uid) => (uid ? env.authenticatedContext(uid) : env.unauthenticatedContext()).firestore();
const profileRef = (fs, uid) => doc(fs, 'users', uid);
const progressRef = (fs, uid) => doc(fs, 'users', uid, 'progress', 'current');

/** Writes past the rules to set up a scenario. */
const seed = (write) => env.withSecurityRulesDisabled((ctx) => write(ctx.firestore()));

before(async () => {
  env = await initializeTestEnvironment({
    projectId: 'tenpai-rules-test',
    firestore: { rules: readFileSync(rulesPath, 'utf8') },
  });
});

beforeEach(() => env.clearFirestore());
after(() => env.cleanup());

describe('users/{uid} (profile)', () => {
  it('owner creates a valid profile and reads it back', async () => {
    const fs = db(alice);
    await assertSucceeds(setDoc(profileRef(fs, alice), profile()));
    await assertSucceeds(getDoc(profileRef(fs, alice)));
  });

  it('another user can neither read nor write it', async () => {
    await seed((fs) => setDoc(profileRef(fs, alice), profile()));
    const fs = db(bob);
    await assertFails(getDoc(profileRef(fs, alice)));
    await assertFails(setDoc(profileRef(fs, alice), profile()));
  });

  it('unauthenticated access is denied', async () => {
    const fs = db(null);
    await assertFails(getDoc(profileRef(fs, alice)));
    await assertFails(setDoc(profileRef(fs, alice), profile()));
  });

  it('rejects an unknown level', async () => {
    const fs = db(alice);
    await assertFails(setDoc(profileRef(fs, alice), { ...profile(), level: 'pro' }));
  });

  it('rejects a daily goal outside 5/10/15/20', async () => {
    const fs = db(alice);
    await assertFails(setDoc(profileRef(fs, alice), { ...profile(), dailyGoalMinutes: 7 }));
  });

  it('rejects extra fields', async () => {
    const fs = db(alice);
    await assertFails(setDoc(profileRef(fs, alice), { ...profile(), xp: 9999 }));
  });

  it('rejects a client-side createdAt', async () => {
    const fs = db(alice);
    await assertFails(
      setDoc(profileRef(fs, alice), { ...profile(), createdAt: Timestamp.now() }),
    );
  });

  it('allows changing answers later but not the creation date', async () => {
    await seed((fs) => setDoc(profileRef(fs, alice), profile()));
    const fs = db(alice);
    await assertSucceeds(updateDoc(profileRef(fs, alice), { dailyGoalMinutes: 20 }));
    await assertFails(updateDoc(profileRef(fs, alice), { createdAt: serverTimestamp() }));
  });

  it('never deletes', async () => {
    await seed((fs) => setDoc(profileRef(fs, alice), profile()));
    await assertFails(deleteDoc(profileRef(db(alice), alice)));
  });
});

describe('users/{uid}/progress/current', () => {
  it('first completion creates the document', async () => {
    const fs = db(alice);
    await assertSucceeds(
      setDoc(progressRef(fs, alice), completion('l1', 10), { merge: true }),
    );
    await assertSucceeds(getDoc(progressRef(fs, alice)));
  });

  it('another user is denied', async () => {
    const fs = db(bob);
    await assertFails(
      setDoc(progressRef(fs, alice), completion('l1', 10), { merge: true }),
    );
    await assertFails(getDoc(progressRef(fs, alice)));
  });

  it('a later completion adds one lesson and its XP', async () => {
    await seed((fs) => setDoc(progressRef(fs, alice), completion('l1', 10), { merge: true }));
    const fs = db(alice);
    await assertSucceeds(
      setDoc(progressRef(fs, alice), completion('l2', 10), { merge: true }),
    );
  });

  it('rejects more than 100 XP in one write', async () => {
    await seed((fs) => setDoc(progressRef(fs, alice), completion('l1', 10), { merge: true }));
    const fs = db(alice);
    await assertFails(
      setDoc(progressRef(fs, alice), completion('l2', 101), { merge: true }),
    );
    await assertFails(
      setDoc(progressRef(fs, alice), completion('l1', 500), { merge: true }),
    );
  });

  it('rejects a completion that adds no new lesson', async () => {
    await seed((fs) => setDoc(progressRef(fs, alice), completion('l1', 10), { merge: true }));
    const fs = db(alice);
    // arrayUnion of an existing id leaves the list as is: size does not grow.
    await assertFails(
      setDoc(progressRef(fs, alice), completion('l1', 10), { merge: true }),
    );
  });

  it('rejects removing a completed lesson or lowering XP', async () => {
    await seed((fs) => setDoc(progressRef(fs, alice), completion('l1', 10), { merge: true }));
    const fs = db(alice);
    await assertFails(
      setDoc(progressRef(fs, alice), {
        completedLessonIds: ['l2'],
        xp: 20,
        updatedAt: serverTimestamp(),
      }),
    );
    await assertFails(
      setDoc(progressRef(fs, alice), {
        completedLessonIds: ['l1', 'l2'],
        xp: 5,
        updatedAt: serverTimestamp(),
      }),
    );
  });

  it('rejects a client-side updatedAt and extra fields', async () => {
    const fs = db(alice);
    await assertFails(
      setDoc(progressRef(fs, alice), { ...completion('l1', 10), updatedAt: Timestamp.now() }, { merge: true }),
    );
    await assertFails(
      setDoc(progressRef(fs, alice), { ...completion('l1', 10), streak: 99 }, { merge: true }),
    );
  });

  it('never deletes', async () => {
    await seed((fs) => setDoc(progressRef(fs, alice), completion('l1', 10), { merge: true }));
    await assertFails(deleteDoc(progressRef(db(alice), alice)));
  });
});
