// AI-GENERATED by Claude (Claude Code), 2026-09-23
// Why: Test scaffolding is tedious and teaches no Flutter concept; the code under test is author-written.
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:tenpai/auth/auth_providers.dart';
import 'package:tenpai/auth/auth_user.dart';
import 'package:tenpai/profile/profile_providers.dart';
import 'package:tenpai/profile/user_profile.dart';

import '../fakes/fake_profile_repository.dart';

void main() {
  test('profileRepositoryProvider throws while nobody is signed in', () {
    // No Firebase in tests: the auth stream is faked as "signed out".
    final container = ProviderContainer.test(
      overrides: [
        authStateProvider.overrideWith((_) => Stream<AuthUser?>.value(null)),
      ],
    );

    // Riverpod 3 wraps a throwing `create` in a ProviderException that only
    // `package:riverpod/misc.dart` exports (a transitive dependency here),
    // so the guard is matched by its message.
    expect(
      () => container.read(profileRepositoryProvider),
      throwsA(
        predicate<Object>((e) => '$e'.contains('needs a signed-in user')),
      ),
    );
  });

  group('userProfileProvider', () {
    late FakeProfileRepository repository;
    late ProviderContainer container;

    setUp(() {
      repository = FakeProfileRepository();
      container = ProviderContainer.test(
        overrides: [profileRepositoryProvider.overrideWithValue(repository)],
      );
    });

    test('loads null while onboarding is not complete', () async {
      final profile = await container.read(userProfileProvider.future);

      expect(profile, isNull);
    });

    test('complete saves and exposes the new profile', () async {
      await container.read(userProfileProvider.future);

      await container
          .read(userProfileProvider.notifier)
          .complete(level: MahjongLevel.seen, dailyGoalMinutes: 10);

      expect(repository.saveCalls, [
        const UserProfile(level: MahjongLevel.seen, dailyGoalMinutes: 10),
      ]);
      expect(
        container.read(userProfileProvider),
        const AsyncData<UserProfile?>(
          UserProfile(level: MahjongLevel.seen, dailyGoalMinutes: 10),
        ),
      );
    });
  });
}
