// AI-GENERATED by Claude (Claude Code), 2026-09-23
// Why: Test scaffolding is tedious and teaches no Flutter concept; the code under test is author-written.
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:material_ui/material_ui.dart';
import 'package:tenpai/auth/auth_providers.dart';
import 'package:tenpai/auth/auth_user.dart';
import 'package:tenpai/profile/profile_providers.dart';
import 'package:tenpai/profile/profile_screen.dart';
import 'package:tenpai/profile/user_profile.dart';
import 'package:tenpai/progress/progress_providers.dart';
import 'package:tenpai/progress/user_progress.dart';
import 'package:tenpai/shared/theme/app_theme.dart';

import '../fakes/fake_auth_repository.dart';
import '../fakes/fake_profile_repository.dart';
import '../fakes/fake_progress_repository.dart';

const _user = AuthUser(
  uid: 'u1',
  email: 'joueuse@example.com',
  providerId: 'password',
);

Future<FakeAuthRepository> _pumpProfile(WidgetTester tester) async {
  final authRepository = FakeAuthRepository();
  await tester.pumpWidget(
    ProviderScope(
      overrides: [
        authStateProvider.overrideWith((_) => Stream<AuthUser?>.value(_user)),
        authRepositoryProvider.overrideWithValue(authRepository),
        profileRepositoryProvider.overrideWithValue(
          FakeProfileRepository(
            profile: const UserProfile(
              level: MahjongLevel.seen,
              dailyGoalMinutes: 10,
            ),
          ),
        ),
        progressRepositoryProvider.overrideWithValue(
          FakeProgressRepository(
            const UserProgress(completedLessonIds: {'l1', 'l2'}, xp: 30),
          ),
        ),
      ],
      retry: (_, _) => null,
      child: MaterialApp(theme: lightTheme(), home: const ProfileScreen()),
    ),
  );
  await tester.pumpAndSettle();
  return authRepository;
}

void main() {
  group('ProfileScreen', () {
    testWidgets('shows the account, stats and onboarding answers', (
      tester,
    ) async {
      await _pumpProfile(tester);

      expect(find.text('joueuse@example.com'), findsOneWidget);
      expect(find.text('EMAIL'), findsOneWidget);
      expect(find.text('30'), findsOneWidget);
      expect(find.text('2'), findsOneWidget);
      expect(find.text("J'ai vu jouer"), findsOneWidget);
      expect(find.text('10 min / jour'), findsOneWidget);
    });

    testWidgets('tapping Se déconnecter calls signOut', (tester) async {
      final authRepository = await _pumpProfile(tester);

      await tester.tap(find.text('Se déconnecter'));
      await tester.pumpAndSettle();

      expect(authRepository.signOutCalls, 1);
    });
  });
}
