// AI-GENERATED by Claude (Claude Code), 2026-09-18
// Why: Test scaffolding is tedious and teaches no Flutter concept; the widget under test is author-written.
import 'package:flutter_svg/flutter_svg.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:material_ui/material_ui.dart';
import 'package:tenpai/shared/models/tile.dart';
import 'package:tenpai/shared/theme/app_theme.dart';
import 'package:tenpai/shared/widgets/tile_size.dart';
import 'package:tenpai/shared/widgets/tile_state.dart';
import 'package:tenpai/shared/widgets/tile_widget.dart';

Widget _harness(Widget child) => MaterialApp(
  theme: lightTheme(),
  darkTheme: darkTheme(),
  home: Scaffold(body: Center(child: child)),
);

void main() {
  group('TileWidget symbol', () {
    testWidgets('shows the tile art for a normal tile', (tester) async {
      await tester.pumpWidget(
        _harness(const TileWidget(tile: Tile(suit: TileSuit.man, number: 1))),
      );

      expect(find.byType(SvgPicture), findsOneWidget);
      final loader =
          tester.widget<SvgPicture>(find.byType(SvgPicture)).bytesLoader
              as SvgAssetLoader;
      expect(loader.assetName, endsWith('/1m.svg'));
    });

    testWidgets('hides the tile art for a face-down tile', (tester) async {
      await tester.pumpWidget(
        _harness(
          const TileWidget(
            tile: Tile(suit: TileSuit.man, number: 1),
            state: .faceDown,
          ),
        ),
      );

      expect(find.byType(SvgPicture), findsNothing);
    });
  });

  group('TileWidget badge', () {
    testWidgets('shows a check icon only when correct', (tester) async {
      await tester.pumpWidget(
        _harness(
          const TileWidget(
            tile: Tile(suit: TileSuit.pin, number: 5),
            state: .correct,
          ),
        ),
      );

      expect(find.byIcon(Icons.check), findsOneWidget);
      expect(find.byIcon(Icons.close), findsNothing);
    });

    testWidgets('shows a close icon only when incorrect', (tester) async {
      await tester.pumpWidget(
        _harness(
          const TileWidget(
            tile: Tile(suit: TileSuit.pin, number: 5),
            state: .incorrect,
          ),
        ),
      );

      expect(find.byIcon(Icons.close), findsOneWidget);
      expect(find.byIcon(Icons.check), findsNothing);
    });

    for (final state in [
      TileState.normal,
      TileState.selected,
      TileState.highlighted,
      TileState.faceDown,
    ]) {
      testWidgets('shows no badge for ${state.name}', (tester) async {
        await tester.pumpWidget(
          _harness(
            TileWidget(
              tile: const Tile(suit: TileSuit.sou, number: 3),
              state: state,
            ),
          ),
        );

        expect(find.byIcon(Icons.check), findsNothing);
        expect(find.byIcon(Icons.close), findsNothing);
      });
    }
  });

  group('TileWidget size', () {
    for (final size in TileSize.values) {
      testWidgets('renders at the ${size.name} dimensions', (tester) async {
        await tester.pumpWidget(
          _harness(
            TileWidget(
              tile: const Tile(suit: TileSuit.man, number: 2),
              size: size,
            ),
          ),
        );

        final rendered = tester.getSize(find.byType(AnimatedContainer));

        expect(rendered.width, size.width);
        expect(rendered.height, size.height);
      });
    }
  });

  group('TileWidget selection lift', () {
    testWidgets('translates the tile up by the tile lift once settled', (
      tester,
    ) async {
      await tester.pumpWidget(
        _harness(
          const TileWidget(
            tile: Tile(suit: TileSuit.man, number: 6),
            state: .selected,
          ),
        ),
      );
      await tester.pumpAndSettle();

      final container = tester.widget<AnimatedContainer>(
        find.byType(AnimatedContainer),
      );

      expect(container.transform!.getTranslation().y, -6);
    });

    testWidgets('animates the lift over the 250 ms token duration', (
      tester,
    ) async {
      const tile = Tile(suit: TileSuit.man, number: 6);

      await tester.pumpWidget(_harness(const TileWidget(tile: tile)));

      await tester.pumpWidget(
        _harness(const TileWidget(tile: tile, state: .selected)),
      );

      final transformInTile = find.descendant(
        of: find.byType(AnimatedContainer),
        matching: find.byType(Transform),
      );

      await tester.pump(const Duration(milliseconds: 125));
      final midway = tester
          .widget<Transform>(transformInTile)
          .transform
          .getTranslation()
          .y;

      expect(midway, lessThan(0));
      expect(midway, greaterThan(-6));

      await tester.pump(const Duration(milliseconds: 125));
      final settled = tester
          .widget<Transform>(transformInTile)
          .transform
          .getTranslation()
          .y;

      expect(settled, -6);
    });
  });
}
