// AI-GENERATED by Claude (Claude Code), 2026-09-18
// Why: Test scaffolding is tedious and teaches no Flutter concept; the widget under test is author-written.
import 'package:flutter_test/flutter_test.dart';
import 'package:tenpai/shared/widgets/tile_state.dart';

void main() {
  group('TileState', () {
    test('declares exactly the six documented states in order', () {
      expect(TileState.values, [
        TileState.normal,
        TileState.selected,
        TileState.correct,
        TileState.incorrect,
        TileState.highlighted,
        TileState.faceDown,
      ]);
    });
  });
}
