// AI-GENERATED by Claude (Claude Code), 2026-09-18
// Why: Test scaffolding is tedious and teaches no Flutter concept; the widget under test is author-written.
import 'package:flutter_test/flutter_test.dart';
import 'package:material_ui/material_ui.dart';
import 'package:tenpai/shared/models/tile.dart';
import 'package:tenpai/shared/theme/app_theme.dart';
import 'package:tenpai/shared/widgets/tile_state.dart';
import 'package:tenpai/shared/widgets/tile_widget.dart';

const _tile = Tile(suit: TileSuit.pin, number: 5, isRed: true);

// Regular is 64x88; this frame leaves 48 logical px on every side, enough
// for the badge overhang and the highlight halo to stay inside the capture.
Widget _frame({
  required TileState state,
  required ThemeMode mode,
  required Key boundaryKey,
}) => MaterialApp(
  theme: lightTheme(),
  darkTheme: darkTheme(),
  themeMode: mode,
  home: Scaffold(
    body: Center(
      child: RepaintBoundary(
        key: boundaryKey,
        child: SizedBox(
          width: 160,
          height: 184,
          child: Center(
            child: TileWidget(tile: _tile, state: state),
          ),
        ),
      ),
    ),
  ),
);

void main() {
  for (final state in TileState.values) {
    testWidgets('${state.name} tile matches its light golden', (tester) async {
      final boundaryKey = GlobalKey();
      await tester.pumpWidget(
        _frame(state: state, mode: .light, boundaryKey: boundaryKey),
      );
      await tester.pumpAndSettle();

      await expectLater(
        find.byKey(boundaryKey),
        matchesGoldenFile('goldens/tile_regular_${state.name}_light.png'),
      );
    });

    testWidgets('${state.name} tile matches its dark golden', (tester) async {
      final boundaryKey = GlobalKey();
      await tester.pumpWidget(
        _frame(state: state, mode: .dark, boundaryKey: boundaryKey),
      );
      await tester.pumpAndSettle();

      await expectLater(
        find.byKey(boundaryKey),
        matchesGoldenFile('goldens/tile_regular_${state.name}_dark.png'),
      );
    });
  }
}
