// AI-GENERATED by Claude (Claude Code), 2026-09-18
// Why: Test scaffolding is tedious and teaches no Flutter concept; the widget under test is author-written.
import 'package:flutter_test/flutter_test.dart';
import 'package:tenpai/shared/widgets/tile_size.dart';

void main() {
  group('TileSize', () {
    test('declares exactly the five documented sizes in order', () {
      expect(TileSize.values, [
        TileSize.small,
        TileSize.hand,
        TileSize.option,
        TileSize.regular,
        TileSize.demo,
      ]);
    });

    for (final size in TileSize.values) {
      test('${size.name} keeps roughly the 64:88 width:height ratio', () {
        // Design values are rounded to whole logical pixels, so small and
        // demo drift a couple percent from the exact 64:88 ratio.
        expect(size.width / size.height, closeTo(64 / 88, 0.03));
      });
    }

    test('radius grows with width across all sizes', () {
      final sorted = [...TileSize.values]
        ..sort((a, b) => a.width.compareTo(b.width));

      for (var i = 1; i < sorted.length; i++) {
        expect(sorted[i].radius, greaterThan(sorted[i - 1].radius));
      }
    });
  });
}
