// AI-GENERATED by Claude (Claude Code), 2026-09-23
// Why: Test scaffolding is tedious and teaches no Flutter concept; the code under test is author-written.
import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';
import 'package:tenpai/scanner/fake_tile_identifier.dart';
import 'package:tenpai/shared/models/tile.dart';

/// Same fold formula as `FakeTileIdentifier.identify`, used here only to pick
/// byte patterns that land on a particular branch — never to hardcode a
/// magic input without the check that justifies it.
int _hashOf(List<int> photo) {
  var h = 17;
  for (final b in photo) {
    h = h * 31 + b;
  }
  return h & 0x7fffffff;
}

void main() {
  group('FakeTileIdentifier', () {
    test('the same bytes always identify the same tile', () async {
      final identifier = FakeTileIdentifier();
      final photo = Uint8List.fromList([1, 2, 3, 4, 5]);

      final first = await identifier.identify(photo);
      final second = await identifier.identify(photo);

      expect(first, equals(second));
    });

    test(
      'a byte pattern whose hash is a multiple of five is unrecognised',
      () async {
        final photo = Uint8List.fromList([3]);
        expect(_hashOf(photo) % 5, 0);
        final identifier = FakeTileIdentifier();

        final tile = await identifier.identify(photo);

        expect(tile, isNull);
      },
    );

    test(
      'a byte pattern landing on an honour index returns an honour tile',
      () async {
        final photo = Uint8List.fromList([10]);
        final hash = _hashOf(photo);
        expect(hash % 5, isNot(0));
        expect(hash % 34, inInclusiveRange(27, 33));
        final identifier = FakeTileIdentifier();

        final tile = await identifier.identify(photo);

        expect(tile!.suit, TileSuit.honor);
        expect(tile.number, inInclusiveRange(1, 7));
      },
    );

    test(
      'every generated input yields a tile within the model bounds',
      () async {
        final identifier = FakeTileIdentifier();

        for (var i = 0; i < 200; i++) {
          final photo = Uint8List.fromList(
            List.generate(i % 20 + 1, (j) => (i * 7 + j) % 256),
          );

          final tile = await identifier.identify(photo);

          if (tile == null) continue;
          final maxNumber = tile.suit == .honor ? 7 : 9;
          expect(tile.number, inInclusiveRange(1, maxNumber));
        }
      },
    );

    test('isRed is set only for a red five on a suited tile', () async {
      // The red bit comes from the part of the hash the index does not use
      // (`hash ~/ 34`), so two fives can differ; both inputs are checked
      // against the formula rather than trusted.
      final redBytes = Uint8List.fromList([30]);
      final plainBytes = Uint8List.fromList([5]);
      expect(_hashOf(redBytes) % 34 % 9 + 1, 5);
      expect((_hashOf(redBytes) ~/ 34).isEven, isTrue);
      expect(_hashOf(plainBytes) % 34 % 9 + 1, 5);
      expect((_hashOf(plainBytes) ~/ 34).isEven, isFalse);
      final identifier = FakeTileIdentifier();
      final redFive = await identifier.identify(redBytes);
      final plainFive = await identifier.identify(plainBytes);

      expect(redFive!.number, 5);
      expect(redFive.suit, isNot(TileSuit.honor));
      expect(redFive.isRed, isTrue);

      expect(plainFive!.number, 5);
      expect(plainFive.suit, isNot(TileSuit.honor));
      expect(plainFive.isRed, isFalse);
    });
  });
}
