// AI-GENERATED by Claude (Claude Code), 2026-09-23
// Why: Test scaffolding is tedious and teaches no Flutter concept; the code under test is author-written.
import 'package:flutter_test/flutter_test.dart';
import 'package:tenpai/scanner/scan_state.dart';
import 'package:tenpai/shared/models/tile.dart';

const _tile = Tile(suit: .man, number: 1);

/// Exhaustive switch with no `default`: this is a compile-time check as much
/// as a runtime one — a variant missing from [ScanState] would fail to build.
String _describe(ScanState state) => switch (state) {
  ScanIdle() => 'idle',
  ScanAnalysing() => 'analysing',
  ScanFound() => 'found',
  ScanNotFound() => 'not found',
};

void main() {
  group('ScanState', () {
    test('the four variants are distinct', () {
      const idle = ScanState.idle();
      const analysing = ScanState.analysing();
      const found = ScanState.found(_tile);
      const notFound = ScanState.notFound();

      expect(idle, isNot(equals(analysing)));
      expect(idle, isNot(equals(found)));
      expect(idle, isNot(equals(notFound)));
      expect(analysing, isNot(equals(found)));
      expect(analysing, isNot(equals(notFound)));
      expect(found, isNot(equals(notFound)));
    });

    test('ScanFound is equal only for the same tile', () {
      const foundOne = ScanState.found(_tile);
      const foundSame = ScanState.found(Tile(suit: .man, number: 1));
      const foundOther = ScanState.found(Tile(suit: .pin, number: 5));

      expect(foundOne, equals(foundSame));
      expect(foundOne, isNot(equals(foundOther)));
    });

    test('an exhaustive switch compiles and covers every variant', () {
      expect(_describe(const ScanState.idle()), 'idle');
      expect(_describe(const ScanState.analysing()), 'analysing');
      expect(_describe(const ScanState.found(_tile)), 'found');
      expect(_describe(const ScanState.notFound()), 'not found');
    });
  });
}
