// AI-GENERATED by Claude (Claude Code), 2026-09-25
// Why: Test scaffolding is tedious and teaches no Flutter concept; the code under test is author-written.
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:material_ui/material_ui.dart';
import 'package:tenpai/scanner/scan_history_screen.dart';
import 'package:tenpai/scanner/scan_record.dart';
import 'package:tenpai/scanner/scanner_providers.dart';
import 'package:tenpai/shared/theme/app_theme.dart';

import '../fakes/fake_scan_history_repository.dart';

ScanRecord _record(String code, DateTime scannedAt) => ScanRecord()
  ..code = code
  ..scannedAt = scannedAt;

Future<void> _pumpHistory(
  WidgetTester tester, {
  required List<ScanRecord> seed,
}) async {
  await tester.pumpWidget(
    ProviderScope(
      overrides: [
        scanHistoryRepositoryProvider.overrideWithValue(
          FakeScanHistoryRepository(seed: seed),
        ),
      ],
      retry: (_, _) => null,
      child: MaterialApp(
        theme: lightTheme(),
        home: const ScanHistoryScreen(),
      ),
    ),
  );
  await tester.pumpAndSettle();
}

void main() {
  group('ScanHistoryScreen', () {
    testWidgets('an empty history shows the empty-state message', (
      tester,
    ) async {
      await _pumpHistory(tester, seed: []);

      expect(find.text('Aucune tuile scannée'), findsOneWidget);
    });

    testWidgets('shows one row per record, newest first as given', (
      tester,
    ) async {
      await _pumpHistory(
        tester,
        seed: [
          _record('5z', DateTime(2026, 9, 25)),
          _record('1m', DateTime(2026, 9, 20)),
        ],
      );

      expect(find.text('Dragon blanc'), findsOneWidget);
      expect(find.text('25/09/2026'), findsOneWidget);
      expect(find.text('1 de caractères'), findsOneWidget);
      expect(find.text('20/09/2026'), findsOneWidget);

      final titles = tester
          .widgetList<ListTile>(find.byType(ListTile))
          .map((t) => (t.title! as Text).data)
          .toList();
      expect(titles, ['Dragon blanc', '1 de caractères']);
    });
  });
}
