// AI-GENERATED by Claude (Claude Code), 2026-09-23
// Why: Test scaffolding is tedious and teaches no Flutter concept; the code under test is author-written.
import 'dart:async';
import 'dart:typed_data';

import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:material_ui/material_ui.dart';
import 'package:tenpai/scanner/scanner_providers.dart';
import 'package:tenpai/scanner/scanner_screen.dart';
import 'package:tenpai/scanner/tile_identifier.dart';
import 'package:tenpai/scanner/tile_photo_source.dart';
import 'package:tenpai/sensei/sensei_providers.dart';
import 'package:tenpai/shared/models/tile.dart';
import 'package:tenpai/shared/theme/app_theme.dart';

import '../fakes/fake_scan_history_repository.dart';
import '../fakes/fake_sensei_repository.dart';
import '../fakes/fake_tile_identifier.dart';
import '../fakes/fake_tile_photo_source.dart';

final _photo = Uint8List.fromList([1, 2, 3]);

/// A capture that stays open until the test completes it: the only way to
/// observe the analysing state, which the scripted fake leaves instantly.
class _PendingPhotoSource implements TilePhotoSource {
  final completer = Completer<Uint8List?>();

  @override
  Future<Uint8List?> capture() => completer.future;
}

Future<void> _pumpScanner(
  WidgetTester tester, {
  required TilePhotoSource photos,
  required TileIdentifier identifier,
  ScriptedSenseiRepository? sensei,
}) async {
  await tester.pumpWidget(
    ProviderScope(
      overrides: [
        tilePhotoSourceProvider.overrideWithValue(photos),
        tileIdentifierProvider.overrideWithValue(identifier),
        senseiRepositoryProvider.overrideWithValue(
          sensei ?? ScriptedSenseiRepository(),
        ),
        scanHistoryRepositoryProvider.overrideWithValue(
          FakeScanHistoryRepository(),
        ),
      ],
      retry: (_, _) => null,
      child: MaterialApp(theme: lightTheme(), home: const ScannerScreen()),
    ),
  );
  await tester.pumpAndSettle();
}

/// Drives a fixed number of frames instead of `pumpAndSettle`: once a result
/// sheet mounts its Sensei panel and the panel starts loading, the
/// pulsing-tiles animation repeats forever and `pumpAndSettle` would never
/// return.
Future<void> _pumpFrames(WidgetTester tester, [int count = 10]) async {
  for (var i = 0; i < count; i++) {
    await tester.pump(const Duration(milliseconds: 16));
  }
}

/// The shutter is the only InkWell on the idle viewfinder; the sheets add
/// their own through the CTA, so callers only use this while no sheet shows.
Finder get _shutter => find.byType(InkWell);

void main() {
  group('ScannerScreen', () {
    testWidgets('idle shows the viewfinder and no sheet', (tester) async {
      await _pumpScanner(
        tester,
        photos: FakeTilePhotoSource.cancelled(),
        identifier: ScriptedTileIdentifier(),
      );

      expect(find.text('Cadrez une tuile'), findsOneWidget);
      expect(find.text('[ FLUX CAMÉRA ]'), findsOneWidget);
      expect(find.text('Tuile non reconnue'), findsNothing);
      expect(find.text('Scanner une autre tuile'), findsNothing);
      expect(tester.widget<InkWell>(_shutter).onTap, isNotNull);
    });

    testWidgets('the shutter opens the camera once', (tester) async {
      final photos = FakeTilePhotoSource.cancelled();
      await _pumpScanner(
        tester,
        photos: photos,
        identifier: ScriptedTileIdentifier(),
      );

      await tester.tap(_shutter);
      await tester.pumpAndSettle();

      expect(photos.captures, 1);
    });

    testWidgets('the shutter is disabled while a scan runs', (tester) async {
      final photos = _PendingPhotoSource();
      await _pumpScanner(
        tester,
        photos: photos,
        identifier: ScriptedTileIdentifier(),
      );

      await tester.tap(_shutter);
      await tester.pump();

      expect(tester.widget<InkWell>(_shutter).onTap, isNull);
      final dimmed = tester.widget<Opacity>(
        find.ancestor(of: _shutter, matching: find.byType(Opacity)),
      );
      expect(dimmed.opacity, lessThan(1));

      // Let the flow finish so nothing touches a disposed notifier.
      photos.completer.complete(null);
      await tester.pumpAndSettle();
      expect(tester.widget<InkWell>(_shutter).onTap, isNotNull);
    });

    testWidgets('a recognised tile opens the result sheet', (tester) async {
      final sensei = ScriptedSenseiRepository();
      await _pumpScanner(
        tester,
        photos: FakeTilePhotoSource.returning(_photo),
        identifier: ScriptedTileIdentifier(tile: Tile.parse('5z')),
        sensei: sensei,
      );

      await tester.tap(_shutter);
      await _pumpFrames(tester);

      expect(find.text('Dragon blanc'), findsOneWidget);
      expect(find.text('HONNEURS'), findsOneWidget);
      expect(find.text('Scanner une autre tuile'), findsOneWidget);
      expect(find.text('Le sensei regarde la tuile'), findsOneWidget);
      expect(sensei.callCount, 1);
    });

    testWidgets('a red five gets the aka dora prefix', (tester) async {
      await _pumpScanner(
        tester,
        photos: FakeTilePhotoSource.returning(_photo),
        identifier: ScriptedTileIdentifier(tile: Tile.parse('5pr')),
      );

      await tester.tap(_shutter);
      await _pumpFrames(tester);

      expect(find.text('5 de cercles rouge'), findsOneWidget);
      expect(find.text('AKA DORA · FAMILLE DES CERCLES'), findsOneWidget);
    });

    testWidgets('nothing recognised opens the failure sheet and Réessayer '
        'opens the camera again', (tester) async {
      final photos = FakeTilePhotoSource([_photo, _photo]);
      await _pumpScanner(
        tester,
        photos: photos,
        identifier: ScriptedTileIdentifier(),
      );

      await tester.tap(_shutter);
      await tester.pumpAndSettle();

      expect(find.text('Tuile non reconnue'), findsOneWidget);
      expect(find.text("RIEN D'IDENTIFIÉ"), findsOneWidget);
      expect(find.text('Réessayer'), findsOneWidget);

      await tester.tap(find.text('Réessayer'));
      await tester.pumpAndSettle();

      expect(photos.captures, 2);
    });

    testWidgets('a cancelled camera returns to the viewfinder', (tester) async {
      await _pumpScanner(
        tester,
        photos: FakeTilePhotoSource.cancelled(),
        identifier: ScriptedTileIdentifier(tile: Tile.parse('1m')),
      );

      await tester.tap(_shutter);
      await tester.pumpAndSettle();

      expect(find.text('Cadrez une tuile'), findsOneWidget);
      expect(find.text('Tuile non reconnue'), findsNothing);
      expect(find.text('Scanner une autre tuile'), findsNothing);
      expect(tester.widget<InkWell>(_shutter).onTap, isNotNull);
    });
  });
}
