// AI-GENERATED by Claude (Claude Code), 2026-09-23
// Why: Test scaffolding is tedious and teaches no Flutter concept; the code under test is author-written.
import 'dart:async';
import 'dart:typed_data';

import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:tenpai/scanner/scan_history_repository.dart';
import 'package:tenpai/scanner/scan_record.dart';
import 'package:tenpai/scanner/scan_state.dart';
import 'package:tenpai/scanner/scanner_providers.dart';
import 'package:tenpai/scanner/tile_identifier.dart';
import 'package:tenpai/scanner/tile_photo_source.dart';
import 'package:tenpai/shared/models/tile.dart';

import '../fakes/fake_scan_history_repository.dart';
import '../fakes/fake_tile_identifier.dart';
import '../fakes/fake_tile_photo_source.dart';

final _photo = Uint8List.fromList([1, 2, 3]);
const _tile = Tile(suit: .pin, number: 5, isRed: true);

/// Container with both scanner dependencies swapped for scripted fakes and a
/// listener collecting every state, first one included, so a test can assert
/// the whole walk and not only the final state. [history] defaults to a
/// fresh fake so a test that does not care about the write path never
/// touches `isarProvider` through the real repository.
({ProviderContainer container, List<ScanState> states}) _harness({
  required TilePhotoSource photos,
  required TileIdentifier identifier,
  ScanHistoryRepository? history,
}) {
  final container = ProviderContainer.test(
    overrides: [
      tilePhotoSourceProvider.overrideWithValue(photos),
      tileIdentifierProvider.overrideWithValue(identifier),
      scanHistoryRepositoryProvider.overrideWithValue(
        history ?? FakeScanHistoryRepository(),
      ),
    ],
  );
  final states = <ScanState>[];
  container.listen(
    scanProvider,
    (_, next) => states.add(next),
    fireImmediately: true,
  );
  return (container: container, states: states);
}

void main() {
  group('scanProvider', () {
    test('starts idle', () {
      final (:container, :states) = _harness(
        photos: FakeTilePhotoSource.cancelled(),
        identifier: ScriptedTileIdentifier(),
      );

      expect(container.read(scanProvider), const ScanState.idle());
      expect(states, [const ScanState.idle()]);
    });

    test('walks idle → analysing → found on a recognised photo', () async {
      final identifier = ScriptedTileIdentifier(tile: _tile);
      final (:container, :states) = _harness(
        photos: FakeTilePhotoSource.returning(_photo),
        identifier: identifier,
      );

      await container.read(scanProvider.notifier).scan();

      expect(states, [
        const ScanState.idle(),
        const ScanState.analysing(),
        const ScanState.found(_tile),
      ]);
      expect(identifier.lastPhoto, same(_photo));
    });

    test('goes back to idle when the camera is cancelled', () async {
      final identifier = ScriptedTileIdentifier(tile: _tile);
      final (:container, :states) = _harness(
        photos: FakeTilePhotoSource.cancelled(),
        identifier: identifier,
      );

      await container.read(scanProvider.notifier).scan();

      expect(states, [
        const ScanState.idle(),
        const ScanState.analysing(),
        const ScanState.idle(),
      ]);
      expect(identifier.lastPhoto, isNull, reason: 'nothing to identify');
    });

    test('ends notFound when the identifier recognises nothing', () async {
      final (:container, :states) = _harness(
        photos: FakeTilePhotoSource.returning(_photo),
        identifier: ScriptedTileIdentifier(),
      );

      await container.read(scanProvider.notifier).scan();

      expect(states.last, const ScanState.notFound());
    });

    test('ends notFound when the camera throws', () async {
      final (:container, :states) = _harness(
        photos: FakeTilePhotoSource.throwing(),
        identifier: ScriptedTileIdentifier(tile: _tile),
      );

      await container.read(scanProvider.notifier).scan();

      expect(states, [
        const ScanState.idle(),
        const ScanState.analysing(),
        const ScanState.notFound(),
      ]);
    });

    test('ends notFound when the identifier throws', () async {
      final (:container, :states) = _harness(
        photos: FakeTilePhotoSource.returning(_photo),
        identifier: ScriptedTileIdentifier.throwing(
          Exception('model unavailable'),
        ),
      );

      await container.read(scanProvider.notifier).scan();

      expect(states.last, const ScanState.notFound());
    });

    test('a second scan after a result runs the whole flow again', () async {
      final photos = FakeTilePhotoSource([_photo, null]);
      final (:container, :states) = _harness(
        photos: photos,
        identifier: ScriptedTileIdentifier(tile: _tile),
      );
      final notifier = container.read(scanProvider.notifier);

      await notifier.scan();
      await notifier.scan();

      expect(photos.captures, 2);
      expect(states, [
        const ScanState.idle(),
        const ScanState.analysing(),
        const ScanState.found(_tile),
        const ScanState.analysing(),
        const ScanState.idle(),
      ]);
    });

    test('scan(fromGallery: true) reaches the photo source', () async {
      final photos = FakeTilePhotoSource.returning(_photo);
      final (:container, states: _) = _harness(
        photos: photos,
        identifier: ScriptedTileIdentifier(tile: _tile),
      );

      await container.read(scanProvider.notifier).scan(fromGallery: true);

      expect(photos.lastFromGallery, isTrue);
    });

    test('a scan started while one is open is ignored', () async {
      final photos = _OpenCamera();
      final (:container, :states) = _harness(
        photos: photos,
        identifier: ScriptedTileIdentifier(tile: _tile),
      );
      final notifier = container.read(scanProvider.notifier);

      final first = notifier.scan();
      await notifier.scan();

      expect(photos.captures, 1, reason: 'no second camera session');
      expect(container.read(scanProvider), const ScanState.analysing());

      photos.completer.complete(_photo);
      await first;

      expect(states, [
        const ScanState.idle(),
        const ScanState.analysing(),
        const ScanState.found(_tile),
      ]);
    });

    test('a recognised tile is appended to the scan history', () async {
      final history = FakeScanHistoryRepository();
      final (:container, states: _) = _harness(
        photos: FakeTilePhotoSource.returning(_photo),
        identifier: ScriptedTileIdentifier(tile: _tile),
        history: history,
      );

      await container.read(scanProvider.notifier).scan();

      expect(history.addCalls, [_tile]);
    });

    test('nothing recognised does not touch the scan history', () async {
      final history = FakeScanHistoryRepository();
      final (:container, states: _) = _harness(
        photos: FakeTilePhotoSource.returning(_photo),
        identifier: ScriptedTileIdentifier(),
        history: history,
      );

      await container.read(scanProvider.notifier).scan();

      expect(history.addCalls, isEmpty);
    });

    test('a history write failure still leaves the result on screen', () async {
      final history = FakeScanHistoryRepository()
        ..error = Exception('disk full');
      final (:container, states: _) = _harness(
        photos: FakeTilePhotoSource.returning(_photo),
        identifier: ScriptedTileIdentifier(tile: _tile),
        history: history,
      );

      await container.read(scanProvider.notifier).scan();

      expect(container.read(scanProvider), const ScanState.found(_tile));
    });
  });

  group('masteredTilesProvider', () {
    test('counts distinct codes, not entries', () async {
      final history = FakeScanHistoryRepository(
        seed: [
          ScanRecord()
            ..code = '5p'
            ..scannedAt = DateTime(2026, 9, 25),
          ScanRecord()
            ..code = '1m'
            ..scannedAt = DateTime(2026, 9, 24),
          ScanRecord()
            ..code = '5p'
            ..scannedAt = DateTime(2026, 9, 23),
        ],
      );
      final container = ProviderContainer.test(
        overrides: [scanHistoryRepositoryProvider.overrideWithValue(history)],
        retry: (_, _) => null,
      );
      // A plain `read` leaves nothing listening to `scanHistoryProvider`, so
      // Riverpod pauses the underlying stream subscription and `.future`
      // never resolves; `listen` keeps it active for the length of the test.
      container.listen(scanHistoryProvider, (_, _) {});

      await container.read(scanHistoryProvider.future);

      expect(container.read(masteredTilesProvider), 2);
    });
  });
}

/// A camera that stays open until the test closes it, to observe what a
/// second press does while the first capture is still pending.
class _OpenCamera implements TilePhotoSource {
  final completer = Completer<Uint8List?>();
  int captures = 0;

  @override
  Future<Uint8List?> capture({bool fromGallery = false}) {
    captures++;
    return completer.future;
  }
}
