// AI-GENERATED by Claude (Claude Code), 2026-09-23
// Why: Test scaffolding is tedious and teaches no Flutter concept; the code under test is author-written.
import 'dart:typed_data';

import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:tenpai/scanner/scan_state.dart';
import 'package:tenpai/scanner/scanner_providers.dart';
import 'package:tenpai/scanner/tile_identifier.dart';
import 'package:tenpai/scanner/tile_photo_source.dart';
import 'package:tenpai/shared/models/tile.dart';

import '../fakes/fake_tile_identifier.dart';
import '../fakes/fake_tile_photo_source.dart';

final _photo = Uint8List.fromList([1, 2, 3]);
const _tile = Tile(suit: .pin, number: 5, isRed: true);

/// Container with both scanner dependencies swapped for scripted fakes and a
/// listener collecting every state, first one included, so a test can assert
/// the whole walk and not only the final state.
({ProviderContainer container, List<ScanState> states}) _harness({
  required TilePhotoSource photos,
  required TileIdentifier identifier,
}) {
  final container = ProviderContainer.test(
    overrides: [
      tilePhotoSourceProvider.overrideWithValue(photos),
      tileIdentifierProvider.overrideWithValue(identifier),
    ],
  );
  final states = <ScanState>[];
  container.listen(
    scanProvider,
    (_, next) => states.add(next),
    fireImmediately: true,
  );
  return (container: container, states: states);
}

void main() {
  group('scanProvider', () {
    test('starts idle', () {
      final (:container, :states) = _harness(
        photos: FakeTilePhotoSource.cancelled(),
        identifier: ScriptedTileIdentifier(),
      );

      expect(container.read(scanProvider), const ScanState.idle());
      expect(states, [const ScanState.idle()]);
    });

    test('walks idle → analysing → found on a recognised photo', () async {
      final identifier = ScriptedTileIdentifier(tile: _tile);
      final (:container, :states) = _harness(
        photos: FakeTilePhotoSource.returning(_photo),
        identifier: identifier,
      );

      await container.read(scanProvider.notifier).scan();

      expect(states, [
        const ScanState.idle(),
        const ScanState.analysing(),
        const ScanState.found(_tile),
      ]);
      expect(identifier.lastPhoto, same(_photo));
    });

    test('goes back to idle when the camera is cancelled', () async {
      final identifier = ScriptedTileIdentifier(tile: _tile);
      final (:container, :states) = _harness(
        photos: FakeTilePhotoSource.cancelled(),
        identifier: identifier,
      );

      await container.read(scanProvider.notifier).scan();

      expect(states, [
        const ScanState.idle(),
        const ScanState.analysing(),
        const ScanState.idle(),
      ]);
      expect(identifier.lastPhoto, isNull, reason: 'nothing to identify');
    });

    test('ends notFound when the identifier recognises nothing', () async {
      final (:container, :states) = _harness(
        photos: FakeTilePhotoSource.returning(_photo),
        identifier: ScriptedTileIdentifier(),
      );

      await container.read(scanProvider.notifier).scan();

      expect(states.last, const ScanState.notFound());
    });

    test('ends notFound when the camera throws', () async {
      final (:container, :states) = _harness(
        photos: FakeTilePhotoSource.throwing(),
        identifier: ScriptedTileIdentifier(tile: _tile),
      );

      await container.read(scanProvider.notifier).scan();

      expect(states, [
        const ScanState.idle(),
        const ScanState.analysing(),
        const ScanState.notFound(),
      ]);
    });

    test('ends notFound when the identifier throws', () async {
      final (:container, :states) = _harness(
        photos: FakeTilePhotoSource.returning(_photo),
        identifier: ScriptedTileIdentifier.throwing(
          Exception('model unavailable'),
        ),
      );

      await container.read(scanProvider.notifier).scan();

      expect(states.last, const ScanState.notFound());
    });

    test('a second scan after a result runs the whole flow again', () async {
      final photos = FakeTilePhotoSource([_photo, null]);
      final (:container, :states) = _harness(
        photos: photos,
        identifier: ScriptedTileIdentifier(tile: _tile),
      );
      final notifier = container.read(scanProvider.notifier);

      await notifier.scan();
      await notifier.scan();

      expect(photos.captures, 2);
      expect(states, [
        const ScanState.idle(),
        const ScanState.analysing(),
        const ScanState.found(_tile),
        const ScanState.analysing(),
        const ScanState.idle(),
      ]);
    });
  });
}
