// AI-GENERATED by Claude (Claude Code), 2026-09-23
// Why: Test scaffolding is tedious and teaches no Flutter concept; the code under test is author-written.
import 'package:flutter_test/flutter_test.dart';
import 'package:tenpai/scanner/tile_labels.dart';
import 'package:tenpai/shared/models/tile.dart';

void main() {
  group('tileName', () {
    test('a red five names the suit with the red suffix', () {
      expect(tileName(Tile.parse('5pr')), '5 de cercles rouge');
    });

    test('a plain number tile names the suit', () {
      expect(tileName(Tile.parse('3m')), '3 de caractères');
      expect(tileName(Tile.parse('9s')), '9 de bambous');
    });

    test('honours use their own French names', () {
      expect(tileName(Tile.parse('1z')), "Vent d'est");
      expect(tileName(Tile.parse('7z')), 'Dragon rouge');
    });
  });

  group('tileFamily', () {
    test('a suited tile names its family', () {
      expect(tileFamily(Tile.parse('5p')), 'famille des cercles');
    });

    test('an honour is its own family', () {
      expect(tileFamily(Tile.parse('1z')), 'honneurs');
    });
  });
}
